### ISSUE TITLE
App icon is not centered

### ISSUE THREAD

**Issue by mohamedzerougdz** [deckerst/aves#1002]
**Describe the bug**
مرحبا اخي، اظن ان لم تنتبه لموضع الأيقونة جيدا.
عدم توسيط رمز ايقونة التطبيق في المنتصف منظر غير مريح.

**Screenshots**
![IMG_20240502_095018](https://github.com/deckerst/aves/assets/153401125/712d14ac-d1f5-47b4-9371-96ab1aa59f58)
![IMG_20240502_094550](https://github.com/deckerst/aves/assets/153401125/a6e54c94-c4db-4d32-afd4-3185682aaa74)

**Comment by deckerst** [comment]
Actually i did pay attention to this and it's off-centered on purpose. Because if it's perfectly centered, there's too much white space on the right side and the whole thing looks unbalanced. 

The manual offset i added may be too high, but in any case the perfectly centered version is not adequate.
