### ISSUE TITLE
Pinch to zoom difficult to trigger

### ISSUE THREAD

**Issue by Donkey-Doug** [deckerst/aves#101]
The pinch gesture to increase or decrease the number of columns is sometimes difficult to trigger. I think that when the grabber is visible, the gesture does not work.

By grabber I mean this thingy:
![Screenshot_20211007-220654_Aves_1](https://user-images.githubusercontent.com/50382414/136455088-0c9544f1-d709-45b9-b674-72b6ca2eb94d.png)

**Comment by Donkey-Doug** [comment]
I don't think my comment about the visible grabber is correct. shometimes it is just difficult to pinch to zoom.

**Comment by deckerst** [comment]
By any chance, do you feel it's slightly more difficult on the Album page than on the Collection page?

**Comment by Donkey-Doug** [comment]
> By any chance, do you feel it's slightly more difficult on the Album page than on the Collection page?

Not really

**Comment by Donkey-Doug** [comment]
Zoom  in gesture does not always work. Zoom out does. I first need to zoom out to zoom in.

Example:
https://www.swisstransfer.com/d/e127bc24-bc2d-4383-8b98-6646c365734d

**Comment by deckerst** [comment]
I slightly improved the gesture so that it will try to find a neighboring thumbnail when the center of the gesture was not directly over a thumbnail. This could happen for example if it was falling in the spacing between thumbnails, or when starting the gesture on a group header (if you use groups).

But I think the main issue here is that the app does not process multi-finger gestures the same way as native. When you use 2 fingers but they don't touch the screen at the same time, Aves currently starts a scrolling gesture with the second finger, while it should remember the first finger and start a scaling gesture. This is wrong, but I'm not sure yet if it's an issue with the framework I'm using or the app.

**Comment by petazonk** [comment]
I also noted this exact problem. That is trying to add more or less thumbnails is difficult and takes multiple goes. I haven't narrowed it down to exactly what is happening.

**Comment by Donkey-Doug** [comment]
Version 1.5.7 solves this issue. It is very smooth in this release. Thank you!
