### ISSUE TITLE
Missing Nominatim data

### ISSUE THREAD

**Issue by IzzySoft** [deckerst/aves#1019]
I've noticed for a while now that Nominatim data are often missing. Having returned from Portugal, out of ~1k photos only ~300 have any Nominatim data at all (country set to PRT), none of them have state or city information (while all of them have GPS data).

Now my 2 questions on this:

* What can I do to improve that? Some kind of rescan?
* Could I easily add at least country information to all apps in a given album, or even city information to multiple selected images?

A third question would of course be how this could be solved in a way not requiring manual editing. I've noticed a similar thing in Spain as well, where many photos just had ESP as country. Seems like I didn't have such issues with e.g. UK (where it even labeled "Scotland" as state and also had city information correct) or DE (cities set, though no states) or Cyprus (cities set).

**Comment by deckerst** [comment]
Aves finds countries/addresses in 2 distinct steps:
1) first a quick pass, completely offline and autonomously, using rough topographic boundaries to find the country, but not the full address. Because of the nature of the data, this is imprecise and it can easily miss locations (close to a coastline for example). Also, this give unlocalized country codes (e.g. `PRT`).
2) then another pass, requiring mobile services installed on the device (typically GMS, but in your case I suppose you plugged Nominatim), to do reverse geocoding. This is more precise and yields a full address, including the city and the country name in your local (e.g. `Portugal`). As far as I know, the mobile services require internet access to do reverse geocoding.

> What can I do to improve that? Some kind of rescan?

You could try to select the media items and in the top right menu select the `Rescan` action. But as I remember, I make Aves go through pass 2 on launch for media items that only got the country from pass 1, if mobile services are detected on the device.

Could you paste here the system info you get in `About` > `Bug Report`?

> Could I easily add at least country information to all apps in a given album, or even city information to multiple selected images?

If you do have a country code but no city, then I suppose the mobile services are not installed or they fail to do reverse geocoding. You could look into that.

If with your current setup even the country is missing, the only option would be to change the GPS coordinates in the metadata (you can do that in Aves). Or you could forgo GPS coordinates and derived address, and simply use tags for the country and/or city.

**Comment by IzzySoft** [comment]
Thanks for the details, Thibault!

> first a quick pass … then another pass

That explains numbers having got up (seems like there's some "delayed event" performing those scans?); meanwhile PRT has 467 entries (with no new photos/videos added in the last 2 days).

> You could try to select the media items and in the top right menu select the `Rescan` action.

Tried that with 2 example photos selected, details shown didn't change (just date, size and GPS displayed on top). Numbers in stats didn't change. Comparing with one of the photos from the PRT filter, it has PRT instead of the GPS coordinates.

> if mobile services are detected on the device.

As you correctly remember, this is the device we've talked about in the past and where the vendor provided a quick fix to make Nominatim working a little over a year ago. Setup didn't change since then, so Nominatim *per se* should still be working. Funny thing is, too, that some media from Portugal correctly get the PRT while others do not, and that with some other countries it seems to even work fully (e.g. during my stay in Aberdeen 9 month ago I get the full country as "United Kingdom", the state as "Scotland" and even the cities as Aberdeen, Stonehaven etc; some places in Spain work as well, where I have 1k correctly marked "Spain" (plus 354 just ESP) with cities like Valencia, Segovia, Toledo – Spain I visited in March/April; Germany seems to work entirely fine).

> Could you paste here the system info you get in `About` > `Bug Report`?

Sure: [aves_report.zip](https://github.com/deckerst/aves/files/15283483/aves_report.zip) contains the `about.txt` (copy-paste from step 2) and 2 log files (from step 1) where you'll be mostly interested in the second, which should cover the rescan run.

> If you do have a country code but no city, then I suppose the mobile services are not installed or they fail to do reverse geocoding. You could look into that.

That's what puzzles me: I didn't change a thing with them for at least half a year, and they worked fine for the media from Spain 1.5 months ago – at least partly (some still have ESP instead of Spain). If you give me a hint / steps to follow to narrow that down, I'll of course do that and provide you with the details – be it via Aves directly, via some FOSS helper app, or via ADB.

![image](https://github.com/deckerst/aves/assets/6781438/ca0ceb91-5fee-413e-866f-035233d56bfb)


> Or you could forgo GPS coordinates and derived address, and simply use tags for the country and/or city.

You mean, select the media, then add the e.g. `PRT` tag to them? I couldn't find a related menu entry for that. And doing that for hundreds of media manually is quite cumbersome (tried that for one but couldn't find "existing labels" listed, just the option to create a new tag or use any of the 3 placeholders Country, State, Place – I must have missed something there).

![image](https://github.com/deckerst/aves/assets/6781438/fde7e3df-cf7e-4372-99a3-23344c9ea1f4)

I've checked with the FAQ ([here in the wiki](https://github.com/deckerst/aves/wiki/FAQ#tags)), but it is not clear how to use any of the existing tags one did not manually create oneself).

**Comment by deckerst** [comment]
Lots to reply to, but I must go soon, so I'll just point out that in your system info I see `Mobile services: not available`.
From the point of view of Aves, there's no mobile services so it won't even try to do the reverse geocoding. Do you have `MicroG` installed? (`Nominatim` is just the reverse geocoder, right?)

**Comment by IzzySoft** [comment]
> actually mobile services are just checked for google map layers. Geocoding is separate.

Just to point out I'm running the "libre" variant here, that comes entirely without the Google Map layers even :wink: The device has microG installed, but all its Google connections (sign in, FCM etc) disabled.

**Comment by deckerst** [comment]
Geocoders typically requires being connected to the internet, so Aves checks connectivity before calling the geocoder (otherwise unconnected users would see these attempts take a long time before timeouts kick in).

Do you think a lack of connectivity on Aves launch could explain things in your case?

**Comment by deckerst** [comment]
> couldn't find "existing labels" listed

This is strange. In the tag editor, you should see a "Top Tags" section showing your existing tags (found in your collection, as they are listed in the `Tags` page) ordered by usage.
![Screenshot_20240512_192932_Aves](https://github.com/deckerst/aves/assets/13898333/e94f9c5b-12dd-4b5e-9252-6e3913b0c5dd)

If you go to the `Tags` page, is it empty?

**Comment by IzzySoft** [comment]
> Do you think a lack of connectivity on Aves launch could explain things in your case?

I don't think that's likely. The device Aves runs on here has a good data plan, and the rescan was done while on WiFi. Nor can I remember any connectivity issues **on that device** (my other one, an old FP2, needs a reboot every 2 weeks or so as it starts missing its SIM, or gets its WiFi "flaky" – but the SHIFT6mq runs stable as a rock).

> In the tag editor, you should see a "Top Tags" section

That's the section I'm missing! Hm, maybe something specific with the flavor? I'm running the "libre" one from F-Droid. Oh, and the device is still on Android 10, in case that matters.

Lemme cross-check, I've got the "normal" version on the FP2 (rarely use it there as it seems too heavy for that 32bit device – but that's a different issue)… Nope, no "Top Tags" there either. Ugh, but that's missing some updates, wow – still on 1.7.1, why? What's more strange: Aves does not show up there in the F-Droid client as "installed app", now I'm baffled. Querying the FP2 via ADB:

```bash
$ adb shell "pm list packages -3" |grep aves
package:deckers.thibault.aves.profile
```

Oof. That looks like some test version where we might have tried things in the past…

> If you go to the `Tags` page, is it empty?

Menu already says "Tags 0". So yes: "No tags".

**Comment by deckerst** [comment]
> The device Aves runs on here has a good data plan, and the rescan was done while on WiFi.

I see, thanks. I'll need to think of ways to debug this further.

> deckers.thibault.aves.profile

Yes, this is a test package. You can remove it.

> Menu already says "Tags 0". So yes: "No tags".

If you don't have existing tags, then it makes sense that you don't have the `Top Tags` section in the editor. I thought you were already using tags in your collection. In any case, tags are free text, you can add any text as a tag.

**Comment by IzzySoft** [comment]
> If you don't have existing tags

No manual ones, no. I was hoping to be able using the location tags there when they're missing, so they also show up in the stats. I make heavy use of albums, though, so this is less about finding images :wink:

> Yes, this is a test package. You can remove it.

I just uninstalled that test version from the FP2 and installed the full version from my repo. Starts up fine, but stays empty as if there were no images to show (~200 photos on that device). Rebooted the device, ran `adb logcat |egrep '(aves|flutter)', started Aves again – this is the [aves.log](https://github.com/deckerst/aves/files/15287470/aves.log) created by that. Screen says "Collection loading", nothing happens. So I unfortunately cannot cross-check there (I can make a separate issue for that if you want – but the FP2 isn't really suited to run large Flutter apps, and gets replaced here soon™ with a SHIFTphone8 as soon as that's ready.

But back to the issue at hand: Let me know if I can do anything to help finding the culprit. If you e.g. have a way I could try to manually query the system's Nominatim (e.g. via ADB, or a small sample app), or a version producing the relevant debug output, I could do that.

**Comment by deckerst** [comment]
> I was hoping to be able using the location tags there when they're missing

Ah, I see. This is actually a good idea. I'll try and think how I can make that possible in the future.

> But back to the issue at hand: Let me know if I can do anything to help finding the culprit. If you e.g. have a way I could try to manually query the system's Nominatim (e.g. via ADB, or a small sample app), or a version producing the relevant debug output, I could do that.

Sure. I'll try when I find the time.

**Comment by IzzySoft** [comment]
> Yes please, with the additional info from the instructions in About > Bug Report.

Will do. A wish at that place: would be good if step 2 could also be saved directly to a file instead of just to the clipboard. If one doesn't have a text editor on the device, it's a bit tricky to get those details to the PC one does the "browser stuff" in (I don't use Github etc. from my mobile devices). On the FP2 I have no editor… OK, managed to install one (had to reboot for that for some reason, time my new device arrives). Created #1022 for this.

Thanks a lot!

**Comment by deckerst** [comment]
@IzzySoft I've made a simple app to test the geocoder on your device:
https://drive.google.com/file/d/1g6SUIyPGrccTcgdhEzPh3F9xEccdYLgq/view?usp=sharing

Could you please try it?
1) open the app,
2) press "get address",
3) you should see 1 or 2 addresses, somewhere in Firenze.

**Comment by IzzySoft** [comment]
Apologies again: I usually do not take that long to respond, but closing for "no response" after just 2 weeks is a bit … err … unlucky when the question was raised just in the 1st week of a 3 week vacation :see_no_evil:

Same as with the other issue: I probably can test next week if you still want me to. Just let me know.

**Comment by deckerst** [comment]
No worries, I do not mind closing and reopening issues. When an issue like this is very much dependent on OP environment, I close it if OP is no longer available/responsive/interested. 

Same as the other issue: if the issue is still a problem for you, we can push the investigation. Otherwise let's forget about it.

**Comment by IzzySoft** [comment]
Must be something location specific. We've been on Cyprus again last year, same issue anew. This time a different device (SHIFTphone 8 running Android 15), so it's not that. But it's the same location again.

Hard to test from a place where it works; but if you have some ideas what I should/could check when I notice I'm in such area, let me know: I'll take notes, and see what I can find out there then. If you just need some coordinates to check with: [here you go](https://www.openstreetmap.org/search?query=protaras+cyprus#map=13/35.01496/34.05313) – just pick any place there in a 20 km range (probably the entire island, but I didn't check that; we've just been around where the needle sits, and up to the border at Deryneia).

If you think it's too specific, I understand. I suspect the default Nominatim service used by microG – not that much can be done about that one, as newer microG versions do no longer support those plugins anymore (it's [NominatimNlpBackend](https://f-droid.org/de/packages/org.microg.nlp.backend.nominatim/) for me here). If my guess is correct, maybe using something like the [Nominatim.org API](https://nominatim.org/) (optionally, or as fallback when the "normal lookup" fails) could be an option? There seems to be [a swagger for it here](https://sparkfabrik.github.io/nominatim-openapi/#/Reverse/reverse). There even seems to be [a Flutter library](https://pub.dev/packages/nominatim_flutter), directly interacting with nominatim.org.

**Comment by deckerst** [comment]
[NominatimNlpBackend](https://f-droid.org/de/packages/org.microg.nlp.backend.nominatim/) is backed by this [repo](https://github.com/microg/NominatimGeocoderBackend) where it states using "OSM Nominatim service". This is confirmed in this [code](https://github.com/microg/NominatimGeocoderBackend/blob/1e05aeb51f1676c8396ddb8fcd61bfefbe5867b4/src/main/java/org/microg/nlp/backend/nominatim/BackendService.java#L55) referring to `https://nominatim.openstreetmap.org`.

[Nominatim Flutter](https://pub.dev/packages/nominatim_flutter) can be configured to use a custom instance of Nominatim, but I can see via this [code](https://github.com/binhlam10796/nominatim_flutter/blob/d130777d1d6be62cb9e1ed8148bdcad20d67ee8c/lib/config/nominatim_configuration.dart#L21) that it also refers to `https://nominatim.openstreetmap.org`.

Using OSM Nominatim server is subject to this [policy](https://operations.osmfoundation.org/policies/nominatim/). The policy explicitly prohibits heavy usage, notably "maximum of 1 request per second". When Aves locates media, it tries to limit requests to new positions only, but it still might trigger many requests in short spans.

So, my comments:
- developers/users should stop considering that OSM and its services are free for all. It runs on donations, that's precious resources.
- maybe the issues you have with Nominatim is because of bans from OSM.
- if newer microG versions do not support your plugin for reverse geocoding, what do they provide as alternative?

**Comment by IzzySoft** [comment]
> maybe the issues you have with Nominatim is because of bans from OSM.

That would not explain why it always works e.g. in Germany, but never on Cyprus.

> if newer microG versions do not support your plugin for reverse geocoding, what do they provide as alternative?

The entire plugin system was dropped at one point. Marvin only supports things directly integrated with microG now. For "normal network location", that is MLS (via BeaconDB, as Mozilla no longer offers its service) – which only works online, not with a local DB, and some kind of Deja Vu (which requires you first collect the locations yourself). I have no idea what is used for Nominatim; my guess is whatever the Nominatim plugin used before. I've never updated to the newer versions, as I want my location data to stay on-device (which now reduced me to OpenCellID, as BeaconDB does not offer exports the way Mozilla did before).

----

I've just tried OSM with the location I gave you before: https://nominatim.openstreetmap.org/reverse?lat=35.01496&lon=34.05313 – response is correct, so it should have worked.

Would you consider a "fetch Nominatim" item in the photo's context menu (next to "edit location"), for photos missing those? It's a far shot, but maybe the nominatim server cannot be accessed from some networks (I could then try some of my Cyprus photos from here in Germany). Given one needs more than a second to reach that menu item for the next photo, that would be well inside the limits described by the policy (yes, I've skimmed it before my last comment). Apart from that, I'm out of ideas then…
