### ISSUE TITLE
Photo picker: support selecting multiple

### ISSUE THREAD

**Issue by pogobanane** [deckerst/aves#1028]
**Is your feature request related to a problem? Please describe.**
I want to send photos via Telegram or Whatsapp. In the messenger, i open "attachement > gallery > three dots top right > aves libre" which brings me into Aves's "PICK" menu. Now i want to select multiple photos that i previously marked as favorites in Aves. However i can only select one photo at a time which directly closes the menu and sends it. 

**Describe the solution you'd like**
In Aves's PICK menu, i want to long press and swipe over photos to select multiple. 

**Describe alternatives you've considered**
The alternative is to send each photo individually and clicking the 5-8 buttons to reach the menu again from which to send the next photo.

**Comment by deckerst** [comment]
Aves already supports it, but calling apps have to specify what they expect a single or multiple files. 

Anyway, you're in luck because it's already possible with the apps you mentioned: 
- Telegram: `attachment` > `File` > `Internal Storage` or `External Storage` (it opens the same system app) > select Aves in the `browser files in other apps` section
- Whatsapp: `attachment` > __long press__ `Gallery` > select Aves

And of course you can always do it the other way around, by selecting items in Aves first, then tap `Share` and select your target messenger app.
