### ISSUE TITLE
Select multiple files by clicking the first and the last one (with long press) 

### ISSUE THREAD

**Issue by xdaft** [deckerst/aves#104]
In multiple other galleries (simple gallery, quick Pic mod and etc) once you select a file and long press on another file it autoselects all the files inbitween.  Example: [Clumsy recording](https://imgur.com/a/YSLR1HL) . I use this very often but it is more like QoL than a must have feature.

**Comment by deckerst** [comment]
I didn't know this gesture, thanks for the discovery!

You probably know these gestures in Aves, but just in case:
1) as you start to select with a long-press you can drag and select multiple items at once,
2) when you long press and reach the screen edge it automatically scrolls,
3) you can pinch-to-zoom the thumbnails, so you can zoom out and see more thumbnails at once.

Given that, you can already select large swatchs of thumbnails with a single long press gesture, so I'm wondering how the gesture you describe helps.

The reason I'm interested in your use case is that I see downsides to that gesture:
1) I've seen non-power users who select items with a long-press each, not a tap. It's inefficient but that's how they do it, and they would be confused if the app suddenly selected multiple items while they only meant one,
2) even for users who are aware of all the gestures, that gesture would prevent selecting a contiguous set of items after starting the selection with a single item (e.g. select item 1 and then items 3~5 without selecting item 2).

By the way, Google Photos and Samsung Gallery do not implement that gesture. Maybe it's because of these downsides.
