### ISSUE TITLE
Edit metadata on videos

### ISSUE THREAD

**Issue by Donkey-Doug** [deckerst/aves#105]
Editing the date and removing metadata does not work on videos. The buttons are greyed out.

![Screenshot_20211012-210131_Aves](https://user-images.githubusercontent.com/50382414/137013887-9a3e02c8-e606-493f-8072-357bf52e6b58.png)

**Comment by Ingegneus** [comment]
might it be possible to read/write the metadata to existing sidecar files? it would be nicer to have the metadata directly in the file, but this might be temporary solution.

**Comment by deckerst** [comment]
Fair suggestion, but I won't support sidecar files. Among other reasons is a technical one: sidecar files are not media content, so it's out of scope, as [Aves is not a file manager](https://github.com/deckerst/aves/wiki/FAQ#no-file-manager=).

But here, the real issue is that I'm dragging my feet to implement MP4 metadata edition. I should tackle it, but I got carried away with more interesting stuff instead!

**Comment by kha84** [comment]
I spent a quite time analyzing all existing open source media managers - https://orange-pi-4-lts.blogspot.com/2022/09/ultimate-guide-to-linux-photo-media.html?m=1 - and even Digikam with all its recent move towards exiftool doesn't fully support that. If you implement this, you'll be the first hero ever.

**Comment by deckerst** [comment]
@kha84 nice write-up. That kind of summary is always useful.

> if you had any kind of GPS tracker with you, which was writing a .gpx track file.

Is that a use case for you? I thought about supporting this when i worked on location editing, but i personally don't need it and there was no explicit demand at the time.

As for videos, I've done some research and it seems writing metadata to MP4 could be done with simple libraries, but for other video formats only the big guns like exiftool or ffmpeg can handle them, and those heavy libraries are not an option for Aves.

**Comment by kha84** [comment]
Reg .gpx tracks - nopes I don't need that. I just put that to my post (it's still unfinished) to be a bit more fair to a guy who developed that software. Because it's definitely has a usecase. But just not for me.

From features perspective, my own requirements are fullfilled by Aves at 90%. What I'm missing is:

a) a way to put metadata to my mp4 videos I'm occasionally shooting with my phone. This is the most wanted thing.

b) some kind of OpenCV thing to recognize faces on photos. This is highly desirable, but can wait.

If that will be done, Aves becomes just a golden standard of how these kind of apps should be made like.

**Comment by xmha97** [comment]
# Set location to videos using exiftool
```
exiftool -GPSAltitude="0" -UserData:GPSCoordinates="34.6363, 50.874900000000004, 0" -Rotation="0" -XMP:GPSLatitude="34.6363" -XMP:GPSLongitude="50.874900000000004" -GPSLongitudeRef="West" -GPSLatitudeRef="North" VID_20221006_094430.mp4
```
https://www.google.com/maps/@34.6363,50.874900000000004,21z
cc: @deckerst

**Comment by deckerst** [comment]
@xmha97 see https://github.com/deckerst/aves/discussions/230

**Comment by deckerst** [comment]
MP4 only, see [wiki](https://github.com/deckerst/aves/wiki/Editing-Support) for support details.
