### ISSUE TITLE
Aves not listed as a gallery app by lineageOS camera

### ISSUE THREAD

**Issue by glemco** [deckerst/aves#1052]
**Describe the bug**

**To Reproduce**
1. Open LineageOS camera (org.lineageos.aperture version 14)
2. Click on the thumbnail in the bottom left corner
3. The system opens a gallery app, but Aves is not listed

**Expected behavior**

I can easily open Aves from the camera.

**Additional context**

I couldn't understand what kind of intent is used to open the gallery, probably something kind of strange because I couldn't intercept it with App Manager (io.github.muntashirakon.AppManager).

Tried also with other apps (from Fdroid):
Dot gallery (com.dot.gallery) works
Fossify gallery (org.fossify.gallery) doesn't
Image toolbox (ru.tech.imageresizershrinker) works but it isn't a gallery
Default lineageOS gallery (org.lineageos.glimpse) works

All galleries (including Aves and the App Manager interceptor) work fine with Open Camera, that makes me think Aperture uses some kind of new API.

LineageOS for MicroG 21 (Android 14) on Oneplus 8T
Aves 1.11.2 from IzzyOnDroid

Let me know if you need further information or logs, I'm not sure if you can install the camera on other ROMs, but you may try from https://github.com/Luciogi/aperture-camera-apk/releases or build from https://github.com/LineageOS/android_packages_apps_Aperture

Thanks and keep it up!

**Comment by deckerst** [comment]
Strange indeed. 
After installing the camera app, there is no image loaded yet at this point and tapping on the bottom left corner yields a common VIEW intent (without a specific image uri) which can be handled by the interceptor and typical gallery apps:
![Screenshot_20240615_184845_App Manager](https://github.com/deckerst/aves/assets/13898333/cee526dc-8c3a-45d4-86a7-adc6b90e1555)

But after capturing photos, tapping on the thumbnail directly opens Google Photos (no other gallery app on my device can handle this intent apparently). And as you mentioned the interceptor is skipped too.

If you can, i think it could be useful to raise an issue about this use case to `muntashirakon.AppManager`.

**Comment by deckerst** [comment]
From my couch search, i found https://developer.android.com/reference/android/provider/MediaStore#ACTION_REVIEW
Which is new since API 29 (Android Q).

Need to check in practice.

**Comment by glemco** [comment]
Wow, that was fast! Thank you.

> If you can, i think it could be useful to raise an issue about this use case to muntashirakon.AppManager

I can surely do it, but what is that exactly? Is it an intent or some other exotic thing (I'm not too familiar with android stuff)

**Comment by deckerst** [comment]
Yes, it was just this particular intent, nothing exotic in the end. Thanks for filing the issue.

**Comment by MrRinkana** [comment]
Is there a possibility to support the [ACTION_REVIEW_SECURE](https://developer.android.com/reference/android/provider/MediaStore#ACTION_REVIEW_SECURE) intent as well? Would allow for browsing pictures taken while device is locked (reviewing them)!

It's probably a bit more work as an activity that can display on the lock-screen is needed, that **only** shows the requested image and an explicit list of secondary images (probably other images taken in the same "camera session").

**Comment by deckerst** [comment]
Does this lineage camera app uses this secure intent too?

**Comment by deckerst** [comment]
@MrRinkana I didn't find a way to test this intent. The native camera apps that work on the lock screen are hard-coded to the native gallery apps, and the lineage camera app does not seem to use `ACTION_REVIEW_SECURE`. Anyway, i've tried to implement it in the blind. Could you test it? Or let me know how I could test it?

**Comment by MrRinkana** [comment]
I might have done some assuming. 

On my phone I run Sony's "photography pro" app, but on lineageOS, and clicking the small icon opens Aves if the phone is unlocked, otherwise the camera app closes, but unlocking the phone brings up aves on the latest picture, so I assumed that photography pro just failsafed to the "normal" review intent..

I have not figured out how to test the lineage camera from lockscreen, might have to uninstall the Sony app for that.. Nevertheless I can't build your commit (you are really fast btw) before I get home to my pc in a couple of days.

The [lineageos camera](https://github.com/search?q=repo%3ASebaUbuntu%2Fandroid_packages_apps_Aperture%20REVIEW_SECURE&type=code) has a call to the ...action.REVIEW_SECURE so without reading the code properly I would assume it uses the intent.

The description of review secure seems exactly like what is required for lockscreen previews, which I combined with the behaviour I was seeing and said assumptions - don't know more than that, sorry!
