### ISSUE TITLE
Retain original time stamp when converting/editing images

### ISSUE THREAD

**Issue by aherrig** [deckerst/aves#1071]
Having been pointed to Aves by a brother, I must say I really like this gallery app and its look and feel!

But noticed a shortcoming, which drives me away from it again: 
Converting pictures to smaller size by reducing jpeg quality and/or resolution, the _timestamp of the original is not preserved_. Instead, current time is set - such that the images appear as newer and further up in the gallery...
This hampers storing only the reduced size versions with consistent sorting on phone and computer, while getting rid of the large originals.

It might be an easy and fast fix, to _not change image time upon simple operations_ like converting, rotating or clipping. Or to offer the option of selecting how to handle time stamps - retain original time or use the current.

I would be really grateful if possible to change this behaviour, such that I don't have to look for an alternative gallery app.

Thanks, 
Andreas

**Comment by lordofscripts** [comment]
Actually, I find that unsettling as well. I noticed that adding tags, location, etc. changes the timestamp, as a result the gallery view gets cluttered with all these OLDER images as if they were new photos.

**Comment by deckerst** [comment]
When converting a media item, you can enable "write metadata" which includes the metadata date of the original item. If this is disable, the converted item is just a new file without metadata, so the date is the new file date.

Do you try to convert media items that already have a metadata date, or not? You can check this in the item `Info` page and check the exif/xmp sections.

> to not change image time upon simple operations

The `image time` can refer to so many dates. If you refer to a file date, it's out of scope for Aves, because [Aves is not a file manager, it's a gallery app](https://github.com/deckerst/aves/wiki/FAQ#is-aves-a-file-manager). If you refer to a metadata date, it's already handled with the "write metadata" option above.

**Comment by deckerst** [comment]
> I noticed that adding tags, location, etc. changes the timestamp

@lordofscripts as I explained above, the file date is not handled by Aves.

As for the metadata date:
- when moving/renaming an item that doesn't already have a metadata date, Aves will show a dialog suggesting to preserve the date. Maybe you rejected that suggestion and checked "do not ask again"? You can verify this via `Settings` > `Navigation` > `Confirmation dialogs` > `Ask before moving undated items`.
- when editing tags, location, etc. and the item does not have a metadata date already, it will write the current file date as a metadata date. With this, the date (as used in Aves) shouldn't change.

**Comment by lordofscripts** [comment]
> > I noticed that adding tags, location, etc. changes the timestamp
> 
> @lordofscripts as I explained above, the file date is not handled by Aves.
> 
> As for the metadata date:
> 
> * when moving/renaming an item that doesn't already have a metadata date, Aves will show a dialog suggesting to preserve the date. Maybe you rejected that suggestion and checked "do not ask again"? You can verify this via `Settings` > `Navigation` > `Confirmation dialogs` > `Ask before moving undated items`.

All of them are enabled.

**Comment by clemcer** [comment]
Hello, @deckerst, I hope it is okay that I ask you this question here, I didn't want to create the same issue again. 

I was wondering whether there are any future plans to include file manager features. 
I have just used aves to move my photos around and now the date is set to today in other gallery apps and my file manager which is not ideal. 

I understand that for Aves this isn't a problem as it uses the timestamp from the metadata.
But for me personally a perfect gallery app would allow me to sort and manage my photos accross albums without modifying them.

I undertand though that this is probably not that easy and you have your reasons as to why Aves works the way it does.
I just wanted to ask whether there are any plans to change this since I move around photos quite often and this is pretty much the only reason Aves hasn't really become my main Gallery yet.

**Comment by deckerst** [comment]
@clemcer Given current Android permission model and current store policy, Aves can only request specific permissions related to its core purpose. As a media gallery, it should not request permissions going beyond media management. Media management is not the same as file management. Without file management, some APIs are out of reach, so Aves cannot do whatever it wants with files.

Maybe, like many users, you got used to older Android where any app could request overreaching permissions and had unrestricted access to files. These days are over. As a developer this is a pain, but that's the current Android landscape.

**Comment by clemcer** [comment]
Okay, that's fair, thanks for your answer! 
You are probably right about me being used to the Samsung Gallery App but I gues I was also wondering because other FOSS Apps like [Fossify Gallery](https://github.com/FossifyOrg/Gallery) or [this one](https://github.com/IacobIonut01/Gallery) don't change the timestamp when moving photos.

But again, I understand that this i probably easier said than done and not the main focus ov Aves.

**Comment by aherrig** [comment]
The workaround I found shortly after my original comment above and became used to, is to correct the altered time stamps with the "Image & Video Date Fixer" app:
- moving the pictures to be stored and compressed to a respective folder (=album)
- changing resolution and quality with Aves, selecting the same folder as the target location, overwriting the originals
- running "Image & Video Date Fixer" over that folder to correct all images time stamps, where exif and file date differ. 

It came with a small invest to be able to do that in batch mode for large amounts of images - but it was worth it...

Best, 
Andreas

**Comment by clemcer** [comment]
Yes, that's also how I fixed it. I am now using Fossify Gallery to move photos around and Aves to look at them. Not ideal but it works.

**Comment by deckerst** [comment]
Can you achieve this with Fossify Gallery without giving it "all files management" permission? If you can I should look into it, maybe I'm missing something...

**Comment by clemcer** [comment]
I just checked and I think your assumption was right.

Fossify Gallery gives the option to just allow "all media access" instead of "all files access" with the warning that the app won't work as well if it can't manage all files.
And indeed, the timestamp only stays intact when the permission "all files access" is granted.

I guess this is nothing you will incorporate into Aves any time soon then, since you don't want Aves to have too many permissions?

**Comment by deckerst** [comment]
> I guess this is nothing you will incorporate into Aves any time soon then, since you don't want Aves to have too many permissions?

Rather than "many", I'd say "overreaching". Also, according to the Play Store policy, gallery apps can't request the "all files management" permission. To me the real mystery is that Fossify Gallery isn't rejected despite violating their policy. Might happen someday.

**Comment by clemcer** [comment]
Hm, maybe thats worth looking into. Out of five gallery apps I just installed four asked for that permission.

Oh, and I noticed something else: I might be wrong but reading through the last two [releases of Immich](https://github.com/immich-app/immich/releases ) makes me think that they are currently struggling to get that permission as well, so it probably isn't that easy.

I for one would be really happy if Aves ever gets this feature but I also totally understand that it's not that easy and might really be a hassle to get that permission from the play store.
