### ISSUE TITLE
Not on Play Store search

### ISSUE THREAD

**Issue by strider72** [deckerst/aves#109]
I can't find Aves in Play Store at all. Only can get to your page via direct link.  Perhaps this is why you don't have any reviews?

Number of downloads is "100null". Something hinky in the app entry

**Comment by deckerst** [comment]
Did you find it in the end?

There are no reviews on the Play Store because it's an open beta. Anybody can install and have fun with it, but reviews are not public, they're only private feedback. By the way, I'm actually surprised anybody managed to find it, as I've never publicized it anywhere.

> Number of downloads is "100null"

You probably saw that on the Aurora Store, no? I noticed this minor glitch, when there are fewer than 1000 downloads!

**Comment by strider72** [comment]
But yeah... Totally doesn't show up at all in Aurora Store

**Comment by deckerst** [comment]
> Somebody posted it to Reddit as a "hidden gem"

Wow, I already like that somebody.

I kept the app as a beta on the Play Store but the app is actually stable. At least it doesn't randomly delete photos by mistake, if that's your concern.

**Comment by strider72** [comment]
It's a solid app. My biggest request is soft delete ("recycle bin").  Also maybe let us set a default view.  But overall I'm really liking it. Impressive in a sea of lookalikes
