### ISSUE TITLE
The date resets when moving images to a different album

### ISSUE THREAD

**Issue by flexagoon** [deckerst/aves#111]
**Describe the bug**
When moving an image to a different album, the date gets reset and image is replaced with today

**To Reproduce**
1. Open any image
2. Check the date when it was made
3. Move it to a different album 
4. Check the date now

**Expected behavior**
The date should be preserved

**System information and logs:**
Aves version: 1.5.3 (Build 57)
Flutter version: 2.5.1 (Channel stable)
Android version: 11 (SDK 30)
Device: OnePlus HD1917
Google Play services: ready (I actually use microG)

**Comment by deckerst** [comment]
I will not automatically modify files when they are moved or renamed. This is not what users expect from these operations.

It's surprising that your photos didn't already have dates in their metadata. On my device (Galaxy S10e), even screenshots get automatically stamped an Exif date when they're created.

Often, people share images via social media or chat apps that automatically modify and strip metadata for privacy reasons (and saving bandwidth). If that's the case for you, maybe there's still a chance to give your images some kind of meaningful dates. Usually files downloaded that way have a name that includes a time stamp. It can be something like `IMG_20210901_142523_783.jpg` or `1600995564713.jpg`. This time stamp reflects the date and time you downloaded the file from the app. Are you in that situation?

**Comment by flexagoon** [comment]
@deckerst looks like https://github.com/deckerst/aves/commit/3c682b37b5cb38b977c2b438d4e47c96c5343494 adds the functionality to bulk edit metadata, right?

**Comment by deckerst** [comment]
@flexagoon have you tried to salvage dates from titles via bulk editing in Aves v1.5.5? To find dates in titles, I tried to make it automatic (so that users don't have to enter a cryptic pattern), but I wonder how well it will work for you in practice.

@Donkey-Doug you mentioned having the same issue. As you can see from the comments above, it's related to the way Android allows access to files. As far I know, you cannot preserve the modified date with the modern APIs from Android 11 on. Even on Android 10 and below, working with the older API is possible only on primary storage, not SD cards.

Instead of focusing on workflows bound to become obsolete, it's probably in their best interest for users to adapt to the way modern Android versions work. In other words, instead of relying on file properties (like file name and modified date), rely on metadata (like title and date as defined in EXIF/XMP).

**Comment by flexagoon** [comment]
@deckerst yes, I did try it, it works great, thanks!

Tho it would be cool if there was a "copy from modification date" option, so that you could set a date in bulk even for images that dont have a date in their name.

**Comment by deckerst** [comment]
> Tho it would be cool if there was a "copy from modification date" option, so that you could set a date in bulk even for images that dont have a date in their name.

@flexagoon Better late than never, it's in Aves v1.5.10!

**Comment by flexagoon** [comment]
@deckerst that's awesome, thank you!
