### ISSUE TITLE
[Android 10] [Realme UI] Can't delete files

### ISSUE THREAD

**Issue by D3ZOXY** [deckerst/aves#112]
**Describe the bug**
When I try to remove a file the app says: Failed to delete X item.

**To Reproduce**
1. Try to delete a file
2. See error

**Expected behavior**
The file should be deleted.

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem. If they are too private for this public space, feel free to [send them by email](mailto:gallery.aves@gmail.com).

**System information and logs:**
Aves version: 1.5.3 (Build 57)
Flutter version: 2.5.1 (Channel stable)
Android version: 10 (SDK 29)
Device: realme RMX1991
Google Play services: ready
Logs: https://www.upload.ee/files/13568591/aves-logs-20211020_231220.txt.html

**Additional context**

**Comment by deckerst** [comment]
Thanks for the bug report.

The log file you linked is empty (0 byte). Was it empty on your device?

Without more details about the file and situation, I won't be able to fix this issue.

When dealing with storage issues, it is important to know where the file is:
- which storage volume: the phone itself or a removable storage like SD card
- which folder: 1. the Download folder, 2. a media folder (within DCIM, Pictures, etc.), 3. the volume root, 4. another folder

Also, does it happen for every file? randomly? just once?
Did you try to delete the file from the Collection page? from the viewer?

**Comment by deckerst** [comment]
I can't reproduce it but I changed the way files are deleted or renamed on primary storage on Android 10 and lower. This may be related to #107 too.

I'll keep this issue open until I get your confirmation (whenever the next version of Aves gets released!)

**Comment by D3ZOXY** [comment]
The bug is still there. At first, the photo is deleted normally, then it reappears in the collection, I delete it again, and I get the error described above. However, if you restart the app, the photo is deleted.

**Comment by deckerst** [comment]
Maybe what's happening is this:
1) the first delete attempt successfully removes the file on storage, but the media is still registered by Android's Media Store. Aves shows media listed by the Android's Media Store, so that would explain why it reappears.
2) the second delete attempt reports failure because the file is already missing, but this second attempt triggered a refresh of the Android's Media Store and cleared the obsolete media entry.

To confirm this diagnostic, could you try the following:
1) make sure a certain media file exists on storage
2) in Aves, try to delete that file (just once)
3) if you got a success in 2) but the media reappears in Aves, check whether the media file still exists on storage
4) if the file is no longer on storage, is the media still displayed in Aves after a device reboot?

I've found some Android bug reports where people experienced discrepancies between storage and Media Store when deleting media on some particular devices with Android 10.

By the way, do you use a custom ROM?

**Comment by D3ZOXY** [comment]
> if the file is no longer on storage, is the media still displayed in Aves after a device reboot?
No.

> By the way, do you use a custom ROM?
No, I'm on stock ROM (with root).

**Comment by deckerst** [comment]
At the moment I have no idea why this happens on your device, but I don't want to give up just yet so... here's a couple of random questions to explore new ideas:
- how did you root your phone?
- do you use Xposed?
- do you run any background automation tool (like IFTTT)?

**Comment by D3ZOXY** [comment]
> how did you root your phone?

Magisk 23.

> do you use Xposed?

No.

> do you run any background automation tool (like IFTTT)?

No.

**Comment by D3ZOXY** [comment]
I accidentally enabled the parameter in the developer options «Disable permission monitoring» and this fixed the bug.
![Screenshot_2021-11-12-15-13-26-29](https://user-images.githubusercontent.com/47178587/141465706-07eeb821-4196-4e9f-8e19-5c8e9a147381.jpg)

**Comment by deckerst** [comment]
Despite my best googling efforts, it's unclear to me what this setting does. The "Permission Monitor", and this setting, seem to be part of Realme UI / ColorOS, not the original Android OS. I have no idea what Realme did to the permission system.

Android 10 is already ambiguous, because Google heavily modified storage access permissions but allowed to opt-out and keep using Android 9-style permissions. Aves does opt-out of this new permission system on Android 10, so you don't have to manually grant access like Android 11 users have to.

From your reports so far, it looks like Realme UI and its Permission Monitor do not behave like standard Android 10. Or at least, it is not correctly implementing access checks when the new permission system is opt-out.

By the way, you say the issue got fixed when you disabled permission monitoring, but are you sure it's not because you installed the newly released version of Aves, v1.5.6?

**Comment by D3ZOXY** [comment]
> By the way, you say the issue got fixed when you disabled permission monitoring, but are you sure it's not because you installed the newly released version of Aves, v1.5.6?

No, when I turned on the Perrmission monitoring again, the problem reappeared.

**Comment by deckerst** [comment]
Thanks for the feedback. With Android 11, you should have seen the directory access request as I mentioned before [here](https://github.com/deckerst/aves/issues/112#issuecomment-948346575), no?

**Comment by D3ZOXY** [comment]
Yes.
