### ISSUE TITLE
External storage vault

### ISSUE THREAD

**Issue by tsrenis** [deckerst/aves#1148]
**Is your feature request related to a problem? Please describe.**
I'm frustrated by vaults being limited to internal storage. Internal storage is inherently limited in a way expandable storage like SD cards aren't.

**Describe the solution you'd like**
A solution would likely be allowing the users a choice where vaults are located

**Describe alternatives you've considered**
Another potential solution is making it so users are able to grant Aves access to all files so that we're no longer limited by the nature of using media store (I.E. Being unable to access hidden folders with .nomedia files or folders starting with ".")

**Additional context**
This is basically the only good gallery application that allows for tagging, which is why it's a shame this isn't a feature. It doesn't seem incredibly out of scope, given that the alternative is something simple/fossify gallery allows.

**Comment by deckerst** [comment]
Currently, Aves leverages the encryption of the internal storage (not only internal in the sense that it is the phone storage, but internal because you can't browse to it as a user unless rooted).

Having vaults on the SD card means Aves would be responsible for the encryption (and the encryption key). Also, the lifecycle of the vaults would no longer be tied to Aves, because you could remove the SD card and transfer the vaults without Aves knowledge.

So, in my opinion a bad idea, with risk of data loss for little reason. If users need a lot of space for vaults, they may need another app anyway. 

> Another potential solution is making it so users are able to grant Aves access to all files so that we're no longer limited by the nature of using media store

This is unrelated. As I said, vaults are in the internal storage (real internal) where the app has full file access on the folders and files it creates.
