### ISSUE TITLE
Different video thumbnails in the collection and viewer

### ISSUE THREAD

**Issue by D3ZOXY** [deckerst/aves#115]
**Describe the bug**
There are different thumbnails in the collection and in the viewer.

**To Reproduce**
1. See what the thumbnail of a video looks like in the collection.
2. Open the video and watch the thumbnail in the viewer.

**Expected behavior**
The video will have the same thumbnail in the collection and in the viewer.

**Screenshots**
[Video](https://radikal.ru/video/jk8TgOw3nPw).

**System information and logs:**
Aves version: 1.5.4 (Build 2058)
Flutter version: 2.5.3 (Channel stable)
Android version: 10 (SDK 29)
Device: realme RMX1991
Google Play services: ready

**Comment by deckerst** [comment]
I was loading video thumbnails in a progressive way:
- first, low quality thumbnails that can be loaded quickly but on which I have no control,
- second, higher quality thumbnails derived from the video at a chosen timestamp.

To make it seamless, I was trying to pick a time for the higher quality thumbnail that matched the one used for the lower quality one. It turns out it's inconsistent across devices so I can't provide a seamless experience for everybody :/

In the end I decided to ditch the lower quality thumbnails. It may take a little longer to get thumbnails, but they'll be consistent, and I can pick whatever timestamp for them.

As I changed the video timestamp from which thumbnails are extracted, the thumbnails in Aves v1.5.5 will not match the ones in Aves v1.5.4. You can clear the app cache to remove inconsistencies.
