### ISSUE TITLE
Display album path at album view

### ISSUE THREAD

**Issue by herrbrixter** [deckerst/aves#1166]
**Is your feature request related to a problem? Please describe.**
The album path is important especially if you want to work with file manager apps.

It's not intuitive to get the album path currently because you have to go inside the album, open a file then view the file's information. You shouldn't have to go to the file level level because album path is at the folder level.

**Describe the solution you'd like**
Select 1 album. The 3 dot menu on the upper right has a menu item like Info that says the album's path.

Or, when you open an album, the abum's path is displayed on top.

**Describe alternatives you've considered**
You have to open a file inside an album to view the file's path.

**Additional context**
In other gallery apps, you can see the folder's path without opening a file inside the folder.

**Comment by herrbrixter** [comment]
F-stop gallery, Gallery Elite, Fossify Gallery displays the folder path without requiring you to open a file inside the folder.

**Comment by deckerst** [comment]
Is it for copy-pasting, or simply to know where it is?

I'm asking because I intended to add a "Show in Explorer" (where you suggested "Info" would be), which would bring you to the explorer, with the album path in the crumbs on top. So it would be in storage context, and more user-friendly than the raw path.

**Comment by herrbrixter** [comment]
Never mind. I see I can find the path from the explorer. Thank you!
