### ISSUE TITLE
.dcm file support

### ISSUE THREAD

**Issue by Aadam-Marshall** [deckerst/aves#1176]
Did an x-ray of my doggy's legs and needed to view the .dcm files on my phone. Had to download a separate app for that. Any plans to support DICOM images? 🐶

**Comment by deckerst** [comment]
Could you please provide a sample file?

**Comment by Aadam-Marshall** [comment]
Can't upload .dcm files here, GitHub doesn't support it. Here: https://send.vis.ee/download/e4d888474b6c7baf/#EqnYdF62meViz0gMube7rA

(It's an open source browser file sharing platform: https://github.com/timvisee/send)

**Comment by deckerst** [comment]
I was interested in this format, because it's an established standard in the medical world. Sadly, it is not simply an image format but allows much more (its MIME type is actually "application/dicom"), and the Android OS does not see it as media. Which means it's not accessible by gasket apps like Aves.
