### ISSUE TITLE
Unable to swipe to next image, depending on directory 

### ISSUE THREAD

**Issue by fbauer-kunbus** [deckerst/aves#1207]
**Describe the bug**
When I use Aves as image viewer by calling it with 'open with' from an app like Total Commander or X-plore in SOME directories it happens, that thought the image is shown in the Aves viewer, I then cannot swipe to the next or previous image in same directory. 
BUT in other directories with images, this works without a problem. 
I could not find any rule for this yet. 

**To Reproduce**
1. Open any Explorer app on Android like x-plore 
2. Navigate into a directory with images 
3. Call 'open with'... AVES for any image 
4. Image is shown in Aves, try to swipe left or right to next image. 
5. If 4. worked, try it with a couple of different directories. Not all should work! 

**Expected behavior**
All directories with images should be swipeable

**Comment by deckerst** [comment]
I think I know why, but I'll need you to confirm.

- Case 1: your explorer app shares a media file in a public directory, with the media public URI. In that case Aves can get the media details, including its path, and list the other media in its directory, so you can swipe.
- Case 2: your explorer app shares a media file in a private/hidden directory, with a custom content URI served by the explorer app. In that case Aves has no contextual details about the file. And even if it did, it would not be able to list the others file because the directory does not contain public media files.

When you share a media file with Aves, you can go to its `Info` page (swipe up) and see its URI. If it's something like `content://media/external/images/media/{some number}`, it's public media. Otherwise it's not.
