### ISSUE TITLE
Moving creates non-existing duplicate 

### ISSUE THREAD

**Issue by Donkey-Doug** [deckerst/aves#124]
This problem seems similar to https://github.com/deckerst/aves/issues/107.

When moving an image in Aves to a different album, the original location still has the images. However, clicking om the thumbnail shows a black screen with "the file no longer exists" message.

Aves version: 1.5.5-play (Build 59)
Flutter version: 2.5.3 (Channel stable)
Android version: 10 (SDK 29)
Android build: lineage_raphael-userdebug 10 QQ3A.200705.002 eng.abhish.20200710.065119 test-keys
Device: Xiaomi Mi 9T Pro
Google Play services: not available

[aves-logs-20211110_232157.txt](https://github.com/deckerst/aves/files/7516298/aves-logs-20211110_232157.txt)

**Comment by deckerst** [comment]
You're right, and I think it's related with #112 too.

I tried a first solution that was working fine when I was testing it on the Android 10 emulator, but evidently it doesn't fix it in practice. I'll try something else!

**Comment by Donkey-Doug** [comment]
The latest debug version seems to have fixed this. 

However, I did save the logs of the debug version to see if there really are zero problems. The log contains many errors. But to be clear, I am not experiencing duplicates on moving anymore.

[aves-logs-20211111_124302.txt](https://github.com/deckerst/aves/files/7520134/aves-logs-20211111_124302.txt)

**Comment by deckerst** [comment]
Glad to hear this! This new approach doesn't seem to solve #112 but I think it's still an improvement and I will release this fix soon.

Thanks for taking the time to attach logs, it's much appreciated.

The logged errors are not actual problems:
- `getEmbeddedPicture` fails when Aves retrieves video thumbnails. Some videos have a dedicated cover picture, some don't. There is no way to check and retrieve it without this error log. It's benign and can be ignored.
- `FileNotFoundException` happens when the Android Media Store thinks there is still a media file, but there's no longer a file on storage, so trying to open that file (for a thumbnail, the viewer or info page) will show this error. Ideally, Aves (and other apps) should remove files in a clean way from the Android Media Store, but sometimes these ghost media files persist.
