### ISSUE TITLE
Existing albums can be recreated

### ISSUE THREAD

**Issue by An-anonymous-coder** [deckerst/aves#1272]
**Describe the bug**
When creating a new album, it is possible to create an album with the same name as an existing album. This doesn't do anything but make it seem like that existing album was just created. There is important additional context about this issue. 

**To Reproduce**
1. Open Aves
2. Go to the "Albums" tab
3. Tap the three dots on the top right
4. Tap "Create album"
5. Enter the name of an already existing album (e.g. "Sunsets")
It will say "Directory already exists", but it will still allow you to press "CREATE" to create the album.
6. Tap "CREATE"
A banner will appear at the bottom of the screen that says "Done!"
8. Tap "SHOW" on the banner that says "Done!"
The already existing album will now have the "NEW" tag displayed on the corner

**Expected behavior**
The app should not allow you to create an already existing album

**System information and logs:**
```
Package: deckers.thibault.aves
Installer: dev.imranr.obtainium
Aves version: 1.11.17-izzy, build 13602
Flutter: stable 3.24.4
Android version: 15, API 35
Android build: 2024102400
Device: Google Pixel 8
Support: dynamic colors=true, geocoder=false, HDR=true
Mobile services: not available
Connectivity: none
System locales: en_US
Storage volumes: /storage/emulated/0/
Storage grants: /storage/emulated/0/Movies/, /storage/emulated/0/Pictures/, /storage/emulated/0/DCIM/
Error reporting: false
```

I can provide logs if requested

**Additional context**

This bug is due to the fix of https://github.com/deckerst/aves/issues/1248 which would create "phantom" albums and wouldn't let you create an album with the same name as any of those. The phantom albums are still present in this update, because when I type the name of one of the previously created phantom albums, it will display the "Directory already exists" message. New phantom albums cannot be created in this update.

**Comment by deckerst** [comment]
> when I type the name of one of the previously created phantom albums, it will display the "Directory already exists" message. 

The message is still there for information, but you should be able to create the album anyway (the button is enabled).

**Comment by deckerst** [comment]
"Phantom album" is not a concept. Please be more precise for me to understand. 

When you do whatever you do: 
- do you expect to see a folder on storage? 
- is there a folder on storage? 
- do you expect to see an album in Aves?
- is there an album in Aves?

**Comment by deckerst** [comment]
I appreciate your suggestions to clarify "Album already exists" v. "Directory already exists", and will likely implement something like this (i may switch the "CREATE" button to "SHOW" when the album exist, not sure yet).

As for the internals, it doesn't exactly work as you think. Albums are an emergent property of your collection. There is not a list of "Aves albums". Rather, albums are derived from the directories of media files in your collection. That's why Aves generally does not show empty albums. The exception to this is allowing users to create a new empty album, to which they can move media files. The new empty album is only visible in that session, as it will disappear if no media is moved to it. On album creation, the directory is not created yet. The directory is only created when necessary, when files are moved to it.

Deleting empty directories is a delicate matter, because Aves is not a general purpose file manager. It's a gallery app, so it has a limited view of what's on storage.

In any case, thanks for following up and clarifying your initial issue. It's appreciated.
