### ISSUE TITLE
Can't view videos only within certain folder/collection

### ISSUE THREAD

**Issue by MomentofClarity** [deckerst/aves#1276]
**Is your feature request related to a problem? Please describe.**

I want to view videos from my camera folder.  Yet no matter what section/folder in I'm in, hitting video icon at bottom gets rid of the "Camera" filter and replaces it with videos that are anywhere on the phone. If I try going the "Camera" from that page, the video filter is removed. 

**Describe the solution you'd like**

If you are in a certain folder or collection and hit the video icon at bottom, it should show the videos within that section (so, add the Video filter to the "Camera" one). 

**Describe alternatives you've considered**

There is no way to view videos only from a certain folder/collection, I tried everything. 

**Additional context**

After typing this out may actually be a bug, not sure but doesn't make sense to be intended behavior as you could just go to "All" and then hit video button if you wanted to see every video on phone
![Screenshot_20241104_151905_Aves](https://github.com/user-attachments/assets/422370a0-c8ed-4d43-81e9-15dfb11c6ef3)
![Screenshot_20241104_151939_Aves](https://github.com/user-attachments/assets/cda6a2cb-edee-4428-bd06-0b7dfb527ead)

**Comment by deckerst** [comment]
For that kind of workflow, use the search page: you can combine all sorts of filters. You can just tap the title of most pages and it will bring the search page.

**Comment by MomentofClarity** [comment]
Thank you for explaining but I still think it's super counter intuitive, UI wise, for that button to kick you out of wherever you are instead of...not doing that. Because the first button is blue in the camera folder,  meaning its the active filter at ur current location. You would expect hitting one of the buttons on that bar would just apply that filter, not kick you out of Camera. 

If the gray bar at bottom is just intended to be a shortcut bar, then first icon shouldn't be blue (implying it's "active" view) when I'm in Camera,  because it's not showing everything on the phone.

(Not trying to argue just saying. Thanks for all your work on the app)

**Comment by deckerst** [comment]
I understand what you are saying. The issue is that different people have different intuitions. For example in that case, if I did it the way you expect, some users would complain that they can't shake off the filters when using the bottom bar, that they would have to manually remove the filters from the top after a switch.

As a concept, the bottom bar is a more compact and accessible drawer. For Aves I've decided that both the drawer and the bottom bar would be for root shortcuts (i.e. resetting whatever you were doing to a known state). Contrary to the Search, Info, Map and Stats pages, which combine filters.

> If the gray bar at bottom is just intended to be a shortcut bar, then first icon shouldn't be blue (implying it's "active" view) when I'm in Camera, because it's not showing everything on the phone.

True, I've tried this when I first implemented the bottom bar, for the exact reason you mention. The lack of feedback from the bottom bar itself was weird, and trying both ways I finally settled on what you see today.
