### ISSUE TITLE
Hide private folder

### ISSUE THREAD

**Issue by Donkey-Doug** [deckerst/aves#13]
Make it possible to hide folders for privacy reasons. One method of doing this is by adding a .nomedia file to the folder. This causes android to ignore the folder in all gallery apps. (The .nomedia file could be deleted manually by the user to unhide the folder in case there is a problem with the app/the app is uninstalled).

**Comment by deckerst** [comment]
Hiding content can be done (at least) in 3 ways:
1) encrypt and lock content behind a password
This would be the actual solution for privacy purpose, because no one else could access the content, even with access to the device. I might implement it some day, but it's not a priority.

2) adding a .nomedia file in the folder
This has the benefit of hiding content for all apps that rely on the Media Store, but the downside is that the user has to be tech savvy enough to revert the change, so Aves would need to explain what's happening in details. Also, anybody with access to the device can revert the change and see the content. Besides, some other gallery apps do not rely on the Media Store, therefore ignoring the .nomedia files altogether.

3) hiding content from the collection shown in the app
This is the solution I went for. It can be reverted from within the app and it can apply to any filter (not just folders, but you could for example hide a specific tag). In my opinion, this is just as effective as 2) for privacy against prying eyes (if they don't have control of the device).

**Comment by deckerst** [comment]
You can long press on a filter and select "hide". To show them again, you can toggle or remove the filters from `Settings` > `Privacy` > `Hidden items`.

![Screenshot_20240419_140901_Aves](https://github.com/deckerst/aves/assets/13898333/7ae0cfd6-4bd9-44b5-bcde-ba830431ed37)

**Comment by deckerst** [comment]
And to hide paths, you can do so from `Settings` > `Privacy` > `Hidden items` > `Hidden Paths`.

**Comment by NastyFlytrap** [comment]
> And to hide paths, you can do so from `Settings` > `Privacy` > `Hidden items` > `Hidden Paths`.

Ah, this is the kinda solution i was looking for. Thank you!

Damn. Those are some efficient responses. 
You run a tight ship. 
Respect.

**Comment by AdityaMH** [comment]
Use .nomedia still didn't work.

**Comment by NastyFlytrap** [comment]
> Adding .nomedia still didn't work.

Yea it didnt work for me either. I just gave up.
