### ISSUE TITLE
Accrescent Update

### ISSUE THREAD

**Issue by RITFW** [deckerst/aves#1351]
I've installed Aves Gallery Libre from Accrescent and noticed that the version available on Accrescent is still 1.11.19, although 1.11.20 has been available since December 11th. 

Is this just a temporary problem or should I switch to another source?

Thanks for the great app and all the hard work. I really appreciate it.

**Comment by deckerst** [comment]
I wanted to wait and check for potential bug reports before fully releasing v1.11.20 on all channels. As a matter of fact, I've since fixed a crash for low memory devices and there's a new locale, so I'll probably release a new version today or tomorrow and push it to all channels.

> Thanks for the great app and all the hard work. I really appreciate it.

Glad you enjoy it!

**Comment by deckerst** [comment]
Just released v1.12.0 on Accrescent, both `play` and `libre` flavours.

**Comment by RITFW** [comment]
Awesome! Thanks a million. 

And thank you for offering the libre flavor as well. 

Happy holidays.
