### ISSUE TITLE
l10n Multilingual Translation 翻译 Chinese Simplified Traditional 简繁体中文 Chinese 中国 zh-cn zh-hans 汉化

### ISSUE THREAD

**Issue by 57382** [deckerst/aves#137]
I'd like to contribute to the translation. Where can I find a translation template? 

https://github.com/deckerst/aves/blob/develop/pubspec.yaml
This is not a translation template.

I like this app. This is a great alternative to Google Photos. No annoying update pop-ups.

**Comment by deckerst** [comment]
Thanks for taking the time to look into it!

There are 2 reference files in English:
- the main big one at
https://raw.githubusercontent.com/deckerst/aves/develop/lib/l10n/app_en.arb
- and a tiny one at
https://raw.githubusercontent.com/deckerst/aves/develop/android/app/src/main/res/values/strings.xml

`app_en.arb` is filled with entries like:
```
"entryActionRotateCW": "Rotate clockwise",
"@entryActionRotateCW": {},
```

In that example:
- the words to translate are: "Rotate clockwise",
- "entryActionRotateCW" is the key (it gives some hint where and how it's used in the app, e.g. "...Tooltip", "...DialogTitle"),
- the line starting with "@" is useless, please ignore it.

Some entries have parameters, usually because of single/plural, like this:
```
"itemCount": "{count, plural, =1{1 item} other{{count} items}}",
"@itemCount": {
  "placeholders": {
    "count": {}
  }
},
```

If there is no single/plural variation in your language, just translate `other{...}` and remove `=1{...}`, like:
```
"itemCount": "{count, plural, other{{count} ...}}",
```

If you feel comfortable around programming tools, I could explain a way for you to see in real time in the app the translation you're creating. But otherwise, you could [send me by email](mailto:gallery.aves@gmail.com) a partially translated file, and I would give you a special build of the app where you can select Chinese Simplified or Chinese Traditional and see how it's integrated.

**Comment by deckerst** [comment]
I'll close this issue as this is not actionable. If you ever get to translate it, you can always send the result by email or open a PR.
