### ISSUE TITLE
Can't grant access to all files

### ISSUE THREAD

**Issue by errr-maxx** [deckerst/aves#139]
**Describe the bug**
Can't grant access to `Internal memory` root (or grant `MANAGE_EXTERNAL_STORAGE` permission) to app
So when I delete images I must grant access to folders containing them

**To Reproduce**
1. Select any image that is NOT in the `Internal memory` root (or any other Android-protected folder)
2. Press 'Delete' button
3. Dialog show up to grant access to 'xxx' folder of 'parent of xxx' folder, press OK
4. See error like on the screenshot

**Expected behavior**
I can grant access to `Internal memory` root (or grant `MANAGE_EXTERNAL_STORAGE` permission) and delete any images without requiring to grant access to all folders containing them

**Screenshots**
![Screenshot_2021-12-02-18-24-55-16_5734e8eb49b4234b62f913f831715b0f](https://user-images.githubusercontent.com/30185766/144451578-1f333d83-deea-4104-80bc-423401b57991.jpg)

**System information and logs:**
Aves version: 1.5.7-play (Build 61)
Flutter version: 2.5.3 (Channel stable)
Android version: 11 (SDK 30)
Android build: RMX2155_11_C.13
Device: realme RMX2155
Google Play services: ready

**Additional context**
When I try to delete image that in `Internal memory` root (or any other Android-protected folder), appears Android dialog to delete it, and it deletes normally

**Comment by deckerst** [comment]
This is not a bug. The dialog that appears in your screenshot is provided by the OS. Apps can request write access to directories but the OS restricts on which directory this access can be granted. Accessing a volume root directory is no longer possible from Android 11.

Aves is not considered a file manager, as it only deals with media files, so it would not get the `MANAGE_EXTERNAL_STORAGE` permission according to the Google Play policy. More on this topic at #106.

In other words, the "expected behavior" you describe is, as far as I know, not possible on Android 11. But in practice, media files should be within a few standard directories, like `/DCIM/`, `/Pictures/`, `/Movies/`. So you can grant access a couple of times and be done.

To modify a file in the root directory, as you describe in "additional context", the app switches to a file-level access when it cannot work with directory-level access. But as you can see, this requires user interaction for each operation. More on this topic at #64.
