### ISSUE TITLE
Rename date editing options

### ISSUE THREAD

**Issue by Donkey-Doug** [deckerst/aves#141]
![Screenshot_20211212-044838_Aves](https://user-images.githubusercontent.com/50382414/145699481-9af6546c-071a-4d40-91e9-838689dddabe.png)

I suggest renaming:

- Set to Select custom
- Clear to ~~Current time~~ Remove

And add an option to select the current time.

**Comment by deckerst** [comment]
I intend to review this dialog, among other things to merge the `set` and `extract` operations, and I may review the wording then.

That said, "Clear to current time" is, strictly speaking, incorrect. "Clear" removes the date from the selected fields (like `Exif Digitized Date/Time`, or `GPS Date`), it's not setting them to the current date. It may appear so if you clear all the fields, because there would be no date left in the metadata, and Aves would default to the modified date of the file.

**Comment by Donkey-Doug** [comment]
Oh, I would then rename Clear to Delete date.
