### ISSUE TITLE
Option for non-persistent filters

### ISSUE THREAD

**Issue by Donkey-Doug** [deckerst/aves#142]
Currently when using multiple search queries, the queries stack. Make it possible to make the search requests non-persistent.

**Comment by deckerst** [comment]
If you need a non-persistent search query, isn't the "title filter" more fitting?

**Comment by Donkey-Doug** [comment]
Is there any way to set title filter as default search mode? I know need to type something random in the search field, press enter, select title filter from 3 dots menu, enter search query and delete the random thing I typed.

**Comment by deckerst** [comment]
I don't understand why you need the step "type something random in the search field". Can't you just toggle the title filter and bypass the search page altogether?

Also, the quick actions displayed next to the 3 dot menu are configurable, so you could put there the title filter toggle (next to the regular search, or instead of it, whatever you prefer). It's in Settings > Thumbnails > Quick actions.

**Comment by Donkey-Doug** [comment]
Ah, Thr location in settings is a little bit weird. Did not expect such a setting under "thumbnails"
