### ISSUE TITLE
Add image rating and/or favorite (heart) as tag.

### ISSUE THREAD

**Issue by JanWaldhorn** [deckerst/aves#143]
Thank you so much for this awesome app. I have been looking for something similar for a long time.

I use the app in combination with DigiKam on the PC and SyncThink for transfer.

In DigiKam I can assign ratings (1-5 stars) to individual images, which are stored in the XMP data, for example, as a rating. I would be very happy if I could also add or search for assigned stars on the smartphone.

The heart / favorites function in Aves does not seem to be stored in the meta data. At least the tag "Favourites" is not transmitted or stored in the metadata. This alone would be helpful.

![grafik](https://user-images.githubusercontent.com/57268762/146576022-04918851-b18f-4d97-adc4-7910a96c37ef.png)

**Comment by deckerst** [comment]
Thanks for the kind words!

About ratings, I intend to support reading, writing and searching. Beyond that, would the following be useful or bloated:
- a "by rating" sort and grouping options in the Collection page?
- an optional rating overlay on top of thumbnails?

About the favorites, you're right, it's purely internal to the app and it doesn't modify the files. The advantage is that it's allowed for any file formats (not just the few ones where XMP editing is supported). I don't intend to change this for now.

**Comment by JanWaldhorn** [comment]
I'm glad to hear that. I think both ideas are good and not bloated at all.

I can see why it makes sense to leave the favorites internal. Being able to optionally fill in/activate the heart on an existing "Favorites" tag would probably cause confusion, wouldn't it?

**Comment by deckerst** [comment]
In the next release you'll be able to see, search and change ratings.

Here are a few details, in case people are curious how things are handled...

There are non-standard and many redundant ways that a rating gets embedded:
- `XMP / xmp:Rating`: between 1 and 5 (0 being unrated, and -1 rejected), standard and used everywhere
- `XMP / MicrosoftPhoto:Rating`: MS came up with this rating in % (between 1 and 99, not 0 to 100)
- `XMP / acdsee:rating`: from ACDSee, redundant with `XMP / xmp:Rating`
- `Exif / Rating (0x4746)`: non standard tag from MS, redundant with `XMP / xmp:Rating`
- `Exif / RatingPercent (0x4749)`: non standard tag from MS, redundant with `XMP / MicrosoftPhoto:Rating`
- likely more, if other software reinvent the wheel like MS and ACDSee

For reading, Aves only reads `XMP / xmp:Rating` and `XMP / MicrosoftPhoto:Rating` (in that order).
For writing, Aves always writes `XMP / xmp:Rating`, and only updates `XMP / MicrosoftPhoto:Rating` if it was already there. Removing a rating will remove the fields, instead of writing a 0 rating.

According to specs, a rating of  "-1" means "rejected". I have no idea whether typical photo management software let users do that, but Aves will handle it for read/write.

**Comment by deckerst** [comment]
> Being able to optionally fill in/activate the heart on an existing "Favorites" tag would probably cause confusion, wouldn't it?

@JanWaldhorn Sorry, I missed your question. Yes, technically possible, but probably confusing. The simple "favorite" / heart is a typical light feature in mobile apps and I don't think it translates well to semantically strong things like ratings and tags.

Hopefully ratings and tags will be enough for you, but let me know if you encounter usability issues with these in Aves.

**Comment by JanWaldhorn** [comment]
All good, thanks for the quick implementation. The star function is enough for me.

**Comment by deckerst** [comment]
@JanWaldhorn I forgot to mention that Aves needs to rescan photos to see their ratings, if they were already scanned in a previous version. New items will be fine.

To rescan, you can select photos on the Collection page, and select `Rescan` in the top right corner menu. You can select all of them at once, too.
