### ISSUE TITLE
Font consistency

### ISSUE THREAD

**Issue by Donkey-Doug** [deckerst/aves#15]
Use the same font throughout the app. At the moment, the font in the hamburger menu is different from the font in the headers and timestamps.

I personally find the font in the hamburger menu to be more pleasant. I suggest using that font everywhere.

**Comment by deckerst** [comment]
I removed the custom font, so the same font is used throughout the app (albeit with some variation of weight, small caps, etc).

The font used is Roboto, which is usually the default font on Android devices. On some devices, such as Samsung devices with One UI, users can change the default font used by all apps. I wanted to use that user preferred font in Aves, but it seems currently impossible because of a [limitation](https://github.com/flutter/flutter/issues/48381) in Flutter, the framework that Aves uses.

**Comment by lalalasupa0** [comment]
> I removed the custom font, so the same font is used throughout the app (albeit with some variation of weight, small caps, etc).
> 
> The font used is Roboto, which is usually the default font on Android devices. On some devices, such as Samsung devices with One UI, users can change the default font used by all apps. I wanted to use that user preferred font in Aves, but it seems currently impossible because of a [limitation](https://github.com/flutter/flutter/issues/48381) in Flutter, the framework that Aves uses.

Hey, is there a way to use the system's text font in texts like "Collection"? I don't like the default, that's why I ask

**Comment by deckerst** [comment]
Nope. The framework limitation is still there.
