### ISSUE TITLE
Different location for refresh button

### ISSUE THREAD

**Issue by Ingegneus** [deckerst/aves#162]
Right now it is only possible (as far as I can tell) to access the refresh button by long pressing on an image->3 dots->refresh. I think it would make much more sense to put that button either in the 3 dot menu on the home screen or In the settings or in the side pane.

**Comment by deckerst** [comment]
I assume you're talking about the action which is called in the English version "Rescan".

You're right: this action is only available where you saw it.

I added this action only because new versions of Aves sometimes introduce a feature that relies on metadata extraction, and it's necessary to rescan the collection to benefit from the feature. For example, when introducing ratings, users needed to rescan items to see the existing ratings of these items.

With that usage in mind, the current location makes sense: rescanning in bulk, and allowing to target specific parts of the collection (for example, only the videos).

I believe that what you're suggesting would force the rescan of the whole collection, and I want to avoid this. Am I missing something?

**Comment by Ingegneus** [comment]
yes i was talking abou the rescan.
i understand the reasoning now thank you. it makes perfect sense. I would still ike to have a button to force a refresh of all files (located in the settings maybe)

**Comment by deckerst** [comment]
Added to the Collection page (not the Settings page) so it's in the same place whether browsing or selecting items.

It applies to the currently visible collection (just like the shortcut, map and statistics actions), so if you want to refresh everything, just go to "All collection" and rescan.
