### ISSUE TITLE
[Gray screen] Read-only storage volume

### ISSUE THREAD

**Issue by Makigo123** [deckerst/aves#167]
After accepting terms and given the app permissions, just ending in a gray screen, nothing happens.
I've tried to let the app as i thought it could be a long load time before displaying the pictures, but didn't work at all.

![Screenshot_20220127-131940120 (1)](https://user-images.githubusercontent.com/98529789/151358785-f041aead-ed29-43c9-8a01-3455c7c1da1a.jpg)

I'm on Pocophone F1 using crDroid 7.14 (Android 11).

**Comment by deckerst** [comment]
Oh, very interesting. I didn't know SD cards could be read-only...

But maybe the gray screen is for another reason, cf #158. Here's a temporary build of Aves, including the fix for that issue:
https://drive.google.com/file/d/1904aLulX5ghgqdgxP1tuth5E2WWTcsP-/view?usp=sharing

Could you try this build and let me know if it works for you?

**Comment by Makigo123** [comment]
> Oh, very interesting. I didn't know SD cards could be read-only...
> 
> But maybe the gray screen is for another reason, cf #158. Here's a temporary build of Aves, including the fix for that issue: https://drive.google.com/file/d/1904aLulX5ghgqdgxP1tuth5E2WWTcsP-/view?usp=sharing
> 
> Could you try this build and let me know if it works for you?

Expired link :/

Edited the original post with a bunch of informations

**Comment by deckerst** [comment]
Thanks for the additional details.

Here's the correct link: https://drive.google.com/file/d/1pvFPImEzXfN8rqnSuh0uh_B5QAJBU6gO/view?usp=drivesdk

**Comment by Makigo123** [comment]
Same problems and errors with that temporary build. Definitly my sd card that got into read-only but yep unable to access any functionality of the app as long as i have a read-only sd card. Works fine otherwise.

**Comment by deckerst** [comment]
Thanks for the feedback.

As far as I understand, while regular sized SD cards have a write protection switch on the side, there is no such switch on micro SD cards. So when Android detects a micro SD card as read-only, it's an issue with the volume format (or driver, firmware, etc.)

I can't simulate this storage volume state, so it won't be obvious to test a fix but I'll see what I can do.

At least it's a rare case and it can be fixed by fixing the SD card itself.

**Comment by deckerst** [comment]
The last release of Aves includes a few fixes to try and protect the app from faulty SD cards, but I cannot say whether they are effective to prevent the gray screen.

The real issue is that a faulty SD card makes Android go nuts. The app cannot get the list of storage volumes, which is essential for permission and file management. So anything like moving files, creating albums, etc. would fail anyway.

I'll close this issue, because I don't think I can do much more to overcome Android failure in that situation.

**Comment by deckerst** [comment]
Another report with the same cause:
```
Device: Samsung Galaxy A71
Device language: Portuguese
App version code: 67
App version name: 1.6.1
Android version: Android 11 (SDK 30)
```

<img src="https://user-images.githubusercontent.com/13898333/157144994-74e31885-efd7-4a6d-b16d-8a04c99f8e02.jpg" width="200">
