### ISSUE TITLE
Export VS move

### ISSUE THREAD

**Issue by Donkey-Doug** [deckerst/aves#168]
What exactly is the difference between exporting and moving an image? Can the options be merged?

**Comment by deckerst** [comment]
> What exactly is the difference between exporting and moving an image?

"Move" acts on a file. It is independent of content and format. It is lossless, as the content itself is not modified. It only modifies its location on storage.

"Export" acts on content. It creates a new image from the decoded image, so it is lossy (image and/or metadata). It only works with formats that Aves can decode. Because it allows changing the format, you can for example convert a HEIC to JPEG, or extract a multi-page TIFF to a collection of PNGs, or rasterize a SVG. Recently, I added a size option which was necessary for SVG export, but it could also be used to shrink images.

Another thing "Export" can do that "Move" cannot, is work on images that are not backed by a file on storage (it's uncommon, but a possibility on Android because images may be shared via content providers, without a file path).

By the way, as I work on #155, "export" will likely take another name ("save as", "transform", "convert"...)

> Can the options be merged?

"Move" is a time-honored action that all users understand, and I will not change its meaning, or add an intermediate dialog with export options.

"Export" could provide a toggle like "delete original", which would effectively merge the two actions as an "exported move". But I'm not a fan, because it's error-prone and could lead to unexpected loss if users do not fully understand the implications of converting images.

Do you have a use case in mind for asking this?

**Comment by Donkey-Doug** [comment]
No use case. I still believe there are too many options in the 3 dots menu.

![Screenshot_20220131-230629_Aves](https://user-images.githubusercontent.com/50382414/151880948-d2b52147-277d-44b3-9998-59a823078813.png)
