### ISSUE TITLE
Add Batch Rename using EXIF data, eg rename filename based on EXIF created date

### ISSUE THREAD

**Issue by petazonk** [deckerst/aves#183]
Allow selected photos to be renamed based on an EXIF tag like the created date. Ideally it would work off a template where you could could get the filename to be something like YYYY-MM-DD_HH:MI:SS.jpg. The template date should remain in the history so you can easily select it again in the future.

After selecting the photos that you want to rename, From the drop down menu, you select Rename > Using ExifCreatedDtm (or whatever it is called). As a bonus there should also be an undo option in case you do it incorrectly.

**Comment by deckerst** [comment]
* Fields
Do you actually need to target specific EXIF fields, or having the notion of "date" (as it is presented in Aves) enough?

* Format
I want a format allowing prefixing, suffixing, and being extended in the future (to insert other fields or counters if needs be), but without being to geeky with full regular expressions (or a thousand buttons for each need). I'm thinking of something like this:
"Honeymoon - {date:YYYY-MM-DD_hh:mm:ss} * - original"
The `*` would represent the current name, allowing prefixing/suffixing. E.g.
`IMG_1234.jpg` -> `Honeymoon - 2022-03-07_17:30:42 IMG_1234 - original.jpg`
If you left it out, like "Honeymoon - {date:YYYY-MM-DD_HH:MI:SS} - original", it would replace the name completely. E.g.
`IMG_1234.jpg` -> `Honeymoon - 2022-03-07_17:30:42 - original.jpg`

* History
Not sure about maintaining a multiple entry history for this, but I would store and reload the last format used at least.

* Undo
After you rename items, I think the "undo" action would not be useful if it's available for a few seconds in a snackbar, because you wouldn't realize that the new names are wrong in that short time. And I don't want to present a permanent banner to undo either. Instead, I believe that providing previews of modified names would be more helpful.

**Comment by petazonk** [comment]
The best date to use is the earliest date in the EXIF/XMP data as file
dates change as photos are moved around but EXIF dates shouldn't change. I
think the exif field is something like date digitised, date created or
something like that depending on the camera manufacturer.

Your preference for a date variable is exactly the same as mine, eg
date:YYYY-MM-DD_hh:mm:ss. I think it would be a great idea to have this as
a config setting where you can set it yourself. I name all my photos as
date:YYYY-MM-DD__hh.mm.ss  . So, for me to be able to set this in the
config and then when renaming the file the config could be expressed as
something like this:

"Honeymoon_<DATE>.".jpg

where the <DATE> format is pulled from the confiig setting and then it uses
the earliest date from EXIF/XMP. The earliest date being from the created
or digitised EXIF data usually.

Also, include an automatic sequence number when more than photo was taken
in that second, eg burst photos. Something like suffix of 001 at the end
but only if a duplicate is detected. If a duplicate is detected then pop up
a warning message or just add a suffix to the end of the filename.

No need for a history really if the <DATE> is set in the config settings.

Probably no need for Undo, but maybe show a preview of what the new file
name would be, eg, show one or two examples before the user presses the OK
button.

**Comment by deckerst** [comment]
@petazonk In Aves v1.6.3 you can rename multiple items at once.

For variable fields, I added the bare minimum:
- `date`, configurable using a template (see below)
- `name`, so you can prepend or append something to the current name
- `counter` (1,2,3...)

but I could add more (dimensions, tags?) so let me know what's needed in practice.

For the date template, you can use symbols as described in this table:
```
Symbol   Meaning                Presentation       Example
------   -------                ------------       -------
G        era designator         (Text)             AD
y        year                   (Number)           1996
M        month in year          (Text & Number)    July & 07
L        standalone month       (Text & Number)    July & 07
d        day in month           (Number)           10
c        standalone day         (Number)           10
h        hour in am/pm (1~12)   (Number)           12
H        hour in day (0~23)     (Number)           0
m        minute in hour         (Number)           30
s        second in minute       (Number)           55
S        fractional second      (Number)           978
E        day of week            (Text)             Tuesday
D        day in year            (Number)           189
a        am/pm marker           (Text)             PM
k        hour in day (1~24)     (Number)           24
K        hour in am/pm (0~11)   (Number)           0
Q        quarter                (Text)             Q3
'        escape for text        (Delimiter)        'Date='
''       single quote           (Literal)          'o''clock'
```

The number of times a letter is repeated matters. For example:
- `MMMM` gives "March"
- `MMM` "Mar"
- `MM` "03"
- `M` "3"

If you intend to use the fractional second part (e.g. `SSS` for milliseconds), you should rescan the collection first (prior to Aves v1.6.3, the subsecond part of dates was not saved properly).

And if the whole feature is difficult to use, let me know!
