### ISSUE TITLE
aves on Windows desktop

### ISSUE THREAD

**Issue by andrazznidar** [deckerst/aves#184]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I can't look at Motion Photos on my Windows computer.

**Describe the solution you'd like**
aves is released for Windows.

**Describe alternatives you've considered**
There exist command line tools to play Motion Photos, but are cumbersome to use.

**Additional context**
As of Flutter 2.10, Windows support is available on the stable channel.
https://docs.flutter.dev/desktop
https://medium.com/flutter/announcing-flutter-for-windows-6979d0d01fed

**Comment by deckerst** [comment]
I'm interested in this (and Linux too) but it is not trivial, even with Flutter desktop support.

About 20% of Aves is Android native code (not cross-platform Flutter code). This would need to be rewritten for each platform. On the plus side, all the code related to the crazy Android permission/file system would be simpler. But media monitoring, codecs and other Android goodies that came for free would need to be researched and implemented specifically for Windows. Also, the video player plugin I'm using has no desktop support.

Back to your need: I'm surprised mature software like XnView or IrfanView does not support motion photo. It would probably be faster to get motion photo support from them than getting desktop support from Aves.

**Comment by deckerst** [comment]
@andrazznidar I have a naive question: have you tried to install the app on Windows via [WSA](https://docs.microsoft.com/en-us/windows/android/wsa/)?

I don't have a Windows computer at hand so I can't try it myself. And I have no idea what kind of file system is exposed to Android apps installed this way. Does WSA mount Windows directories for Android consumption, or is it just an Android sandbox?

**Comment by STPKITT** [comment]
I'm a Linux user so I don't use Windows anymore, but I just read yesterday that Microsoft developed WSA much further, also in terms of desktop integration so that with the next big update (I don't know how Microsoft calls those these days) Windows 11 will have WSA for everybody (I guess, not sure about W11 licensing model) while until now it's been a beta preview in the Windows Insider branch. So if that works well I think developing Aves for a proprietary platform like Windows is a waste of time.

**Comment by protist** [comment]
> I'm interested in this (and Linux too)

I've love to see this on Linux as well. As far as I can see, there are currently no viewers for motion photos on Linux. There are a few options to extract the video part, but no integrated solution to view motion photos or select frames.

**Comment by kha84** [comment]
Have you tried Digikam? I think for desktop usage there's a plenty of opensource options. 

But when it comes to mobile, the number of really great apps is just limited by few fingers, and Aves is the best out of all of them, including wast majority of proprietary ones.

So I really keen to see dear sir @deckest to not spread his efforts by trying to support many playforms at once, but rather stay focused on improving existing product, which is great.

**Comment by protist** [comment]
@kha84 I just tested Digikam on your suggestion. Unfortunately it does not appear to recognise the image as a motion photo. I think the backend may well be the same as Gwenview, which also does not work. (Digikam also seems quite bloated to me compared to Aves!) Are there really plenty of FOSS options? I tried a few and could not find a single one that worked with motion photos. Did you have anything specific in mind in your comment?

Having said that, I agree that porting this to Linux may well be beyond the scope of the project. I imagine it would be quite a difficult process. However, my +1 was mainly in response to @deckerst mentioning that he was at least interested in supporting Linux.

**Comment by kha84** [comment]
Hey @protist,

>  quite bloated
It's called "feature rich" :)

I was reading this one https://bugs.kde.org/show_bug.cgi?id=385726 and as per latest comment there it appears that some support was added recently in march / april. Might worth to ensure you took the latest version of DK, because usually the distributed versions are based on stable releases and might be bit behind the bleeding edge of new features from master. Also feel free to update that Bugzilla ticket of KDE project - KDE dev guys are super responsive.

Speaking of other FOSS alternatives have a look here - https://wiki.archlinux.org/title/List_of_applications/Multimedia#Image

No, I didn't have any specific on my mind, I just know it there's a lot of existing foss desktop grade software, and usually there should be something to do the job

**Comment by protist** [comment]
> It's called "feature rich" :)

🤣 Fair call!

> Might worth to ensure you took the latest version of DK

I tested the latest stable, but TBH it's a bit too... um... feature rich for my liking anyway.

> I just know there's a lot of existing desktop grade foss software, and usually there should be something to do the job

You are probably correct, but there are a lot to test! I tested about half a dozen of the "main" ones, and couldn't find one that worked.

**Comment by kha84** [comment]
I hear you, my friend. I've been doing pretty much the same over last couple of days - https://orange-pi-4-lts.blogspot.com/2022/09/building-up-google-photos-replacement.html

Basically there's a DigiKam who can do everything, and there're 3 or 4 media organizers which are "almost there", but not exactly there yet. Depending on what exactly you need.

**Comment by kha84** [comment]
> @andrazznidar I have a naive question: have you tried to install the app on Windows via [WSA](https://docs.microsoft.com/en-us/windows/android/wsa/)?
> 
> I don't have a Windows computer at hand so I can't try it myself. And I have no idea what kind of file system is exposed to Android apps installed this way. Does WSA mount Windows directories for Android consumption, or is it just an Android sandbox?

Btw, i do have couple of boxes with win 10/11. Sorry I entirely missed this your hint. Will give it a try tomorrow with WSA and report you back on how it goes.

**Comment by kha84** [comment]
I finally managed to install & configure WSA on Windows 11 machine and install Amazon AppStore there.
The thing is - I can't find Aves Gallery application in there. 
My guess they're filtering in only apps which can be scaled for tablets

**Comment by deckerst** [comment]
@kha84 I missed your comments. Thanks for testing WSA. The [app is on the Amazon AppStore](https://www.amazon.com/dp/B09XQHQQ72) so I'm curious about the criteria for WSA. The app is not specifically made for tablets but it works fine of those. Please let me know if you figure out the reason for Aves being filtered out.

**Comment by kha84** [comment]
I know **it is** on the Amazon store, because I've been following your URLs from the project mainpage - and I've seen it's there, when I went there with my web browser :) it's just not being available for me to "order it", for some reason. And Amazon is not giving any kind of explanations why. As I said, I first thought it might be some territorial restrictions for my account, so I created a new account on Amazon, which had a US phone number and US as a country. But that didn't work as well. What I haven't tried yet, is to reach their support for any clarifications. I can give it a try, sure. But need to say, my expectations for support being able to fix that are already low :)

**Comment by deckerst** [comment]
@kha84 just for your info, Aves is now available via WSA. I didn't test it myself but I've been told that the file system on WSA does not mount Windows volumes. It's just like a VM, so not very useful with Aves at the moment.

**Comment by kha84** [comment]
Thanks for the update. 
I think on desktop we do have number of options, like DigiKam who were promissing to fix some of the critical bugs in the upcomming version 8. These bugs were preventing users to update EXIF metadata on mp4 video files. That was the only big pending thing on my list, for proper media archive management on desktop. And I'm super excited to see it was already handled properly in AVES - amazing job.
