### ISSUE TITLE
Moving feature

### ISSUE THREAD

**Issue by user-2022** [deckerst/aves#205]
Hello. When a user moves or copies a file, its creation/modification date changes. As a result, we get a new, newly created file (a copy of the old one) at the final address. This is inconvenient when I want all files to go in chronological order, and old files are displayed as old even after moving...
Please fix the move feature so that it works not like copying the file and deleting its old version, but like moving it without changing its creation date.
And make sure that sorting is available by "creation date" and "last modified".
Thank you!

**Comment by deckerst** [comment]
The issue, and limitations, of the modification date is discussed in https://github.com/deckerst/aves/issues/111.

Basically, with modern permission systems it's out of reach. That's one of the reasons I think the modification date is not a valuable field, and Aves uses the reliable metadata date instead.

You can edit images to give them a metadata date, so that you do not depend on flimsy file properties.
