### ISSUE TITLE
Cache takes a lot of space

### ISSUE THREAD

**Issue by Ingegneus** [deckerst/aves#206]
Sometimes (I wasn't able to pinpoint the trigger yet) aves takes up a lot of storage ~8GB. A large part is cache that I can just remove, but some 2GB are just for data. What is included in this big chunk of memory?

**Comment by deckerst** [comment]
Could it be from the items in the recycle bin?

**Comment by Ingegneus** [comment]
Yess indeed its the recycle bin. why does it generate so much cache though?

**Comment by n-berenice** [comment]
> Yess indeed its the recycle bin. why does it generate so much cache though?

Thumbnails maybe? I have over 5k image and webm files and my cache is about 2GB.

**Comment by deckerst** [comment]
> why does it generate so much cache though?

The cache is populated by processed images (thumbnails, video previews, tiles for large images, etc.) By default it's never emptied. I thought Android was automatically trimming it when the device got low on storage.

In any case, I'm surprised that the cache would reach that size. I should take a closer look, and probably put in place a more aggressive cache trimming strategy.

How's your collection in terms of format and quantity?
1) Do you have many motion photos, multipage TIFF, or HEIF image sequences?
2) Do you have many videos with cover images?
3) Do you have a lot of turnover, with many images added, removed, added, removed...?

**Comment by Ingegneus** [comment]
points 2. and 3. apply to my collection.

**Comment by k3n01** [comment]
An option to disable it altogether would be cool enough for me

**Comment by eternalbit** [comment]
For me the storage usage (both, data|internal and cache) is an issue as well. (#663 )

I have a not too small collection of > 7000 photos/videos (mostly on the external sd due to very limited internal storage) and I've had both cases, cache and data using up to 2.5 GB of internal storage after browsing/viewing photos for some time, at which point my internal storage is basically full.

It would be ideal for my use case if there was a setting so that the **only** media caching that Aves does would be for the small thumbnails in the scrolling view. Each of these has dimensions of < 180x180 pixels on my phone and thus would only use like 10 kB of space. A library of 30,000 media files would then only occupy ~ 300 MB of space, which would be absolutely fine.

(I'm not sure: aren't such small thumbnails cached already by the Android media scanner, so that Aves might not even need to cache them again?)

Would such a setting be a big deal to implement?

(The feature set of Aves with exif tagging, search and others is just awesome, but I can only use it if it keeps a low storage profile.)

**Comment by deckerst** [comment]
Thanks for the feedback.

Actually, there was a bug related to this : temporary files (created for various reasons, like media analysis, motion photo extraction, etc.) that were supposed to be deleted were left in the cache directory, forever. These files were not even "cache" in the sense that they would be reused. The fix is not released yet but these one-time use files should no longer stay in the cache folder.
