### ISSUE TITLE
No mathcing app found when tapping edit

### ISSUE THREAD

**Issue by francois072** [deckerst/aves#220]
![SmartSelect_20220409-195441_Aves](https://user-images.githubusercontent.com/64827815/162585860-cafdb8ba-eaba-4698-ad83-492e2bdd68d2.jpg)
I am using a Samsung A12.

**Comment by deckerst** [comment]
Is it wrong? Do you actually have an app on your device that can edit the item you were viewing?

For now Aves does not provide its own image or video editor. See issues #17 and #18.

Usually, devices already come with at least one default app that can be used as an image editor (but no video editor). As far as I know, it's the case for Samsung devices.

**Comment by francois072** [comment]
The only app that the phone came with to edit photos with was the Samsung Gallery app, but Aves doesn't open that

**Comment by deckerst** [comment]
Ok, so it should show at least this app to edit images. But videos are not editable by it.

If what you're trying to open is an image and it fails, please provide more details about the file. Any detail you can provide could be useful: type, uri, size, dimensions... You could screenshot what's displayed in the `Info` page.

Also, please follow the instructions in the app `About` > `Bug Report` section, and attach here the logs and system information.

**Comment by francois072** [comment]
[aves-logs-20220410_112737.txt](https://github.com/deckerst/aves/files/8458675/aves-logs-20220410_112737.txt)

Aves version: 1.6.3-play (Build 69)
Flutter version: 2.10.3 (Channel stable)
Android version: 11 (SDK 30)
Android build: RP1A.200720.012.A127FXXU4AUK1
Device: samsung SM-A127F
Google Play services: ready
System locales: en_US
Aves locale: system -> en

![SmartSelect_20220410-112639_Gallery](https://user-images.githubusercontent.com/64827815/162611776-1d38fb79-7dab-47ac-a3a0-d882517dfe05.jpg)

I also installed Sketchbook, Phimp.me and Epik, but none are shown as editing options.

**Comment by deckerst** [comment]
I took a closer look, and the short answer is: it's actually not a bug in Aves, and the solution for you is to use the "share" action instead of the "edit" action to open your image with these apps.

The long answer is that Android works with "intents". Apps can declare supporting an intent (for example Google Photos declares being able to edit a picture), and other apps can send intents to these supporting apps. The "edit" intent is standard and meaningful, but lots of apps do not declare supporting it. Sketchbook, Phimp.me, Epik are all apps that do not declare supporting this intent, so they are not listed when sending the "edit" intent. On the other hand, these apps usually support the "share" intent, so you can use that to send them a file. If these apps were good citizens in the Android ecosystem, they would declare what they support, like Google Photos and many other apps do, but instead they rely on the semantically weak "share" intent.

About the image editor bundled with the Samsung Gallery app, it seems the editor is only usable when launched from the gallery itself, as it's not even listed among the apps supporting the "share" intent either. I guess Samsung did this intentionally, to not make their editor available to non-Samsung apps.
