### ISSUE TITLE
Bottom navigation option

### ISSUE THREAD

**Issue by dude-shah** [deckerst/aves#222]
**Is your feature request related to a problem? Please describe.**

Can you add an option to show per date stuff something like that 

![IMG_20220410_120848.jpg](https://user-images.githubusercontent.com/63038690/162606722-106cf74f-1c5b-4f50-bf38-cbc9a3b6c451.jpg)

Also for the Search and Tabs UI, tabs on bottom look nice rather than swiper from left option, i think this way it will look way better and modern. Its just a suggestion for a change in UI, these are ideas are from my phone default gallery app.

![IMG_20220410_121149.jpg](https://user-images.githubusercontent.com/63038690/162606797-3a4f754f-6ce4-412d-a6f6-2534b7d0353f.jpg)

Fonts used for the Months should be Bold or Heavy Font Type

**Comment by Donkey-Doug** [comment]
Android 12 Material You screenshot:

![Screenshot_20220410-193049_Infinity](https://user-images.githubusercontent.com/50382414/162631891-2d6f0b10-086d-424a-91af-9ab8cdb4256a.png)

**Comment by deckerst** [comment]
@dude-shah 

> Can you add an option to show per date stuff something like that

Have you tried the different `group` options in the view settings? I think grouping by day is what you want.
<img src="https://user-images.githubusercontent.com/13898333/162649206-c0858540-394e-4144-afef-acb085bb9214.png" width="200"/><img src="https://user-images.githubusercontent.com/13898333/162649214-8e787ca4-64c5-4086-a9e9-4a78f9b97516.png" width="200"/>

> tabs on bottom look nice rather than swiper from left option

I guess you're talking about using bottom navigation instead of the side drawer, like in Samsung Gallery:
<img src="https://user-images.githubusercontent.com/13898333/162649336-207c5d44-a623-4ab4-ad0e-17a605813f7a.png" width="200"/>

I believe the drawer is a good fit for some users (especially those who use advanced features) and bottom navigation is a good fit for some others (those who basically just need to switch between the collection and the albums), so I intend to provide the choice.

> Fonts used for the Months should be Bold or Heavy Font Type

Are you saying this from an accessibility point of view? Do you toggle the "bold font" switch at the OS level and expect an effect in Aves?
Or are you saying this from your sense of aesthetics?

I'm interested in the former, not the latter.

@Donkey-Doug what do you expect me to understand from your screenshot? If it's not relevant to OP's requests, please create a separate issue, and be more explicit about your request.

**Comment by dude-shah** [comment]
> I guess you're talking about using bottom navigation instead of the side drawer, like in Samsung Gallery:

Yeah something like that.


> I believe the drawer is a good fit for some users (especially those who use advanced features) and bottom navigation is a good fit for some others (those who basically just need to switch between the collection and the albums), so I intend to provide the choice.

A choice between them for users would be better.
 
> > Fonts used for the Months should be Bold or Heavy Font Type

> Are you saying this from an accessibility point of view? Do you toggle the "bold font" switch at the OS level and expect an effect in Aves?
> Or are you saying this from your sense of aesthetics?

I'm suggesting a change like this, it makes more impact than the font used now.

![IMG_20220411_134826.jpg](https://user-images.githubusercontent.com/63038690/162700117-e7f5a04d-cb2c-4df9-824b-b672af946e73.jpg)

Also i noticed the app lacks basic edit option, like **crop**, doodle etc. For that one has to open the image in separate app, should i make a separate issue for this.

**Comment by deckerst** [comment]
> Also i noticed the app lacks basic edit option, like crop, doodle etc. For that one has to open the image in separate app, should i make a separate issue for this.

No need, there's already #17. You can show interest by upvoting it with a thumb-up reaction, and you can also subscribe to the issue to get updates.
