### ISSUE TITLE
[FR] Add Undo delete buttton to popup message

### ISSUE THREAD

**Issue by basings** [deckerst/aves#225]
When deleting an image, you need to go to the recycle bin in order to restore it. Sometimes you accidentaly delete an image or have second thoughts right when deleting it. It would be great if there was a button on the right side on the popup "moved 1 item" such that you can easily restore an image.

**Comment by deckerst** [comment]
I agree, there's an opportunity for a button here, but I was hesitating between "show" (to be consistent with other moving actions) and "undo" (because it is more traditional after "delete").

I'll probably go with "undo", as you suggest, but there's something to bear in mind. Because the file date is modified when moving it, the file date after "undo" will be different in the end. Not a big deal, but it will not, strictly speaking, restore the file to its original state. It will just move it back.

**Comment by basings** [comment]
If "undo" is not exactly reversing the action, people will complain and open issues, I guess. "Restore" or a simple "back button"(leftward facing (round) arrow? But it kinda means the same.

What's the implementation of the "clock symbol with arrow" in the recycle bin? Isn't
it basically restoring the image/undoing the deletion? It looks as if it would preserve the timestamps to me. Wouldn't it just be the action of that button specifically applied to the most recent deleted image(s) for the next x seconds?

**Comment by deckerst** [comment]
> What's the implementation of the "clock symbol with arrow" in the recycle bin?

This symbol is used for the "restore" action. This action moves the trashed file to its original directory. If a file with the same name is already there, the restored file name will be automatically renamed to avoid conflict. As far as I know, from Android 11, unless the app is a file manager or an OEM app, there is no way to move a file and preserve its "file modified date". Aves uses the "file modified date" only as fallback if there's no metadata date.

> Wouldn't it just be the action of that button specifically applied to the most recent deleted image(s) for the next x seconds?

Yes it would be. The only question is whether to call it "restore" or "undo" in the snack bar. I don't think it matters much, I'll see what's used by Google Photos and the like.
