### ISSUE TITLE
[FR] Prevent Rotation when zooming on map

### ISSUE THREAD

**Issue by basings** [deckerst/aves#229]
### Description

When zooming in or out of the map the map rotates. This is the case for both, when only one finger moves away from the other and when both fingers move into the opposite direction. You can't go straight with both fingers. 

This could be improved by fixing the orientation to north which would reduce functionality by notbeing able to rotate. Or by introducing a threshold before the map starts rotating, i.e. e.g. 5 degrees.

**Comment by deckerst** [comment]
Aves supports some Google Maps layers and some Leaflet layers (the OSM and Stamen ones), and these 2 kinds of layers use different engines.

I noticed the issue you describe only with the Leaflet layers, as the Google Maps rotation threshold works just fine, in my opinion. Could you confirm that you are only experiencing this on the Leaflet layers?

By the way, if your device does not have the Google Play Services installed, the Google Maps layers are hidden automatically.

**Comment by basings** [comment]
Yes, I checked it. It is only for osm maps. Google fixes the action, either rotation or zoom.

**Comment by basings** [comment]
To my understanding this can be closed since the the issue needs to be fixed in the leaflet library, right?

**Comment by deckerst** [comment]
I remember quickly checking but not investigating much when i noticed this a long time ago. It's possible i missed a parameter or an easy workaround. I'll keep this open for now so i remember to take another look.

**Comment by deckerst** [comment]
As suspected, there was a magic parameter. So this is fixed in the sense that it will either zoom or rotate, but the drawback is that the gesture triggers after a specific threshold, which may be too large for some, and too small for others.

Also, while we're on the topic of Leaflet layers, I'm already aware of a few bugs:
1) white line artifacts appear at specific zoom levels,
2) the zoom gesture zooms on the map center instead of the gesture focal point.
These bugs have recently been addressed in the library, but they haven't yet released an official stable version with the fixes.
