### ISSUE TITLE
Immersive mode 

### ISSUE THREAD

**Issue by Willbz5** [deckerst/aves#232]
Add option for semi and full immersive mode in settings.

Semi immersive means only hide status bar but keep navigation bar.

Full immersive means hide both .

**Comment by deckerst** [comment]
You forgot "please".

**Comment by Willbz5** [comment]
> You forgot "please".

???

**Comment by deckerst** [comment]
You could think about the tone of your writing. I doubt you give orders to people around you when you need a favor. There's no reason to be impolite just because it's the internet.

But you're not the only one. I should probably pin some notice with guidelines for people who forget themselves when they're online.
