### ISSUE TITLE
New icons style

### ISSUE THREAD

**Issue by iJahangard** [deckerst/aves#235]
The current icons seem to be inconsistent 
I know they called material design system icons but they are not so consistent as Google quantum icons which they're actually a better set of material icons

In my opinion your awesome application need a better iconset
So you may have two different choices:
1. Google quantum icons, that they are close sourced and you have to decompile google apps to extract those icons you want
2. Use another icon set like Microsoft fluent design icons they're accessable here
https://github.com/microsoft/fluentui-system-icons

**Comment by deckerst** [comment]
> The current icons seem to be inconsistent

Any specific example of inconsistency?

> Google quantum icons

Any reference, or documentation, regarding these "Google quantum icons"?

**Comment by iJahangard** [comment]
![Screenshot_20220426-015551_Aves](https://user-images.githubusercontent.com/67248292/165178057-c2614cb5-85c8-44f6-81e5-b703e073ea1c.png)
In this screenshot : 
Some elements are too thin or too big like screen rotate icon
Rename icon is weird to me idk
About edit button just look at what google used in **gallery go** app also rename icon

Delete button is too far from google quantum one 
The rotate screen icon is far away from what I've learnt from  material design 

These are what google uses: 
![Screenshot_20220426020250](https://user-images.githubusercontent.com/67248292/165178915-ea42b4dc-a2d9-4f85-91f2-cd515c20940b.jpg)
![Screenshot_20220426020259](https://user-images.githubusercontent.com/67248292/165178947-f7569921-a35a-4d85-ac81-aa8cd3edf7e1.jpg)
![Screenshot_20220426020404](https://user-images.githubusercontent.com/67248292/165179158-6fe811e8-f759-4ce3-b2a0-dcb8f0deb1c2.jpg)



And uh!!!!
There's no documentation or something about quantum icons , I decompiled some of google app and learned it practically

Anyway , I think you may consider to use Microsoft fluent design icons, they're gorgeous, consistent & free to use
So don't forget to use the high width icons they sound more beautiful and strong toe

**Comment by deckerst** [comment]
Thanks for the explanation. I see your point about the "Rotate screen" icon thickness, but for the rest I don't think it's important to match the icons of the latest Google products, especially if those icons are not from an available set.

In principle I'm not against changing the icon set, but there's a high bar. I'd need to replace [all the icons defined here](https://github.com/deckerst/aves/blob/develop/lib/theme/icons.dart) with a consistent set that is as user-friendly as possible to a typical Android user. That's more than a hundred icons, and there will be plenty more needed if I start working on the editor. [Material](https://fonts.google.com/icons?selected=Material+Icons) + [MDI](https://materialdesignicons.com/) are not perfect, but they're up to the task. I'm not so sure about Fluent.

As an exercise, I tried replacing the ones in your screenshot with Fluent icons:
<img width="250" src="https://user-images.githubusercontent.com/13898333/165198951-edd835a4-3f00-4606-8a35-98378fd9059f.png" />

I couldn't find a good one for the "Rotate screen" action. "Move" also didn't have an obvious icon, so I opted for a variation of the "Copy" one, which is not ideal (and I'm not even talking about the horizontal misalignment between the Copy/Move icons).

So, here is my suggestion: if *you* come up with a satisfactory replacement icon from Fluent for the whole set (100+ icons), I promise I'll take a serious look at it. Otherwise, I'll stick with the current one.
