### ISSUE TITLE
Allow option to have small Thumbnail overlay icons, eg "Show location icon"

### ISSUE THREAD

**Issue by petazonk** [deckerst/aves#240]
I really like the thumbnail overlay icons as I can quickly identify if a geotag or motion photo is in the current photo, however, I find them to be way to big which detracts from the image.

It would be great if their was an option to make them much smaller and for bonus points in the top right corner. Also it would be good to have the option to have them visible in full screen mode as well, eg when you are looking at the full photo.

Another alternative would be have a quick toggle button on the thumbnail view such that I could turn the overlay icon function on or off quickly while keeping the thumbnail view open.

**Comment by deckerst** [comment]
#68 déjà vu? ^^

You have a Pixel 6 Pro, right? How many thumbnails/columns do you have across the width of your screen in the Collection page?

Top right corner is already used for the selection overlay.

As for thumbnails in full screen, have you tried `Settings` > `Viewer` > `Overlay` > `Show thumbnails`?

**Comment by deckerst** [comment]
I *slightly* reduced the size of icons on the thumbnails (so that at least 5 can fit on one side).

> when you are looking at the full photo

@petazonk Could you let me know why you would like to see icons on the full photo? I'm asking because I think most of the icon info is already displayed in another way on the viewer overlay already:
- motion photo / multipage icon: in the viewer you see extra thumbnails for the extra content,
- location icon: the location appears in the top overlay,
- panorama icon: there's an "open panorama" button on the bottom,
- video duration: it appears in the bottom next to the track bar.

**Comment by petazonk** [comment]
You are correct in that it isn't essential, but, it is easier to notice the
location icon present as an overlay then it is to look up and read the
location text when in full view.

I still find the overlay icons overly large and also a little intrusive in
their white colour (which is good for maybe vision impaired). Would it be
at least possible to make the icons have a transparent background or the
option to have them another colour such as green or blue? I also prefer the
icons in the top RHS but I guess this is personal preference

**Comment by petazonk** [comment]
P6P, yes.
3 columns wide is what I normally use.

In regard to overlay, I mean the GPS icon that appears in the thumbnail
view, should be an option to appear in full photo view. I know the text
appears at the top of the screen.

I'm aware of the thumbnails view in the viewer.
