### ISSUE TITLE
[Bug] Trashing items modifies their date.

### ISSUE THREAD

**Issue by MajinSaaY** [deckerst/aves#244]
**Describe the bug**
Items restored from bin have their time modified to the current date.

**To Reproduce**
1. Open any image from any previous date
2. Delete it
3. Restore it
4. Check modified date

**Expected behavior**
Maintain the original date.

**Comment by deckerst** [comment]
The issue, and limitations, of the modification date is discussed in https://github.com/deckerst/aves/issues/111.

Basically, with modern permission systems it's out of reach. That's one of the reasons I think the modification date is not a valuable field, and Aves uses the reliable metadata date instead.

You can edit images to give them a metadata date, so that you do not depend on flimsy file properties.
