### ISSUE TITLE
Wrong emojis on country view

### ISSUE THREAD

**Issue by glemco** [deckerst/aves#247]
**Describe the bug**
If I go to the countries view, I see all countries my pictures are from, but instead of the flag, there's a weird set of Chinese (?) characters. See the screenshots, the only correct is FRA (which is in Paris and it isn't grouped with pictures in other cities in France).

**To Reproduce**
1. Go to 'Burger menu'
2. Click on 'Countries'
3. See error

**Expected behavior**
I would expect to see the emoji flags and all pictures from the same countries together.

**Screenshots**
![image2](https://user-images.githubusercontent.com/32201227/167433082-b7b67f16-4d1d-4387-bed0-0e20c71345b6.jpg)

**System information and logs:**
Aves version: 1.6.4-izzy (Build 1070)
Flutter version: 2.10.4 (Channel stable)
Android version: 12 (SDK 31)
Android build: aosp_lemonkebab-userdebug 12 SQ1D.220205.003 eng.androi.20220226.162719 test-keys
Device: OnePlus KB2003
Google Play services: ready
System locales: it_IT
Aves locale: system -> it
Installer: null
*(I can mail you the logs if relevant)*

Thanks in advance

**Comment by deckerst** [comment]
Nice bug, thanks for the report.

About the weird characters, it seems the geolocating service on your device returns addresses with country codes in lower case instead of upper case. I didn't expect it but it's easy to fix.

About "FRA" separated from other pictures taken in France, I understand the symptom but it is more subtle. Aves does not have a list of country names like "Francia" or "Germania". It relies on the addresses returned by the geolocating service on the device. And sometimes these addresses contain a country code ("FR" / "FRA") but not the country name ("Francia"). I'm surprised this happens for addresses in Paris, though. I thought it only happened for weird geopolitical cases (e.g. Svalbard, which technically belongs to Norway, but it's not really really Norway).

Do you use a custom ROM by any chance? Or custom Google Play services?

**Comment by deckerst** [comment]
When you open a picture from the "FRA" country, and then go to the picture `Info` page, do you see an address like this one?

<img src="https://user-images.githubusercontent.com/13898333/167523823-df3f75a6-12bc-4023-868f-d5509b3e6166.png" width="250"/>

**Comment by glemco** [comment]
Wow, quick diagnosis!
I indeed have microg as play services implementation (I guess the responsible of this would be Nominatim, then).
In the info I see the complete address (e.g. Francia, Grande Est, Wissembourg) for the ones with Chinese symbols, while just FRA for the others, I tagged them in the very same way through the app, I was even more precise in picking the spot inside the city.

I quickly tried the locations with [https://nominatim.openstreetmap.org/ui/reverse.html](this) but nothing looked out of place..

**Comment by deckerst** [comment]
The emoji flags are fixed, so I'll close this.

I'm not sure I can do anything further to help the geolocating service find the missing addresses. These services (including the one from Google) are not 100% reliable. They sometimes fail or return different results over time. It's also possible that it stopped returning addresses after too many requests in a short time. I don't know. I'll contact you if I ever get a bright idea to debug this.
