### ISSUE TITLE
Blank placeholder is displayed for images deleted/moved to a different location

### ISSUE THREAD

**Issue by xd003** [deckerst/aves#251]
**Describe the bug**
I moved some images to a different location & now aves is displaying a blank placeholder in its place saying - "The file no longer exists" . Shouldn't ideally these placeholders be removed if their corresponding images are not accessible . I can't even seem to delete them . Its just wasting the screen space

**Screenshots**
![Screenshot_20220515-072001652](https://user-images.githubusercontent.com/26503185/168453881-e595b9b1-d3ac-4fd2-b9b1-47431d5cb7d4.jpg)

**System information and logs:**
```
Aves version: 1.6.4-play (Build 70)
Flutter version: 2.10.4 (Channel stable)
Android version: 10 (SDK 29)
Android build: nad_kenzo-userdebug 10 QQ3A.200905.001 714 release-keys
Device: Xiaomi Redmi Note 3
Google Play services: ready
System locales: en_US
Aves locale: system -> en
Installer: com.android.vending
```

[aves-logs-20220515_171213.txt](https://github.com/deckerst/aves/files/8694841/aves-logs-20220515_171213.txt)

**Comment by deckerst** [comment]
Thanks for the report!

1. could you please attach the logs (you can save them from `About` > `Bug Report`)?
2. did you move these images with Aves, or with another app?
3. does this happen consistently all the time, or randomly sometimes?
4. do you use a custom ROM?

**Comment by xd003** [comment]
> Thanks for the report!
> 
> 1. could you please attach the logs (you can save them from `About` > `Bug Report`)?
Just attached it in the original post

> 2. did you move these images with Aves, or with another app?
I moved them using a file manager ( Mixplorer ) , just for additional info the behaviour is same if i delete them . For instance , i just deleted a image received on WhatsApp through the file manager and its still leaving those blank placeholders

> 3. does this happen consistently all the time, or randomly sometimes?
As of now , seems to be happen consistently

> 4. do you use a custom ROM?
Yes , Nusantara A10 based on AOSP

**Comment by deckerst** [comment]
Aves displays media as they are registered in the Media Store (a database maintained by the OS). When you see these placeholders, it means that the Media Store has entries for them, even though the actual files are no longer there.

Here, the issue is that Mixplorer and WhatsApp fail to manage media files in a clean way on your device, leaving obsolete entries in the Media Store. I'm not really surprised, given that your device uses a custom ROM with Android 10 (a bad version when it comes to media access & permission).

From my point of view, it's not a bug in Aves. One thing I could do, is make sure that you can delete/clean these obsolete entries from Aves. But ideally you should use better apps to manage your files, or switch to a different OS/ROM (Android 9 or 11, or official ROMs), otherwise you'll keep creating these obsolete entries in the Media Store.

**Comment by xd003** [comment]
@deckerst 
Thanks for the info . Its anyways rare that i delete some image through file manager not gallery ,  i guess just adding the ability to delete these obselete entries manually from Aves should be quite sufficient

**Comment by KoremuMekuro** [comment]
I'm using material files from zhanghai.I assume this is a problem with aves, cuz default aosp gallery hasn't such issue + if I clear aves user data then all the blank entries dissapears.And I can't delete about 20k(textures) blank entries cuz aves just hangs up in the proces.Even if I choose about 100 entries aves just hangs up.
