### ISSUE TITLE
Material you colors?

### ISSUE THREAD

**Issue by arun54321** [deckerst/aves#260]
Could you add material you colors on Android 12+?

**Comment by deckerst** [comment]
I have to look into it, but I'm not sure it will match expectations.

In Aves, colors are used basically in 3 ways:
1) the accent color (currently indigo), used for selected elements, and interactive elements like buttons, switches, etc.
2) neutral colors (from black to white, not tinted), used for generic text and background
3) highlights (various neon/pastel colors, if enabled), used to associate unique colors to filters, info sections, etc.

I don't want to give a tint to 2) because I think tinted texts and backgrounds would be jarring or weird next to images.
And the idea of 3) is that these generated colors are varied enough to help the brain find stuff faster without having to read the labels, so restricting these colors to a Material You palette would defeat the point.

So, only 1), the accent color, would be affected. Is that what you had in mind?

**Comment by arun54321** [comment]
I prefer having stock material you design. I did not find any issues with readability with the material you apps - infinity for reddit, gmail, google messages.
If you don't want material you color schemes, that's fine. 👍
