### ISSUE TITLE
Search / Filter with filename(path) / Owner / Size / Date ...

### ISSUE THREAD

**Issue by netcharm** [deckerst/aves#265]
**Is your feature request related to a problem? Please describe.**
Add search / Filter with filename(path) / Owner / Size / Date ...

**Describe the solution you'd like**
add search / filter conditioin to find media with path / owner /size /date, like:
1. date:2022/05 date:<y|m|d> <<>=!> <2022|05|31>
2. size: <w|h|l> <<>=!> 1024[ |b|k|m]
3. owner: <part of owner name>
4. name: <part of path name>
5. exif: <any text contained in exif metadata>
6. iptc: <any text contained in iptc metadata>
7. xmp: <any text contained in xmp metadata>
...

**Comment by deckerst** [comment]
I may add some (like date, file size, dimensions), but not the exif/iptc/xmp because I don't index the fields from these sections.

For the name, the default query is already checking the title (which is usually the file name without extension). Not the path, though, as the album filters would usually cover that. What's your use case for the path filtering? Interested in the file extensions? or subtrees?

For the owner, you mean the app/package owner as displayed in the `Info` page, right? Is it something you would actually use?

**Comment by deckerst** [comment]
Implemented a few keys: year, month, day, width, height, size.
With these operators: <, >, =.
It's pretty lenient on spacing, and it's usable in the search page and in the title filter bar.

Examples:
- year<2012
- width = 1024
- size > 2m
