### ISSUE TITLE
When auto play video is on, the first second plays in slow motion

### ISSUE THREAD

**Issue by git-pietro** [deckerst/aves#267]
**When clicking on one of my videos the first second is longer than a second, it's like it's in slow motion. The process to start a video takes "too" long.** 

_v1.6.8_
_Android ColorOS 12.1
Oppo Find X5 Pro_

**Comment by deckerst** [comment]
I see 2 different phenomena that feel like what you describe:
1) on my mobile, some MP2TS videos (recorded on a Panasonic camera) do start in a weird way, as if there was no key frame, and the playback needed to play in slow motion to reconstruct the beginning,
2) by design, video playback starts by fading out its cover and it takes around a second.

I consider 1) a bug but I've only seen it happened with common MP4 videos, and it depends on the video library Aves is using. Nothing much I can do here.

And I do 2) on purpose for smooth transitioning between thumbnail previews and playback. I'm happy with the effect and this won't change.

Does your issue sound like one of these, or something else? To dig further, I'd need a screen recording of your observations. Also, does it happen for all videos, or only one?

**Comment by marcosilva85** [comment]
Although the ticket is  closed, I also observe this side-effect.
I can describe it:
- On the Aves gallery, choose any video (side-note: my videos are recorded in mp4 h264, the most typical format/codec).
- This plays the animation that enlarges it so that it goes to full-screen (~0.3s).
- Short fade-out, just before playback (~0.3s).
- Video starts playing <- here,  the initial second is choppy and is probably a bug.

;)
