### ISSUE TITLE
Round ui corners

### ISSUE THREAD

**Issue by iJahangard** [deckerst/aves#286]
There is a problem in new style phones which they have rounded displays
so android material design that aves uses right now is looks reallt good on old phones with sharp corners

current roundness is about 4dip if you add ability to set custom values (not any values) like 8 12 16 18 20 24 26 32 ...
that would be awsome !!!!

**Comment by deckerst** [comment]
I understand that modern screens have rounded corners (mine is like that), but I don't understand your request.

What would your requested setting do? Could you provide screenshots, samples or mockups?

**Comment by iJahangard** [comment]
![Screenshot_20220719-103026_Lawnchair](https://user-images.githubusercontent.com/67248292/179676551-b5ecad49-3210-494a-ba60-1cfaf4b37f93.png)

I would prefer to have an option which is like the screenshot above make me able to set a custom value for the corners, but that option should not have any range of roundness
In old material design guide we used 4.0dip but now we do more rounded corners
So the option has to have scales of usual valuees like 4dip(which is default), 8dip ,12dip, 16, 20, 22, 24 and may more

**Comment by deckerst** [comment]
There are different rounded corners everywhere in the app. Your requested setting would apply to which ones?

![Screenshot_20220719-084122_Aves](https://user-images.githubusercontent.com/13898333/179683228-c85df2ef-073c-4c9c-bc9d-1de5c29333ef.png)

**Comment by iJahangard** [comment]
That would be awesome if you make separate option for each section plus album box

**Comment by deckerst** [comment]
> "thick borders have meaning"

Thick borders indicate filters, whether they have a cover image or not, multiline or not, coloured or not.

> PS. I do love first logo from https://github.com/deckerst/aves/issues/798#issuecomment-1771185509 <3

Haha, I'm so glad I moved on from that design!

> PSS. I don't understand current trend to make everything more and more round.

Some time ago, Microsoft was getting very squarish and colourful. I liked that they were trying their own thing, but I don't know if they kept that design... Anyway, in my app I try to use roundedness and other visual cues as hints for identity and behaviour. Here for example to distinguish a media item thumbnails (square) from filters with a cover image (rounded).

**Comment by M7amma** [comment]
Reviving this one (https://github.com/deckerst/aves/issues/286) with a narrower version of the ask, since I imagine the fully custom dp-value picker (8/12/16/18/20...) is a lot of extra UI surface for a small visual detail.

Would a simpler **square vs. rounded toggle** be more feasible? Fossify Gallery uses plain squared album thumbnails by default: https://github.com/FossifyOrg/Gallery

Rather than exposing arbitrary radius values, even just a binary switch ("Square" / "Rounded", using the current default for the rounded option) would let users match their preferred grid style without the complexity of a full custom-radius picker. Wanted to flag this scoped-down version in case it changes the feasibility calculus.

**Comment by deckerst** [comment]
@M7amma thanks, I appreciate your way of thinking. However, I'm stubborn on that point, regarding keeping UI customisation to a minimum in general, and this filter roundness in particular, because it has meaning in the app.
