### ISSUE TITLE
Support HEIC motion photos

### ISSUE THREAD

**Issue by protist** [deckerst/aves#305]
**Describe the bug**
I use Samsung's built-in camera app. This creates motion photos, but there are not recognised by Aves.

**To Reproduce**
1. Go to a motion photo taken with Samsung's built-in camera app
2. Aves does not recognise it as a motion photo

**Expected behavior**
Aves should recognise it as a motion photo

**Screenshots**
Aves does not recognise this as a motion photo
![Aves](https://user-images.githubusercontent.com/646668/185770851-b5b03e72-6bbb-4089-a0f5-e1fa9ee34141.png)

The Samsung gallery app does recognise this as a motion photo
![Samsung gallery](https://user-images.githubusercontent.com/646668/185770873-aa2d6999-cc4a-49c6-a84c-4fede8a76d9d.png)

**System information and logs:**
N/A

**Additional context**
Here is the [image](https://github.com/deckerst/aves/files/9388208/20220812_112058.tar.gz) above, taken with the Samsung camera app.

**Comment by deckerst** [comment]
I didn't know motion photos could be made in HEIC format! I also use the Samsung camera but with the default JPEG format, and these motion photos work fine.

**Comment by protist** [comment]
Ah right, sorry, I forgot I had also changed this setting. Thanks for picking that up!

**Comment by deckerst** [comment]
Done, with a few limitations.

Reading XMP (which is necessary for motion photo detection) from HEIC images is not supported by the library I'm using, so I fall back on the native Android capabilities. That's only available from Android 11 and it doesn't work for all files, but at least it works with the sample image you gave.

As for handling the motion photo itself, playback is supported, opening and inspecting the video part is also supported, but stripping the video is *not* supported (because editing XMP of HEIC images is not supported).

As a side note, if you care about privacy, you should know that in your sample file the location metadata is included twice:
- in the Exif metadata of the HEIC image itself,
- inside the MP4 metadata of the embedded video.

**Comment by protist** [comment]
That's fantastic. Thank you for the super-quick response. Those limitations sounds perfectly reasonable.

That's also interesting about the location metadata. I often strip the EXIF data, but never thought about the MP4 metadata. Thanks for the heads-up, and I'll keep that in mind.

**Comment by deckerst** [comment]
@protist the fix is in the new release v1.6.12, but you'll need to rescan these images. The most efficient way to do it is as follows:
1) go to "All collection"
2) menu > "Stats"
3) tap on "HEIF"
4) menu > "Rescan"

**Comment by protist** [comment]
@deckerst Just installed the new version. That works perfectly. Thank you again for the quick fix!
