### ISSUE TITLE
Seemless loops

### ISSUE THREAD

**Issue by Donkey-Doug** [deckerst/aves#356]
I have the settings "loop videos" on, but the loop is not perfectly seemless. The video paused half a second before the next loop starts. I think a seemless loop would be better.

**Comment by deckerst** [comment]
I agree it would be better, but it's probably not going to be fixed anytime soon, because it's a defect from the video player library Aves uses.

**Comment by Christmastree56** [comment]
Hi there deckerst, is Donkey-Doug referring to when a slideshow plays a video, it briefly pauses/flickers/fades first before playing? Just wanted to make sure I understood because I also noticed this when playing a slideshow. You are saying it is an issue with the current video player the app uses correct?

**Comment by deckerst** [comment]
OP is talking about the playback transition when a video repeats in a loop, between the end of the video and its beginning.

I believe your issue is different. When a video starts, the app first shows the cover (embedded cover image if there is one, or whatever is used as thumbnail), and then fades to the video. This is the intended behavior. Maybe you don't like that behavior, or maybe there's indeed an issue when playing videos in slideshow, but i can't tell without further details. If you think it's buggy, please open another issue, with a screen recording.

**Comment by Christmastree56** [comment]
Ahh, I understand now. Thank you. Then with that description, there is likely no bug. As you mentioned, it is just a preference thing. I was unsure if there was an option to disable that behavior. So far, that is the only thing that sticks out to me for my preferred use case. Everything else is great, it's very clean, and I love the aesthetic. The stats in there is also a cool feature as well. Looking forward to more updates 😎

**Comment by deckerst** [comment]
Aves relies on `media-kit` (backed by `MPV`) for video playback. The [current version of media-kit on github](https://github.com/media-kit/media-kit/blob/18f155fe81cae93db712307411a17b2b93760eb6) seems to perform seamless loop as expected. Aves now uses that version (rather than the currently published version of media-kit v1.1.11).
