### ISSUE TITLE
doubt weblate

### ISSUE THREAD

**Issue by gallegonovato** [deckerst/aves#373]
Good afternoon @deckerst 

I received a notice from weblate. But I don't understand exactly what it refers to.

It says to create a new site for Brazilian Portuguese and Mexican Spanish.

Or modify the existing Portuguese to Brazilian. And Spanish, and put Mexican.

If it is the latter I can not do it since I am not the creator. But the first if you allow me to add it.

Best regards

**Comment by deckerst** [comment]
Thanks for reaching out. I wanted to contact you but didn't know how, actually.

The original translations for Aves, before using Weblate, included a "Portuguese" translation. The country wasn't specified, but it's actually the "Portuguese (Brasil)" variant. There is no need to create another one in Weblate specifically for Brasil.

I noticed that you had created a new language on Weblate for the Brasil variant, so I did the following:
- I updated the original "Portuguese" language with your changes,
- I removed the "Portuguese (Brasil)" language from Weblate,
- I added the notice you mentioned.

Also, because of technical reasons, I currently have some trouble making Weblate match some languages with the right files in the code. I'm still fiddling with settings for the "Short Description" and "Long description" components. The othercomponents should be OK as they are.

I'll try to clarify the notices on Weblate regarding Portuguese & Spanish.

**Comment by deckerst** [comment]
I fixed my technical issues with Weblate.

Regarding the variants in Spanish and Portuguese, I'm aware that there are regional differences. What I explained above is that contributors should consider the default "Portuguese" language as Brazilian Portuguese. But if they want to contribute Portuguese from Portugal, they should add in Weblate the language "Portuguese (Portugal)".

Thanks again for your contributions @gallegonovato !

**Comment by gallegonovato** [comment]
Good afternoon @deckerst

Glad I could be of help.

What maybe, due to the way of expressing in Spain, and some areas of Spanish speaking America or Latin America. Maybe the translation in Spanish can vary often.

Maybe it would be good to think about opening a Spanish (Spain) one so as not to confuse you. And not to change the translation over and over again. Maybe a person from Spain says one thing one way, and another from Latin America another way. And maybe we are correcting each other. And giving you the run-around.

I don't know if you would allow to modify the tradition of https://hosted.weblate.org/translate/aves/app-main/es/?q=has:suggestion (since the translation in Spanish is very bad), and this https://hosted.weblate.org/translate/aves/app-main/es/?q=has%3Asuggestion&offset=2#suggestions lacks the tilde in Spanish.

A hug and thank you for your time and help.

**Comment by deckerst** [comment]
I'll take a look at your suggestions, thanks!

Also, I noticed that you edited or suggested translations for Spanish, Portuguese, Italian, Galician, Chinese and German. This is impressive but, if you don't mind me asking, are you fluent in all these languages? If your suggestions simply come from tools like Google Translate, I'd rather you refrain from adding these edits, so that native speakers can tackle them later.

**Comment by gallegonovato** [comment]
Good afternoon:

I am from Spain, more specifically from Galicia ( that's where my name comes from). I go to Portugal very often and I speak it. And if I study the rest of languages. Family abroad for example. Hence the reason. And that I speak it. 

But you are the one who rules.

Best regards

**Comment by gallegonovato** [comment]
Good afternoon @deckerst

I have a question on some words to translate. The same is: Open home

Home in mobile exists in Spanish. But you can also say home screen, Home and Assistant, etc..

Then Home in Spanish is:  casa, hogar, domicilio . (i.e. where people live).

But I don't know if you want to leave it as: Abrir Home . Or Abrir Inicio, or Abrir Pantalla principal, or Abrir pantalla de inicio for example.

Best regards and sorry for the inconvenience.

**Comment by deckerst** [comment]
You can see how "home" is used in the app and translated in Spanish so far:
https://hosted.weblate.org/translate/aves/app-main/es/?offset=1&q=home&sort_by=-priority%2Cposition&checksum=

As you mentioned, here it's not `casa`, but rather `inicio` or `pantalla de inicio`, because it refers to the home page.

**Comment by gallegonovato** [comment]
Good afternoon @deckerst

That it's not home (place where you live), I already figured. 

But in Spanish the word home is also recognized. But for telephony use or referring to them.

That's why I didn't know whether to leave home untranslated or translate it to home screen.

Thanks for your help.
