### ISSUE TITLE
Redesign album name and count

### ISSUE THREAD

**Issue by Donkey-Doug** [deckerst/aves#38]
The current design makes it both hard to read the text and see the cover image behind the text.

Current view:
![test1](https://user-images.githubusercontent.com/50382414/103500946-0055bf80-4e4d-11eb-994e-1047d7b313ae.png)

Example of a possible alternative view:
![test2](https://user-images.githubusercontent.com/50382414/103500956-09df2780-4e4d-11eb-98fa-a59c6afd1058.png)

**Comment by deckerst** [comment]
If the metadata aspect of this app is not important to you, maybe you could
try this app:
https://f-droid.org/en/packages/com.simplemobiletools.gallery.pro/

This is a good open source gallery app, with a very standard and
customizable look. Given the various style issues you raised here, maybe
that app could be a better fit for you.

**Comment by arun54321** [comment]
Yeah. It is difficult to see the pictures with text at center. Could you add a option or something move label to bottom? Or label below the picture like Google photos.

**Comment by deckerst** [comment]
The layout for Albums / Countries / Tags was modified. I went with @arun54321's suggestion to put the label below the picture because it works well with a wider range of font sizes. It's released as part of Aves v1.5.2.

Here's an example:
<img src="https://raw.githubusercontent.com/deckerst/aves_extra/main/screenshots/S10/6-S10-countries.png" alt='Countries screenshot' height="400" />
