### ISSUE TITLE
Add photo taken device brand name & model number to info page

### ISSUE THREAD

**Issue by jerryn70** [deckerst/aves#387]
Title says it all

**Comment by deckerst** [comment]
First off, please read this before opening feature requests:
- #234

This piece of information is already in the Info page, down in the Exif section. Have you explored these sections?

**Comment by jerryn70** [comment]
@deckerst sorry I just saw that section now. BTW I have a question, do you have any plan to implement auto rotate screen if the screen orientation is in lock.?

**Comment by deckerst** [comment]
I don't plan to do it, because my opinion is the following: if the user wants auto-rotation, they can already unlock their screen at the system level with a simple toggle. No need for each app to reimplement that.

That said, if the user screen orientation is locked, Aves viewer overlay automatically shows a quick action that allows them to manually override the orientation.

**Comment by jerryn70** [comment]
@deckerst Thanks for explaining.  Today i renamed one album folder from Aves gallery. After that date of all the images in that folder got changed. Why that happened

**Comment by deckerst** [comment]
There are several points here:
1) Media files *always* have a "file date", and they *can* have a "metadata date" (e.g. the date a photo was taken, which is written in Exif metadata). Aves displays the "metadata date" when possible, and the "file date" as fallback.
2) [Aves is not a file manager](https://github.com/deckerst/aves/wiki/FAQ#is-aves-a-file-manager), so some file operations are not as straightforward as you'd think.
3) Renaming an album in Aves is not the same thing as renaming a folder in a file manager. Basically, files are moved, rather the folder being renamed.
4) Because of 2) and 3) the "file date" is modified when an album is renamed, but the "metadata date", if there is one, is not modified.

If the files in the renamed album have a "metadata date", the date displayed in Aves won't change. But if the files have no "metadata date", the date displayed in Aves will change.
