### ISSUE TITLE
[Widget] Last Photo

### ISSUE THREAD

**Issue by xmha97** [deckerst/aves#404]
Please add an option to show the last photo instead of showing random photos.
Thanks.

**Comment by deckerst** [comment]
I added the option, but note that even if you choose to display the most recent photo in the widget, the widget will display the last one __as known in Aves__. Meaning that it doesn't update in real time. Aves collection must be up-to-date for the widget to be up-to-date. Aves does not run a real time background service to update itself, by design.

**Comment by xmha97** [comment]
> I added the option, but note that even if you choose to display the most recent photo in the widget, the widget will display the last one __as known in Aves__. Meaning that it doesn't update in real time. Aves collection must be up-to-date for the widget to be up-to-date. Aves does not run a real time background service to update itself, by design.

Is the collection updated every time I open the app?

**Comment by deckerst** [comment]
Yes.
