### ISSUE TITLE
Option to automatically move favorites to (sub)folder/album

### ISSUE THREAD

**Issue by JanWaldhorn** [deckerst/aves#407]
**Sync/share favorites only**
I use [Syncthing ](https://syncthing.net/) to keep my pictures in sync and backed up between devices. This involves designating a folder such as "DCIM" or a subfolder whose contents are synchronized.

I usually take quite a few photos, of which I usually only find some really good, but often don't delete the others right away because it documents something, for example.

Anyway, the good/favorite pictures I edit from time to time in [DigiKam ](https://www.digikam.org/) on my PC (recognize faces, more tags etc.). Especially pictures of our child I would like to share with my wife as well. Even here it is only about the favorites. Sending these pictures via messenger is troublesome in many ways.

**Suggested solution**
The easiest way, would be to have an extra (sub-) folder "Favorites", where these pictures are stored and kept in sync between the devices using Syncthing. For me, an option that automatically moves either all "Favorites/Heart" or all starred images to a specified folder would be awesome.
As a workaround, I currently filter the favorites, select all of them and then move them to the subfolder. (And skip the images already in the folder).
![Aves_auto_move_favorites_compr](https://user-images.githubusercontent.com/57268762/203407377-8a5fc7e9-9d2d-4519-9c81-1f702310a3e5.jpg)

**Comment by deckerst** [comment]
I understand your situation, but it's not clear to me that the solution you suggest is the right fit. Your syncing solution is file-based, while Aves is metadata-based.

If you use the fav action with the intent that all your favs are gathered in the same folder, then what you actually want is to use the "move to album". So I see 2 ways here:
- the synchronous way: when you spot a fav, you should use the "move to album" action. But I guess you find it too tedious to use. Let's make it more convenient.
- the asynchronous way: when you spot a fav, you add it to your favs in Aves, and then another app runs from time to time in the background to perform the move. Apps like Tasker, IFTTT, etc. should help (disclaimer: I haven't used them!) Maybe Aves will need to expose some intent for these apps to retrieve the paths of your favs.

I don't want to perform the async task in Aves, because I don't want to reimplement Tasker/IFTTT for a niche need.

**Comment by JanWaldhorn** [comment]
I'm very excited about Quick Actions #390 in Aves v1.7.5 and you're right, favorites are not that important in my wish. I just haven't come up with any other solution.
Would it be possible similar to what you [mentioned ](https://github.com/deckerst/aves/issues/406#issuecomment-1326576065) in #406, using a long press to select the last folder used? Or the other way around, short press moves to a default folder, long press lets select any other folder?
Second idea, to show the quick actions on multiple selection of images also on the home page? Either like in the photoshopped image in the attachment as an extra bar or additionally in the existing navigation bar. But the latter might be a bit confusing when combining Navigation and Quick Actions.

![Aves_multi_move](https://user-images.githubusercontent.com/57268762/203846665-5461e254-c05c-40b1-87f2-df9541ccd3df.jpg)

**Comment by deckerst** [comment]
> Would it be possible similar to what you https://github.com/deckerst/aves/issues/406#issuecomment-1326576065in https://github.com/deckerst/aves/issues/406, using a long press to select the last folder used?

Yes, I was thinking along these lines.

> to show the quick actions on multiple selection of images also on the home page

Not what you photoshopped, but do you know you can change the quick actions at the top of that page? In the "Settings" > "Thumbnails" > "Quick actions", then tab "Selecting". Personally, I put the "move" action there as I use it a lot.

**Comment by JanWaldhorn** [comment]
No, I had overlooked that until now. Thanks! Now I'm just curious about a long press version, or an additional quick action for a default folder ("Favorites") and possibly the ability to skip images that are already in the folder by default? Then it would be a real quick action and super easy to assign like a heart.

**Comment by deckerst** [comment]
With the coming changes to the quick actions (rate / tag / move / copy) and overlay (rate / tags), I think it's best to close this issue and let you try out the next version of Aves (whenever it will be released). Feel free to give feedback then.
