### ISSUE TITLE
Hiding / warning about missing media items

### ISSUE THREAD

**Issue by Terrance** [deckerst/aves#432]
This is effectively a follow-on to #251 and #384, as I found those shortly before raising a bug report about deleted media still showing in Aves.  I use Syncthing as a two-way sync between my phone and computer, for photos and other files.  Typically I end up taking multiple pictures at once, and later (on the computer) choosing the better one to keep -- this means I delete unwanted pictures on the computer and Syncthing will sync the deletions back to my phone.  As Syncthing is working with the filesystem directly rather than the media database, stale entries are presumably being left in the database.

#### Describe the solution you'd like

Ideally I'd prefer these missing items to just not be shown in Aves, assuming the media store will eventually catch up and process the deletions.  I've compared with Simple Gallery and the stock OnePlus gallery, and both of those are hiding the missing media.  If you're not keen on hiding them outright, perhaps a filter or option to conditionally show them would be viable?

#### Describe alternatives you've considered

I'm aware I can "delete" them from Aves to clean up the stale entries, but that means having to sift through all my pictures twice.  There's no indication from the collection views that the media is missing, nor when I open the image full-size -- all the metadata appears to be cached, so it's only the poor image quality (as it stretches the thumbnail rather than opening the full-size original that doesn't exist any more) that gives it away.  Could we alternatively get some indication in the grid and full-size views when files are missing: a ⚠ or similar icon, or fading out items in the grid?

#### Additional context

System information:

```
Package: deckers.thibault.aves
Aves version: 1.7.7-izzy
Aves build: 8701
Flutter version: 3.3.9
Flutter channel: stable
Android version: 12
Android API: 31
Android build: EB2103_11_C.07
Device: OnePlus EB2103
Geocoder: ready
Mobile services: ready
System locales: en_GB, en_US
Aves locale: system -> en
Installer: org.fdroid.fdroid
```

Log file with errors when trying to view deleted pictures: [aves-logs-20221204_145653.txt](https://github.com/deckerst/aves/files/10148853/aves-logs-20221204_145653.txt)

**Comment by noearchimede** [comment]
I have exactly the same workflow as described in this post and thus also the same problem. I really appreciate that the missing images now show up as a "missing image" symbol and not as a lower quality version of themselves (I gess you changed that since this issue was opened?).

However, I am still wondering if you would consider adding a feature to remove these images completely, either automatically or maybe with something like the "Rescan" button in Collection view?
I'm asking because I find it annoying to manually delete all "missing photos" on my phone and also don't see the point in having them show up, since anyway if the file is missing the image can't be recovered (unless of course using backups or other stuff that has nothing to do with Aves).

**Comment by deckerst** [comment]
> the point in having them show up

It shows that the media database at the OS level is filled with obsolete items. Showing them allows the app to clean them (with action from the user). It also shows that an app/tool/workflow could be improved to manage media in a cleaner way. This media database is used by Aves, but also by many other apps, and I find it more meaningful to make the user aware that something is wrong on their device rather than sweeping it under the rug.

**Comment by deckerst** [comment]
By the way, my *opinion* is that the right thing to do would be for the Syncthing Android users to file an issue at their repo so that they delete media the proper way.

**Comment by noearchimede** [comment]
Thank you for your reply. I did non know that, I thought that the media database was maintained and read by Aves only. Now I see why it makes sense to show the missing images! I will see if I can file an issue at Syncthing for this issue, thanks

**Comment by noearchimede** [comment]
So just to be sure that I'm not missing any existing option, the quickest way to deal with these missing pictures at the moment is to select them all manually and delete them right?

**Comment by deckerst** [comment]
Yes, there is no indicator yet to help find the obsolete items.

**Comment by Terrance** [comment]
So I just gave this some scrutiny again -- on my device at least, the deletions by Syncthing seem to be being picked up pretty quickly by the media store now (a few seconds' delay), unlike at the time of reporting when the background rescans used to take anything up to a couple of hours to notice.

I also had a look at Syncthing on Android, and it appears [they already have (and always had) some handling for this](https://github.com/syncthing/syncthing-android/blob/1.23.4/app/src/main/java/com/nutomic/syncthingandroid/service/EventProcessor.java#L151-L155), though it's recently been removed for newer devices seemingly due to compatiblity issues.

**Comment by insilmaril** [comment]
Also just ran into this. Could the "rescan" option in aves maybe trigger a media store rescan?

I know there dedicated apps to do that, but that's what I would expect from a "rescan" anyway.

Btw I love aves, thanks!

**Comment by Terrance** [comment]
For what it's worth, in the cases where I made large media changes that weren't entirely picked up, I've been manually invoking the scanner via Termux (no root required; can also be done over adb):

```sh
am broadcast -a android.intent.action.MEDIA_SCANNER_SCAN_FILE \
  -d "file:///storage/emulated/0/DCIM/Camera/IMG_20231010_012345.jpg"
```

Note that you'll have to do this for each affected file path, and it takes a while to go through (1-2 seconds per file).

**Comment by deckerst** [comment]
> I know there dedicated apps to do that

Are there some apps that can actually do that on modern Android (and without root)? I'm genuinely interested if you know an open-source app like that.

> that's what I would expect from a "rescan" anyway.

This `rescan` is only useful when a new release of Aves introduces scanning features. For example, if new kinds of motion photos are detected, it would allow users to rescan their collection to detect these. It's not meant to trigger the Android media scanner, because as far as I know it's impossible to do so globally on modern Android.
