### ISSUE TITLE
Exif image description in Cyrillic is displayed incorrectly.

### ISSUE THREAD

**Issue by polinom11** [deckerst/aves#448]
**Describe the bug**
I enter the excipher description of the image: "Подьезд podezd". I open in the section "Information" Exif IFD0. Image description looks like: "??????? podezd"

**Expected behavior**

**Screenshots**

![1671137688063](https://user-images.githubusercontent.com/48948406/207967419-edf9f64d-a0bd-4be1-9349-6bb350aae968.jpg)
![1671137688068](https://user-images.githubusercontent.com/48948406/207967436-d5932fe9-fd26-4348-b116-7dd97ef6d432.jpg)

**Comment by deckerst** [comment]
Thanks for the report. I guess you're the one who reported it first in the Play Store review.

Following your review, i realized that the library I'm using to edit Exif only writes ASCII. The Exif format does allow writing in Unicode, which would solve the issue here.

I need to find a library that supports Unicode writing, or fix the library I'm using.

**Comment by deckerst** [comment]
Actually, it's more subtle:
- the Exif `Image Description` field only allows ASCII (that's the spec),
- the Exif `User Comment` field has provisions for Unicode, but there's an ambiguity on the encoding UTF-16BE or UTF-16LE, and some Exif editors get confused and make the job of Exif readers more difficult.

So, my take is that these fields are redundant and inferior to the XMP `dc:description` field.
Aves will read descriptions from these fields (by precedence):
- XMP / dc:description
- IPTC / caption-abstract
- Exif / UserComment
- Exif / ImageDescription

But if you edit the description Aves will only write to `XMP / dc:description`, and will remove `Exif / UserComment` and `Exif / ImageDescription`.
