### ISSUE TITLE
Photo edit

### ISSUE THREAD

**Issue by gun4qmm7h** [deckerst/aves#451]
I know that photo editing isn't on the TODO list as of now, but I was wondering when it will be implemented. I love the app but hate having an extra app to do all the editing.

Keep up the good work
Love the work and app

**Comment by deckerst** [comment]
No estimation, no plan.

But i don't understand why some people dislike using dedicated apps for different tasks. Would you prefer to have a mediocre editor embedded in Aves rather than using a mature editor app like Snapseed? It took several years to make Aves a decent gallery. How many years will it take to make a decent editor?

By the way, even if Aves included an editor, it would be launched and used exactly like another app.
