### ISSUE TITLE
Support to scan compressed folders and hidden folders.

### ISSUE THREAD

**Issue by UniverseCodex01** [deckerst/aves#455]
**Is your feature request related to a problem? Please describe.**

In apps like Telegram or WhatsApp, camera section or choose files section, shows all images in device and sdcard, this also can apply to all media editor apps, so all media files are mixed and has no privacy.

**Describe the solution you'd like**

I want to separate my normal pictures with daily usage pictures, for example when I open WhatsApp camera or file selector in app I only want to see my photos, not my wallpapers, memes, Pinterest images, etc.
To solve this I think that a function to work with pictures stored in compressed folders like, for example wallpapers.zip/.rar/.7zip/.targz/etc it's a good idea because normal apps don't scan for pictures in compressed files, so normal apps only will show pictures stored in folders and when I want to see or work with my other pictures I can do it from aves gallery, because will be the only app that can scan images in compressed files, with this we can get more privacy and not mixed pictures.

**Describe alternatives you've considered**

In alternative to scan and works with compressed files is the function of scan hidden folders like, for example .wallpapers or .memes, this is a different method but results are the same.

**Additional context**

A good example of first method to resolve this problem is Perfect Viewer, is an app centered in read of comics and mangas and can work with .zip files because in general images of a comic chapter are stored in compressed files, so I can read my downloaded comics in perfect viewer and other apps can't show it.

**Comment by deckerst** [comment]
Regarding hidden folders, please check out the FAQ, especially [this](https://github.com/deckerst/aves/wiki/FAQ#can-aves-display-media-inside-hidden-folders).

As for zip files, I've considered handling opening them, but in any case they won't be part of the collection (because they are not media, just like hidden folders).

For what you're trying to achieve (having only a specific app to access specific files), it seems you should use a vault (aka secure folder). You can subscribe/upvote #114 to show interest. But it will be faster for you to use one of the many existing vault apps out there.
