### ISSUE TITLE
slide to show side menu 

### ISSUE THREAD

**Issue by joefast77** [deckerst/aves#465]
can I ask for a feature : swipe to show side menu instead of reaching for the hamburger menu , it's easier for people with small hands and big devices . thank you 
![Screenshot_2022-12-28-00-07-08-03_ee4e2c77f5dd6d2e03bdeacf38a89f81](https://user-images.githubusercontent.com/80571759/209717696-846060cc-7cae-4c22-929e-993aa728cf5e.jpg)

**Comment by deckerst** [comment]
At the OS level, do you use swipe gestures for navigation instead of the buttons?
By default users can open drawers by swiping from the left edge, but the OS swipe gestures overtake this gesture. (That's one of the reasons I prefer OS navigation by buttons instead of gestures.)

Handling a horizontal swipe gesture on the middle of the screen to open the drawer is a possibility, but I'm reluctant to do that, because that gesture could be useful for another purpose in the future (for example sliding out an album bar like in Samsung Gallery).

**Comment by joefast77** [comment]
yes I do use gestures , but if that is inconvenient for you maybe it could be included in the bottom navigation bar if that is possible .

**Comment by KeysGilbert** [comment]
I agree that making this a slide motion would be pretty inconvenient if you use gestures. If the new idea is to add the side menu to the navigation bar (thus, remove the hamburger menu) maybe I could try doing that?
