### ISSUE TITLE
Allow drag and drop of a thumbnail, with no geotag, onto a thumbnail that has a geotag for adding geotag

### ISSUE THREAD

**Issue by petazonk** [deckerst/aves#471]
Editing geotags is much easier now with the feature added in map view, however, it might also be good to have an even easier method of adding or fixing geotags. For example, let's say I take 5 photos in a restaurant but the middle photo didn't get geotagged. I know that all the photos were taken at the same location so if I could drag and drop the middle thumbnail onto another thumbnail then I could easily correct that bad or missing geotag.

Allow a long press option, in the thumbnail view, to give you the option of dragging and dropping a thumbnail onto another thumbnail such that the geotag information is copied into the bad or missing one. This would make geotagging super fast and easy.

The alternative is to use the geotag edit function from the map view.

**Comment by deckerst** [comment]
I think the benefit this would bring do not justify the downsides. Because having this would make more common use cases more difficult. Right now long press on thumbnails goes straight to selecting. Adding a menu here would be inconvenient.

Overall this use case is too specific and can already be addressed with the `edit location` > `choose on map` / `copy from other item` workflow.
