### ISSUE TITLE
Left handed "fast" scrolling

### ISSUE THREAD

**Issue by sparevermicelli** [deckerst/aves#482]
**Is your feature request related to a problem? Please describe.**
Scrolling by dragging the scrollbar thumb (to quickly scroll to an older date/year for instance) is only available when using the phone right handed

**Describe the solution you'd like**
Ability to switch sides of the scrollbar thumb

**Describe alternatives you've considered**
using other hand :)

**Comment by deckerst** [comment]
I'm unlikely to provide this option because, like many other UI elements, the layout is conventional according to the text direction of the current locale. For left-to-right, the drawer is on the left, the overflow menu is on the right, keys are on the left, values on the right, etc. And I don't want to micromanage the layout beyond that convention.

But I'm curious, how do you manage with other apps?

By the way, i'm surprised you intend to grab the thumb with one hand. I know i can't do that, even with the thumb on the "convenient" side ^^

**Comment by sparevermicelli** [comment]
I don't,  and it's been an annoyance for a long time in all the gallery apps ;). 

But I completly understand now. 


I am used to this pattern of scrolling with a thumb - I use Niagara launcher so it's a very natural movement for me. 
The tbumb is a little bit too far,  but still reachable by one hand. 

Thank you for the reply, feel free to close this.
