### ISSUE TITLE
Auto-flipped photos taken with the selfie cam aren't displayed correctly

### ISSUE THREAD

**Issue by LeonardoMantovani** [deckerst/aves#505]
**Describe the bug**
I've set in the Google Camera app to automatically mirror the photos taken with the front camera and in google photo and other gallery apps, they are showed as expected. In Aves, instead, every time I open the app (without having it running in background) they are displayed as flipped (the original pic, before GCam mirrored it) and in less than a second they get flipped and displayed properly.
I'll attach a 20sec video to explain myself better
https://www.swisstransfer.com/d/bfe261bd-867d-42b6-84ec-beb08b3be054

**To Reproduce**
1. Open Google Camera app
2. In settings, enable the option _Show selfies as their previews_
3. Take a bunch of selfies
4. Open Aves 
(I'm using a Pixel 6a running Graphene OS with Sandboxed Google Play Services if this can help)

**Expected behavior**
Selfies are displayed correctly from the beginning, just as other pics in Aves and all the pics (selfies included) in other Gallery apps

**Comment by deckerst** [comment]
I don't have the Google Camera. Would you mind sharing one of these selfie images (as it is, without recompression or other processing)?

**Comment by deckerst** [comment]
Thanks. I removed the link, for your privacy.

When Aves loads thumbnails, it first loads the thumbnail already embedded within the file, because it's the quickest. Then it makes on the fly a higher resolution thumbnail derived from the full image. It's a 2 step process.

With your images, what i see is that the embedded thumbnail is not flipped, but the image itself is flipped. In other words, Google Camera saves inconsistent thumbnails.

There's no indication in the file or metadata that the image was flipped, so i can't identify and single out these images to skip the embedded thumbnails. The only solution here would be for Aves to never use the embedded thumbnails. To me this is not acceptable because these embedded thumbnails are helpful most of the time. Your case is an exception because Google Camera creates files with the wrong thumbnails in specific circumstances.

**Comment by LeonardoMantovani** [comment]
Thank you for your explanation.
I agree with you when you say that it wouldn't be acceptable to disable embedded thumbnails, since for the majority of the photos they are correct and useful.
At this point if Google Camera was an open-source project I would have opened a issue there to fix this behavior, but since (sadly) it isn't, I can't do that. I'll try to contact the Google support about that and report here if I receive any answer.

In the mentime, What do you think about disableing the embedded thumbnails just for photos coming from Google Pixels front cameras? It wouldn't be for sure the perfect solution but it could temporary fix the problem, and it should be possible because in the `Exif SubIFD` parameters there is the `Lens Model` that identify if the pic was shoot from a Google Pixel front camera...

**Comment by deckerst** [comment]
Fair suggestion, but i want to avoid making code for specific devices or lenses.

One thing i wanted to do for a while is to add thumbnail edition, to regenerate or remove embedded thumbnails. It wouldn't be automatic but it's a way to actually fix the problematic images.

**Comment by deckerst** [comment]
I'll close this one as I think it's a bug with Google Camera, and #215 will track progress with thumbnail edition.
