### ISSUE TITLE
Albums in nested folders: Be able to access albums hierarchically or group albums.

### ISSUE THREAD

**Issue by Jartyyy** [deckerst/aves#511]
Hey,

first of all a few kind words. I really like the app and its usability is superb! The way to search by connecting different tags, ratings etc is the best I've ever used. Keep up the good work, it's highly appreciated.

**Is your feature request related to a problem? Please describe.**
When the file structure isn't flat, but there are many sub-folders in folders, Aves shows the folders on the lowest level as albums. Folders in a higher level are only shown as albums, when they also have pictures inside, that aren't part of a sub-folder. When you have 30 subfolders in folder A and 30 subfolders in folder B, it can get difficult to quickly access the data I want, because I cant quickly select A or B.
At the moment I have +500 Albums in Aves that are connected to different topics (drawings, phtographs, etc.) and when I try to tag all my drawings, it's hard to filter the right albums.

**Describe the solution you'd like**
I'd like to be able to navigate to the subfolders through the folders. In F-Stop this is called "nested directories" and other apps like Simple Gallery offer similar fitures.

**Describe alternatives you've considered**
Sadly I can't offer a workaround yet. I have 500 albums in Aves. So I have to search for the folder name to find the album.
Another solution would be the option to group the low-level albums and when selecting the group, you see the albums it concerns.
Even if it's not possibly to show albums in a more nested view, do you know a way that can make my life a little bit easier?

**Comment by deckerst** [comment]
Thanks, glad you like the app!

As for the nested folders, there's already an issue for it:
- #268

I also think nested folders would be useful. If/when I do it, it would probably be more like Samsung Gallery, with user-defined album groups, rather than automatically organizing sub-albums based on sub-folders.

> do you know a way that can make my life a little bit easier?

Nope :/

**Comment by jbrown1597** [comment]
> Thanks, glad you like the app!
> 
> As for the nested folders, there's already an issue for it:
> 
> * [Nested albums #268](https://github.com/deckerst/aves/issues/268)
> 
> I also think nested folders would be useful. If/when I do it, it would probably be more like Samsung Gallery, with user-defined album groups, rather than automatically organizing sub-albums based on sub-folders.
> 
> > do you know a way that can make my life a little bit easier?
> 
> Nope :/

Chiming in here,

I ab-so-lute-ly 
BEG 
BEG 
BEG you not to implement Samsung Gallery's nested folder implementation UNLESS it's *OPTIONAL* (in addition to the standard Nested folder implementation)

Why?

1. It's all temporary. (And I'd wager most don't even realize it)
The folders only exist on that phone, on that app. It inherently punishes people for maintaining their files. 
New phone? Poof! Time to start all over again (-:

2. It makes manual backups a REAL headache. 
We're talking from 30 seconds -> 2 hours. 
Instead of a quick drag & drop of the WHOLE gallery as backup, I have to manually backup EACH FOLDER where it is on my PC. 

3. Honestly, I can't think of what there is to gain by ONLY having user-defined folders
