### ISSUE TITLE
Terms of Service are inconsistent with the license

### ISSUE THREAD

**Issue by gdt** [deckerst/aves#517]
**Describe the bug**
I installed "Aves Libre" from f-droid.   At first run there are Terms of Service that the user must "accept".   These are obviously intended to form a contract that limits use, and thus the true license of the code is the combination of the actual license and the terms.   Taken together, they do not meet the Free Software or Open Source definitions.

**To Reproduce**
Install Aves Libre form f-rdoid.  I used 
```
Version 1.7.10 (9004) suggested Added on 2023-01-21 
```
Start it, and see terms presented.

**Expected behavior**
I exepect Free Software programs not to have Terms of Service.   At most, I expect a statement of intent from the author and a dismiss button.

**Screenshots**
Omitted because it's clear the way it is working is expected  from the current source code.

**System information and logs:**

The About screen is unreachable from the Terms page.

**Additional context**

Not realy relevant, but it's an interesting question what clickiing Agree means, when a user is running their own copy of code on their own computer. In the US, running a program is not a right restricted by copyright, and my impression is that this is generally true.   So one is interacting with their own computer, and thus agreeing with themselves, as I see it.

**Comment by deckerst** [comment]
I'm not a lawyer and I'm not interested in this kind of issues.

If you think the app, as it is with its terms, should be removed from F-Droid, feel free to reach out to them.

**Comment by LuccoJ** [comment]
I agree, with these terms, the app should not be present on F-Droid. If you are not a lawyer, then perhaps you should not write licenses on the spot when you already have a license.

**Comment by IzzySoft** [comment]
@deckerst after all you did to get this into F-Droid, should it fail on a phrasing? Maybe there's a middle-way making both sides happy – like having it (or just the "offending part") absent in the libre flavor?

But wait, what are we talking about? [Did I get it right](https://gitlab.com/fdroid/fdroiddata/-/issues/2893#note_1271128181) and it's about [these terms](https://github.com/deckerst/aves/blob/develop/assets/terms.md)? If so I'd honestly like to know what is the problem. I see none with those terms. But then, I'm no lawyer either.

**Comment by deckerst** [comment]
@IzzySoft thanks for being sane. I have no time or energy to cater to zealots.

**Comment by LuccoJ** [comment]
I have tried to explain in detail what the problem is with requiring (especially in ToS that must be accepted before the app can be used!) terms like "You must use the app for legal, authorized and acceptable purposes" in [my response to you on the F-Droid data issue](https://gitlab.com/fdroid/fdroiddata/-/issues/2893#note_1271137211).

Software freedom is not a joke, and terms that are like "come on, just use it legally, and we'll be friends" can be much trickier than they sound. That's why people who are not lawyers should probably refrain from making up their own license additions, and stick to licenses written by people who *are* lawyers, or with the assistance of lawyers.

From F-Droid's point of view, I am surprised the issue isn't viewed as very simple: if it doesn't fit software freedom as defined by the FSF or open source as defined by the OSI, it's not to be included. If this is "zealotry", I'm definitely proud to be a free software "zealot".

**Comment by Quintasan** [comment]
I believe it's perfectly okay for @deckerst not to change anything if he doesn't want to. I admit it would be nice to have a proper (as in lawyer-approved) ToS for this but it's his call.

At the same time @LuccoJ - I think there's nothing preventing you from forking this repository, removing the ToS and publishing on F-Droid if you really want to use Aves. The diff would be minimal so the effort associated with maintaining the fork would be minimal. That's what I would do in case when the author didn't want to use his time on changing the ToS and I were feeling strongly about this.

@deckerst is doing this in (I assume) his spare time without any compensation so he should be free to direct his effors anywhere if he wishes to do so. You and I may not like it but that's how you actually get free (as in beer) software in most cases.

**Comment by eyalroz** [comment]
> I'm not a lawyer and I'm not interested in this kind of issues.

Great, then you should have no problem removing the silly TOS. It's just wasting lines of code and users' time.

**Comment by calvinmkissinger** [comment]
like this comment if you came here from hacker news

**Comment by edwardgalligan** [comment]
> *I'm not a lawyer and I'm not interested in this kind of issues.*

I'm not a lawyer either, nor do I believe one should need to be a lawyer to release open source software. However, to be so dismissive & "disinterested" is somewhat at odds with intentionally open-sourcing your work. What was the motivation for this commit: https://github.com/deckerst/aves/commit/4b3d5c389bf415b4920208c006033b46223fe7fd

That is a legally binding license very deliberately added to the project - it seems worthwhile to be at least "interested" in whether it's legally compatible with your ToS.

**Comment by IzzySoft** [comment]
@deckerst As pointed out, to me this indeed looks like overdoing it by going "for the letter" (or how the bard would have put it: "Much ado about nothing"). On one hand I understand the argument of the "zealots". But on the other hand, the sentence in question is stating the obvious, as per my reading, so you might well consider removing it "for peace's sake". Let me "vivisect" it as I understand it. First, full quote:

> You must use the app for legal, authorized and acceptable purposes.

* **legal:** whoever would use it for illegal reasons wouldn't feel bound to the TOS anyway (and be punishable for the fact alone).
* **authorized:** I read this as "only view/manage/maintain material you are authorized to view/manage/maintain". That's just a more specific part of "legal" then. You authorize the use of the app per se with the license you've specified – so IMHO this must be about the "material".
* **acceptable:** is quite vague. To a thief it's acceptable to steal etc. You don't give a scope, so this just gives cause to "fights".

I had (and still have) no reasons not to accept the TOS, given my interpretation. You're no lawyer, IANAL either. We won't fight each other, even if I slightly misunderstood/misinterpreted the TOS as you meant it (which I pretty much doubt). So between us, this is rather a "moral" statement and, in my opinion, one without "power": If one uses it illegally, that person can be sued anyway. So why not simply remove the "TOS section"? What did I miss?

If you cannot agree with my conclusion, I gladly offer you a talk (e.g. via Jitsi) so we maybe can "iron it out", just let me know. I'm sure we come to an understanding and find a solution the "zealots" can accept as well.

(PS: no offense meant to the "zealots", which is why I put the term in quotes. It's important to defend freedom, and I can follow your arguments to a point. But from having worked with Thibault I have the opinion we might be "seeing ghosts" here – while I admit others might misinterpret his intention here. So before things escalate, I hope we can find a peaceful solution. As one understanding both sides, I'll offer to "mediate").

(PPS: heretical suggestion to rephrase to "You should use the app only for legal, authorized and acceptable purposes." This turns the restriction into a strong suggestion, thus removing the argument about "taking away freedom" :speak_no_evil: :dash:)

**Comment by Quintasan** [comment]
> Responsibility doesn't stem only from having been paid for your work.

Nor does it come from working on open-source software which has a NO LIABILITY clause so your point is kind of moot. If anything "responsiblity" you're thinking of comes from your beliefs when it comes to doing open source. I don't like the TOS but going further than asking the author to change it and not backing away when he says that he doesn't want to waste time on this feels kind of weird. You have all the tools required to make a more freedom-friendly fork and you come here and try to force the author to do something he doesn't want to. I might not agree with his decision or his ToS but I'm not going to argue he should change it when he explicitly said that he doesn't want to spend time on it.

**Comment by Quintasan** [comment]
> Responsibility doesn't stem only from having been paid for your work.

Nor does it come from working on open-source software which has a NO LIABILITY clause so your point is kind of moot. If anything "responsiblity" you're thinking of comes from your beliefs when it comes to doing open source. I don't like the TOS but going further than asking the author to change it and not backing away when he says that he doesn't want to waste time on this feels kind of weird. You have all the tools required to make a more freedom-friendly fork and you come here and try to force the author to do something he doesn't want to. I might not agree with his decision or his ToS but I'm not going to argue he should change it when he explicitly said that he doesn't want to spend time on it.

**Comment by eyalroz** [comment]
> not backing away when he says that he doesn't want to waste time on this 

Because he is being disingenuous. He has already "wasted time" on adding a TOS prompt. Why does a person who's "not interested in these kinds of issues", and who has already added a license, want to "waste time"  to write a TOS prompt?
