### ISSUE TITLE
Filter tags by multiple tags

### ISSUE THREAD

**Issue by csprr** [deckerst/aves#524]
**Describe the solution you'd like**
Have an option to filter by multiple tags in an 'and' or 'or' fashion.

(Example; filter by files having the 'food' and the 'person' tag and an option to show all of the pictures having either of them, or in the 'and' filter where there's files with both the tags)

Edit: Or being able to select multiple tags and exclude pictures for example that have both the tags 'food' and 'person', but exclude the ones that have 'food' in them.

**Comment by deckerst** [comment]
You can already combine filters by adding them from the Search / Stats page, or even from the Info page of an item. This is combining them with "and". "Or" is not supported at the moment.

Also, you can long press a filter (from the Search page, etc. or one of the folders already applied in the Collection page) to "filter out" items, rather than filtering them in.

Take a look and play with these features, and let me know how it goes.

**Comment by csprr** [comment]
That's actually perfect, same for issue #523 .
I simply was not aware of the search function being that powerful. I have probably clicked the search icon once, then pressed back (too fast and never saw the options) and was therefore missing the options.

Thank you for your fast and perfect replies!
