### ISSUE TITLE
Copy image to clipboard

### ISSUE THREAD

**Issue by yant0** [deckerst/aves#53]
Option to copy image to clipboard

**Comment by deckerst** [comment]
I took a look at this. The implementation on my side is trivial, but I noticed different clipboards behave differently.

The clipboard from `GBoard` (the Google keyboard) displays the image thumbnail as expected, but the clipboard from `Samsung Keyboard` does not display a thumbnail. In both case it's possible to paste the image, but the lack of thumbnail for the `Samsung Keyboard` is a bummer.

Checking system logs, I see that the `Samsung Keyboard` clipboard indeed fails to fetch the thumbnail (due to some inter-process issue). It looks to me like a bug from them, but I'm not sure...

@yant0 Do you know any other gallery that can copy an image to a clipboard? If that gallery can get the `Samsung Keyboard` clipboard to show a thumbnail, I'll try to dig deeper. Otherwise I might release the feature as it is.

I'm also interested to know what keyboard/clipboard you use, if it's not google/samsung.

**Comment by yant0** [comment]
Unfortunately, i haven't seen any gallery apps that can copy images to clipboard. I will let you know if i found something.

As for keyboards, i use [FlorisBoard](https://github.com/florisboard/florisboard), `AOSP keyboard`, and occasionally use `Gboard`. In FlorisBoard, i've tried to copy image through Chrome and it shows the thumbnail and paste properly. I've never tried Samsung's keyboard before.
