### ISSUE TITLE
Accrescent version missing in the wiki list

### ISSUE THREAD

**Issue by DavidMndz** [deckerst/aves#537]
I checked the wiki for the differences between the versions available when the app is installed from the different stores available, but I was not able to get the version details for the Accrescent store.

I would like to understand if that one is the same version than the F-Droid one and if not, which are the differences. I thing it would be great add Accrescent in the comparation between versions as well.

Thanks.

**Comment by deckerst** [comment]
Sure, I'll add it to the wiki tomorrow. But to answer your question, it's the `play` version.

**Comment by DavidMndz** [comment]
Thanks for the quick update.

A couple of more questions if you do not mind.

Do you plan to add a "free" version to Accrescent?
What is "Bundled shaders" for? I saw them in the wiki for the Play version but I am not sure what is it for.

Thanks again.

**Comment by deckerst** [comment]
> Do you plan to add a "free" version to Accrescent?

Nope.

> What is "Bundled shaders" for?

Normally, when users install and launch the app for the very first time, shaders are compiled as needed (for animations, transparency, etc.) and it can look janky because performances take a hit. By precompiling and bundling shaders, the first launch is smoother.

If the shaders I bundled are incompatible with the user's device, it shouldn't matter, in theory. In practice, it can prevent launch in rare edge cases. Also, bundled shaders raise issues for people using hardened memory allocation for extra security (with GrapheneOS, if my memory serves me right).

So, I've decided to keep the bundled shaders for the mainstream versions, as they help most of the time. But I didn't bundle them for the niche versions. In the long term, bundle shaders should no longer be necessary as the framework I'm using (Flutter) is working on a new system that does not need them.

**Comment by deckerst** [comment]
I suppose it works for you with hardened memory allocation specifically because I do not bundle shaders with the version of Aves you are using.

For versions that have bundled shaders, I regenerate them every time I upgrade the Flutter version used by Aves.

**Comment by deckerst** [comment]
Interesting! Then i suppose Flutter changed the way shaders are used, but i actually don't know. In any case, i will let the versions as they are (with or without shaders).

**Comment by DavidMndz** [comment]
In my case, the free version is working perfectly in GrapheneOS with hardened memory allocation enabled.

Thanks again for the details and clarifications.

**Comment by deckerst** [comment]
No specific reason. By default nothing is planned, so there was no plan to add another version of the app to that store.

Aves originally got to be on Accrescent because its author reached out to me. He seemed nice and the project serious enough so I agreed. As simple as that.

**Comment by deckerst** [comment]
I'm not against it. Just wondering what Accrescent policy is regarding having multiple versions. If that's confusing... Anyway, I'll take a look.
