### ISSUE TITLE
Missing places

### ISSUE THREAD

**Issue by BenVB1** [deckerst/aves#549]
A lot of places are not being picked up correctly. For example Bournemouth, a large coastal town, is simply listed as Great Britain > England. My home town is among them. Yet the villages around my town are listed correctly individually as Great Britain > England > placename.

**Comment by deckerst** [comment]
I'm aware of this, but i don't have a consistent solution to offer at the moment.

The addresses come from the geocoder service provided by your device (usually from Google mobile Services). And these addresses are split into fields (like "country", "administrative area", etc.) but it's not an exact science, and it changes sometimes with time, with locale...

Especially for countries having states in them (like GB with England, but same goes with Australia and others), what should be the "place" is not easy to extract from these addresses in a consistent way.

A solution that may generally improve things for villages in England may make things worse for, say, large capitals like Tokyo.

**Comment by deckerst** [comment]
Could you send me an example image of each location and your expected place for each? (You can attach them here, or send them by email)

**Comment by BenVB1** [comment]
Hi.
Attached are 4 examples. I've renamed the files to reflect the correct locations. Hope this helps.

Regards, Ben

**Comment by deckerst** [comment]
I don't see the links/attachments. Am i missing something?

**Comment by BenVB1** [comment]
Well, I first tried email but was rejected by server for being over the
size limit. I then tried on the site. I added the files & thought it odd it
didn't show any confirmation.

Ah well, I'll try again with seperate emails...

**Comment by BenVB1** [comment]
Hi Thibault.
Ermm, I sent 4 images related to this about a week ago?

Regards, Ben

**Comment by BenVB1** [comment]
Ah, I did send them to the notification email. Ok, let's try web interface...
![Bournemouth](https://user-images.githubusercontent.com/127518925/226645753-f6f98a0b-bcfb-4485-9854-26063cbd2e8a.jpg)

**Comment by BenVB1** [comment]
![Isle_of_Wight](https://user-images.githubusercontent.com/127518925/226646240-d339ad84-7507-4dc5-bce1-adebbad40b26.jpg)

**Comment by BenVB1** [comment]
![Boscombe](https://user-images.githubusercontent.com/127518925/226646306-28856e3d-17da-453a-979f-776133116de8.jpg)

**Comment by BenVB1** [comment]
![Aylesbury](https://user-images.githubusercontent.com/127518925/226646379-4f34643b-c5f0-4961-ad12-71b72e0f11c0.jpg)

**Comment by BenVB1** [comment]
Looks like they're there now?

**Comment by deckerst** [comment]
Yes, thank you. So for these you expect to see "Aylesbury" and "Bournemouth" as places, as well as "England" as state, right? I'll check how their addresses are returned by the Geocoder service.

**Comment by BenVB1** [comment]
Hi.

1. Boscombe is a suburb of Bournemouth so, I would expect to see
Bournemouth as a place. Drilling down further is a bit overkill I think.

2. I would expect Totland Bay here as Isle of Wight is more a county.

3. Again, Bournemouth.

4. Aylesbury, as Vale Park is a large park, likened to a suburb. Aylesbury
is a town in the county of Buckinghamshire.

Small suburbs/parks/venues etc usualy go well as an inclusion in metadate
title/description.

Regards, Ben

**Comment by deckerst** [comment]
Thanks for the explanation.

Most of your expected places are actually impossible to retrieve, because `Bournemouth` and `Aylesbury` appear in the address line, but they do not appear in the segmented fields returned by the geocoder service.

latitude | longitude | addressLine | adminArea | countryCode | countryName | featureName | locality | postalCode | subAdminArea | subLocality | subThoroughfare | thoroughfare
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
50.719925 | -1.858047 | 83 Grove Rd, Boscombe, Bournemouth BH1 3AH, UK | England | GB | United Kingdom | 83 | null | BH1 3AH | Dorset | Boscombe | 83 | Grove Road
50.667619 | -1.566021 | Whitecliff House, Totland Bay PO39 0JD, UK | England | GB | United Kingdom | Totland Bay | null | PO39 0JD | Isle of Wight | null | null | null
50.71976 | -1.846261 | 2540 Undercliff Dr, Boscombe, Bournemouth BH5 1BN, UK | England | GB | United Kingdom | 2540 | null | BH5 1BN | Dorset | Boscombe | 2540 | Undercliff Drive
51.816709 | -0.805296 | Vale Park, Park St, Aylesbury HP20 1DX, UK | England | GB | United Kingdom | Vale Park | null | HP20 1DX | Buckinghamshire | null | null | Park Street

I tried to find the best strategy to get the most sensible results given what's possible, and for your samples I get:
1. Boscombe
2. Totland Bay
3. Boscombe
4. Vale Park

<img width=250 src="https://user-images.githubusercontent.com/13898333/226859765-9bd3dad4-ec7a-4a60-960a-955a48c1c0b7.png"/>

**Comment by BenVB1** [comment]
Hi Thibault.
Wow, that is a mess! Not surprised it's difficult to make sense of. Still,
your best strategy does at least break it down better, rather than most
being lumped into one vast area.

Thank you for taking the time to look into this for me - much appreciated.

Regards, Ben

**Comment by BenVB1** [comment]
Hi Thibault.
Just a quick note to say thank you for sorting the location issue. That
looks a lot better now, sorting it into more meaningful locations.

Regards, Ben
