### ISSUE TITLE
AV1 video codec support

### ISSUE THREAD

**Issue by Wjxfi** [deckerst/aves#555]

**Comment by mherrmann3** [comment]
I'm eagerly waiting for this support. But I wonder: why not simply using the AV1 codec shipped with Android 10+? The AOSP Gallery plays AV1 without problems.

Yes, there is no camera app that produces AV1 video streams. BUT: That doesn't mean that AV1 doesn't reside on phones already.
One use case: Videos recorded by a camera app, even in HEVC/h265, are typically larger than they need to be[^1]; re-encoding them on a PC/GPU with better compression efficiency can save a lot of storage (typically at least 85% w/o significant quality loss). And why not re-encoding them already with AV1? Benefit:
1. It's the next-gen video codec with even better compression efficiency[^2].
2. Unlike AVC/h264 and HEVC, AV1 is open and royalty-free; therefore it is more widely supported[^3]. So the same video file could be uploaded to a cloud and played/streamed directly from there via web interface.

[^1]: Due a trade-off between performance and compression efficiency: using a fast preset guarantees saving the file in reasonable time, but produces poorly compressed (larger) files.
[^2]: [en.wikipedia.org/wiki/AV1#Quality_and_efficiency](https://en.wikipedia.org/wiki/AV1#Quality_and_efficiency)
[^3]: Such as Firefox, Chromium, Opera, Vivaldi, and several hardware manufacturers. ([en.wikipedia.org/wiki/AV1#Adoption](https://en.wikipedia.org/wiki/AV1#Adoption) & [en.wikipedia.org/wiki/HTML5_video#Browser_support](https://en.wikipedia.org/wiki/HTML5_video#Browser_support)). The only party pooper seems macOS/iOS, but who cares 😜

**Comment by mherrmann3** [comment]
I just learned that Aves [uses FFmpeg](https://github.com/deckerst/aves/wiki/Support%3A-Video) for video playback. Any chance to update it to a more recent version and/or compile it with AV1 support? [FFmpeg v4.0](https://www.ffmpeg.org/index.html#pr4.0), the currently used version in Aves, in principle supports AV1 decoding, but only if compiled with `--enable-libaom`; not sure if this is possible [on Android](https://trac.ffmpeg.org/wiki/CompilationGuide/Android). More recent FFmpeg versions extended AV1 support, incl. HW-based decoding.

**Comment by deckerst** [comment]
Aves indirectly uses FFmpeg through ijkplayer. That player customizes FFmpeg source, but it relies on an old version of it, and the player seems unmaintained. This is problematic but I don't have the expertise to bring it to the latest FFmpeg.

As for AV1, maybe I can add `libaom` to the [FFmpeg config I use](https://github.com/deckerst/ijkplayer-befovy/blob/aves/config/module.sh).

**Comment by mherrmann3** [comment]
Worth a try! Although certainly not the fastest decoder, but perhaps better than not playing AV1 at all 😉 

Just an idea[^1]: how about switching the media engine? The following could be viable alternatives[^2] (perhaps more up-to-date, easier to maintain, and feature-rich):
- [MediaLibrary](https://developer.android.com/guide/topics/media/mediaplayer); example app: [Fermata Media Player](https://github.com/AndreyPavlenko/Fermata)
- [Media3](https://github.com/androidx/media) (related to [ExoPlayer](https://github.com/google/ExoPlayer)); example apps: [Just (Video) Player](https://github.com/moneytoo/Player), [Next Player](https://github.com/anilbeesetti/nextplayer), Fermata Media Player
- [libmpv](https://github.com/mpv-player/mpv) (also based on FFmpeg); example app: [mpv for Android](https://github.com/mpv-android/mpv-android)



[^1]: I have no clue about the effort to switch and I assume it's easier said than done.
[^2]: source: https://github.com/moneytoo/Player#other-open-source-android-video-players

**Comment by deckerst** [comment]
Yes, I've considered changing the engine: https://github.com/deckerst/aves/wiki/Review:-Android-&-Flutter-packages#video

Media3/ExoPlayer is popular but it is not as flexible as FFmpeg to include whatever codec I need. In particular, I need AVI, M2TS, and some others. I believe someone recently worked on AVI support for ExoPlayer, but in any case it's limiting.

VLC is great. The main drawback is that it bundles everything so the library is large. If I didn't care about app size, I would probably switch to that one.

As for MPV, it seems nice but I haven't tried it yet. Is there some Flutter plugin for it?

**Comment by mherrmann3** [comment]
Oh, I missed your detailed review! Great! And very interesting to read your opinion and further info.

Regarding interfacing mpv with flutter, I found this related discussion: https://github.com/mpv-player/mpv/issues/7373. So there seems hope:
* https://github.com/alexmercerind/media_kit (formerly 'libmpv.dart'); very promising
* https://pub.dev/packages/libmpv

I also found [mpv_dart](https://github.com/KRTirtho/mpv_dart) (see also [flutterawesome.com/mpv-players-json-ipc-binding-for-dart](https://flutterawesome.com/mpv-players-json-ipc-binding-for-dart)).

Not sure if these possibilities could work / is what you need.

**Comment by deckerst** [comment]
First impressions after integrating `media_kit` in Aves.

The good:
- improved seek accuracy,
- improved looping transition,
- improved speed selection,
- HDR support,
- AV1 support (surprised?),
- some corrupted videos become playable (e.g. mp4 with inconsistent duration in their metadata).

The bad:
- [Android content URIs are not supported](https://github.com/alexmercerind/media_kit/issues/252),
- [capturing frames is not supported](https://github.com/alexmercerind/media_kit/issues/192),
- subtitle rendering is handled by the player: this is a good thing overall (notably for fancy SSA/ASS styled subtitles), but styling settings are not exposed, and more importantly non-latin text renders as tofu (i.e. subtitles in Arabic, Greek, Chinese, Korean, etc. are unreadable). Maybe it's possible to provide a universal font to avoid tofu, and maybe it's possible to fork the package to expose subtitle settings, but I need to try this out.
- some corrupted videos become unplayable (e.g. some badly encoded old MKV I had).

**Comment by Quackdoc** [comment]
would it be possible for aves to use media_kit as a fallback for images too? if that's the case it could serve as a platform to support images that typically wouldn't work without android support.

IE avif images on versions too old, it likely wouldn't be too hard to add support for jpegxl either.  currently using the media_kit test application to load images, including AVIF images works fine. if this is something that aves can do I can work on adding JXL into media_kit. it would be very nice to have since apple is now supporting jxl and avif images are already getting served by google to some people so the number of avif images floating about is not small.

**Comment by alexmercerind** [comment]
I like this application & I'm ready to work closely if you want.

Be assured that mpv/libmpv is extremely performant & stable. You can retrieve metadata & other video/audio parameters in libmpv as-well. Hopefully; there is a plan to provide a custom events API. Internally, I have a package called `package:media_kit_tag_reader`; which I use (not public yet).

**Comment by alexmercerind** [comment]
The bundle size greatly relies on the chosen FFmpeg codec(s). An application of size under 30 MB is considered good AFAIK.

**Comment by deckerst** [comment]
@alexmercerind thanks. Your package is nice and I believe that in the end I'll switch to it. For me the major hurdles at the moment are https://github.com/alexmercerind/media_kit/issues/255 and  https://github.com/alexmercerind/media_kit/issues/192.

> You can retrieve metadata & other video/audio parameters in libmpv as-well.

Just to be clear, this is not exposed yet in the API of media_kit, right?

> The bundle size greatly relies on the chosen FFmpeg codec(s). An application of size under 30 MB is considered good AFAIK.

True, and personally I'm fine with larger packages, but one of the current distribution channel for Aves is IzzyOnDroid, and they do not accept packages larger than ~30 MB.

**Comment by alexmercerind** [comment]
So I've been catching up on your list slowly :)

The upcoming update for package:media_kit will ship major improvements ("actual 1.0.0").
Android support wasn't much optimized before & now I've given it a lot of time.

And... I've covered it all I suppose (yet to release). You can try the `main` branch.

- The OpenSL ES limit, crash & other performance issues have been addressed.
  We (I & other testers) can't reproduce a single crash. Very stable.
- The performance has been improved by upgrading to FFmpeg 6.0, where direct mediacodec works very-stable.
- The [`video-out-params` has been exposed](https://github.com/alexmercerind/media_kit/pull/276).
- The subtitle rendering has also been improved.
  - Now two types of subtitle rendering is offered:
    - Flutter rendered (default)
    - [libass](https://github.com/libass/libass) rendered
  - You can [easily switch by passing `libass` argument](https://github.com/alexmercerind/media_kit/blob/6d0f0401b8d87596a6167fd629912cff92003edc/media_kit/lib/src/player/platform_player.dart#L401-L411).
    - I & other testers have used it.
  - Flutter rendered subtitles also provide good styling options: [docs](https://github.com/alexmercerind/media_kit#customize-subtitles)
- A [new easy-to-use `screenshot` method has been added](https://github.com/alexmercerind/media_kit#capture-screenshot).
- Lastly, the **size of the library has been reduced to half!**
  - A lot of redundant decoders/demuxers have been stripped.
  - The size of our test application went from 16.5 MB to 12.4 MB (4.2 MB less); rest is due to Flutter itself.
- The support for content:// URIs was already added in last update.
  
Thanks!

**Comment by deckerst** [comment]
Great! Thanks a lot for addressing all of this. I'll try and test it as soon as I can.

Quick question about the Flutter subtitle rendering: is it only for rendering by the player, or do we get a stream of subtitle events so the consumer app can render it? I'm asking because I currently render subtitles out of the video player widget, so I need the stream for that (and advanced styling).
<img width="250" src="https://github.com/deckerst/aves/assets/13898333/92241a0e-0895-4141-b76b-2d5d2a5350f7"/>

**Comment by alexmercerind** [comment]
You can listen to `Stream<List<String>>` inside `Player.stream.subtitle` for custom rendering purposes.

We also have [some styling options available by default](https://github.com/alexmercerind/media_kit#customize-subtitles).

<hr>

Let us know if any issues are found related to stability or etc.

**Comment by deckerst** [comment]
@alexmercerind follow up in #678, dedicated to integrating `media_kit`.
