### ISSUE TITLE
Add option to view hidden files

### ISSUE THREAD

**Issue by CrazyBytesVE** [deckerst/aves#574]
Hello. Your app is great. I would like to ask you if it is possible to add some quick option to "momentarily" view hidden files, in order to, for example, track images from Whatsapp or Telegram and delete them. You can add it to the free version so you don't have problems with the Play Store version.

**Comment by deckerst** [comment]
I don't intend to provide this. Besides technological and permission issues, I disagree with the spirit of the feature. If apps place files in hidden folders, or if they place a ".nomedia" file to explicitly specify that these files should not appear along other regular media, I respect that. It's the responsibility of these apps to manage these files in sensible ways.

**Comment by cyberia-ng** [comment]
Hi, I have a use case for this feature which might change your decision on this:

I sync my photos directory using [Syncthing](https://syncthing.net/), and I have a hidden directory in there (called ".private") so that it is respected by my *nix boxes. (I also have it set as a hidden directory in Windows, which I believe uses NTFS metadata so is not relevant here.)

I would like to set this as a hidden album within Aves, but in order to do so Aves needs to recognise it in the first place.

**Comment by deckerst** [comment]
Sure, but it's not *only* about my opinion on the matter, there are technical restrictions due to the fact Aves is a gallery app and not a general file manager app. Cf wiki: [Can Aves display media inside hidden folders?](https://github.com/deckerst/aves/wiki/FAQ#can-aves-display-media-inside-hidden-folders)

**Comment by cyberia-ng** [comment]
Ah understood. I guess Simple Gallery gets around this by using more general file management permissions.

**Comment by deckerst** [comment]
Yes, I suppose they use the "All file access" permission. F-Droid allows it for any app, but the Play Store is ironically more privacy conscious about this and requires apps to justify the need for such a permission. According to their policy, gallery apps should use media related permissions instead.
