### ISSUE TITLE
Fast Pixelize function

### ISSUE THREAD

**Issue by albotroz** [deckerst/aves#575]
**Is your feature request related to a problem? Please describe.**
It would be great if it was possible to censor images without additional apps.

**Describe the solution you'd like**
Sections of the image either pixelate or black out - without people being able to recover it.

Thanks for your work and app.

**Comment by deckerst** [comment]
I recently checked the most popular free photo editors (cf [wiki](https://github.com/deckerst/aves/wiki/Review:-Photo-editors)), and obfuscation (by pixelating or blurring) is surprisingly rare. I only found it in the specialized app `PrivacyBlur`. Do you know of others?

As for your request, I'll close this issue because I consider this feature part of that issue:
- #17 

Feel free to upvote/subscribe to that issue.

**Comment by albotroz** [comment]
Unfortunately, I don't know of any lightweight (not bloatware) FOSS apps.

LineageOS 20, however, has a built-in simple app called "Markup" that lets you paint over parts of the image - just as if you were painting over it with Windows Paint. I'll use that for now.

**Comment by deckerst** [comment]
It's probably not to your liking (because it's bloated and not open-source) but B612 has an interesting brush variant that can pixellize the painted area.

As for Markup, i believe it's `com.google.android.markup` and was extracted from some Android Pie source. Minimalist but works well indeed.
