### ISSUE TITLE
Add full brightness option for when viewing thumbnails

### ISSUE THREAD

**Issue by petazonk** [deckerst/aves#612]
I can't see the thumbnails clearly unless the brightness is on full.

It would be good if there was similar option for thumbnails as there is for full screen view. That is, full brightness while viewing thumbnails.

An alternative is to manually turn the brightness up.

**Comment by deckerst** [comment]
So it would be full brightness everywhere, for thumbnails and full screen? It seems the alternative you pointed, adjusting the brightness at the OS level, makes more sense in this case.

**Comment by petazonk** [comment]
Well not really in that photos look better at full brightness where as text
is too bright then. I think if full screen photos look better brighter then
why not thumbnails? Having to turn your phone to full brightness, manually,
every time you open Aves would be annoying I think.

**Comment by petazonk** [comment]
Oh, I forgot to mention, I sometimes turn mosaic thumbnail size all the way up and then scroll through the thumbnails as a way of viewing photos. Having full screen brightness here also helps. I like this way of viewing photos sometimes, as it is like looking at a webpage where you can slowly scroll down for each photo.

**Comment by deckerst** [comment]
I'm not fully convinced, but actually the cost of implementing it is very low, so why not. I'll probably move the existing "maximum brightness" toggle and make it a choice in `never` / `always` / `viewer only`.

**Comment by JimW1at** [comment]
Would it be a good idea to have custom brightness instead of maximum brightness because maximum brightness hurt the eyes, especiallly at night. 

Phones with high nits of brightness i.e. 1300 nits would also benefit from custom brightness option.

**Comment by deckerst** [comment]
@JimW1at why not simply rely on the OS adaptive brightness then? It knows what's best for the current luminosity and display properties.

**Comment by JimW1at** [comment]
> @JimW1at why not simply rely on the OS adaptive brightness then? It knows what's best for the current luminosity and display properties.

Yes that is true, but a custom brightness option would be a  better alternative because it will allow me set 600 nits as default instead of 1300 nits. The OS adaptive one always mess up brightness at night or day. I think this app will benefit from custom brightness also this is a gallery app viewing pictures and videos are its main purpose and having custom brightness option will further enhance user experience in my opinion.

Btw, is this option complex/difficult to implement , asking this because i am not a developer :) 

Just want to know. Thanks anyway.

**Comment by deckerst** [comment]
You probably won't like my answer, but here it is: it is not difficult to implement, but I think the use case does not justify making the settings fiddlier. Incrementally, each little bit of fiddliness does not look like much, but in aggregate they make the app bloated. The settings are already not as lean as I'd like them to be.

**Comment by JimW1at** [comment]
> You probably won't like my answer, but here it is: it is not difficult to implement, but I think the use case does not justify making the settings fiddlier. Incrementally, each little bit of fiddliness does not look like much, but in aggregate they make the app bloated. The settings are already not as lean as I'd like them to be.

Ok. I understand your point. You do not want settings page to get bloated with extra options.But can we get these extra options with something like an advanced settings option which will be off by default so that it will ruin user experience of the app. Users who would want these experimental settings can simply turn on advanced setting option to get those options.

This is only my idea you are free to ignore.
