### ISSUE TITLE
PiP mode for images

### ISSUE THREAD

**Issue by Tanmandal** [deckerst/aves#616]
Can you please add the feature of viewing an image in pip mode
Instead of automatically switching to pip mode like in case of videos add a button which would open the image in pip mode

The only app which has this feature is Anything to PiP , but it is not open source

**Comment by deckerst** [comment]
PiP is useful to let something play in a corner while doing something else, so I don't understand why you would want a static image in PiP. Could you explain why you need this?

**Comment by Tanmandal** [comment]
I am a student and it's useful when I am jotting down points from online class screenshots on notesapp
The pip window on latest versions of android is resizable so I can just resize it to make small while I write and again when I need to read I can just make it large to see this reduces the need for switching between apps 
I tried using the android split screen feature but it does not work very while typing as space where I am typing is not quiet visible

**Comment by deckerst** [comment]
On my device (a Samsung from 2019, running Android 12), any app can be switched to a split screen view or a pop-up view. The pop-up view is a resizable window. Don't you have this? It seems exactly what you need, and I designed Aves to behave gracefully when being used in a resizable pop-up view.

I'll close this issue, because I don't think PiP is appropriate here. A resizable pop-up view is what you want and that can be handled by your launcher/OS.
