### ISSUE TITLE
Change Select from menu to Select All from menu or add Select All as a second menu option

### ISSUE THREAD

**Issue by petazonk** [deckerst/aves#630]
It seems inefficient to use the Select from menu option when I can simply long press a photo to select.

I think it would be more efficient to have a Select All from the menu option instead of just a Select.

The alternative is to first go Menu > Select and then repeat this with Menu > Select All. This seems inefficient as I can get the first Select option by long pressing.

**Comment by deckerst** [comment]
There is some redundancy here and there because users are not as curious, clever or competent as you might think. For example, in the past I had removed the "Info" action from the viewer menu because you could access the `Info` page with just a swipe. But then multiple users failed to find that Info page by themselves, so I reinstated the "Info" action. If I remove the "Select" menu option, trust me, some users will ask me how to select...

**Comment by petazonk** [comment]
Yes I understand your thinking but if it was changed to select all they
would still find it?
