### ISSUE TITLE
Add dynamic date tag to allow easy viewing of photos before and after date of current photo

### ISSUE THREAD

**Issue by petazonk** [deckerst/aves#631]
It is currently difficult to see photos either side of the current photo when you have that photo selected from a tag. For example, let's say I'm viewing all tags of John Smith but I now want to see photos before and after this photo. I can't see how I can see the prior photo to this the current photo if it is not John Smith.

I think it would be good if there was a dynamic tag generated, for the same day that the current photo was taken, and thus I could click on this dynamic tag (say 1 Jan 2023) and then all photos take on that day would be displayed. I could then see the photos before and after the tagged photo I was looking at.

The other way or reaching photos, before and after a displayed tagged photo, is by looking at the date that the photo was taken, and then searching for that day of photos. However, I haven't found a way of easily finding photos taken on say the 1-JAN-2023 as there doesn't appear to be a search date for an exact day?

The date of the photo is displayed when looking at photos so maybe this date could by hyperlinked to take you a group of photos that were taken on that date. This could also be extended to allowing a user to click on the location displayed so as to show you all photos from that location as well.

**Comment by deckerst** [comment]
> there doesn't appear to be a search date for an exact day?

True, it's not directly accessible. The closest thing currently available is via the `Stats` page. The Stats page shows a graph by time, and if you tap on nodes in that graph, you get a filter that appears just below. The graph is contextual so that if the current collection spreads over years, it will show a year filter. For months a month filter, and for days a day filter.

<img width="250" src="https://user-images.githubusercontent.com/13898333/235770993-d1c9580d-dbe7-49c6-ad2a-3f2789251cab.png">

> This could also be extended to allowing a user to click on the location displayed so as to show you all photos from that location as well.

Do you know you can tap on the `country` and `place` filters below the small map in the `Info` page?

<img width="250" src="https://user-images.githubusercontent.com/13898333/235771375-52b57c19-be3a-479c-9364-0275789ff8aa.png">

But to get back to your request, I'll think about adding a similar filter for the day in the `Info` page.
