### ISSUE TITLE
App crashes when in viewer

### ISSUE THREAD

**Issue by Lorestan00** [deckerst/aves#634]
**Describe the bug**
When moving from image to image in the viewer it crashes (see photos) 

**To Reproduce**
1. Click on any image and either swipe or tap to move to new image 
2. After 3 or 4 images either there is an image saying 'oops' or the app crashes

Thumbnails appear correctly. It's only when opening some images they show 'oops' and then crashes though not always

I've cleared cache and data and tried to use the app with stock settings but to no avail

**Expected behavior**
You would hope it woudl move from image to image without issue

**Screenshots**
![Screenshot_20230506_110044_Device care.jpg](https://user-images.githubusercontent.com/81394097/236618041-d6ed9245-59a2-463a-8d15-394c9db249e8.jpg)

![Screenshot_20230506_110024_Aves.jpg](https://user-images.githubusercontent.com/81394097/236618048-d4bd487c-3b6f-4627-aa57-49fa57ae938e.jpg)

**System information and logs:**

[aves-logs-20230506_111329.txt](https://github.com/deckerst/aves/files/11412098/aves-logs-20230506_111329.txt)

Package: deckers.thibault.aves
Installer: com.looker.droidify
Aves version: 1.8.6-izzy, build 9701
Flutter: stable 3.7.12
Android version: 13, API 33
Android build: TP1A.220624.014.F936BXXU2CWCC
Device: samsung SM-F936B
Geocoder: ready
Mobile services: ready
System locales: en_GB
Storage volumes: /storage/emulated/0/
Storage grants: 
Error reporting: false

**Additional context**

**Comment by deckerst** [comment]
Thanks for the report. I see some fatal errors in the logs, but they seem to come out of nowhere.

If you open the app and just wait, would it crash by itself? I'm asking because maybe the background cataloging is using/corrupting memory.

Does it happen with particular files you can identify and share with me?

Does it happen if you only browse through images (and not videos)?

Does it happen if you only browse through basic images taken with your camera (nothing fancy, downloaded or transferred from outside)?

I've noticed you use a Samsung Flip. Do you open/close it while the app is running?

**Comment by Lorestan00** [comment]
If I open the app and leave it alone it's fine no crashes

How long should cataloguing take? There are about 10k mainly images.

A couple of files it seems to happen to more frequently but not always. See attached.both were taken with the camera. Interestingly if I scroll through images downloaded from the web which I've saved it doesn't crash.

It appears to be images I've taken which are triggering the crash. I've filtered by video including ones I've recorded and can scroll through with no issue.

Unfortunately it crashes on my galaxy fold 4 on both the main and cover screens.

I've attached a video of how when opening an image which shows 'oops' it does momentarily show thr image. It's of one of the two images I've attached

https://user-images.githubusercontent.com/81394097/236640824-58098521-731b-4369-b726-f3fd23c8cd72.mp4

![20230411_203357 (1)](https://user-images.githubusercontent.com/81394097/236640847-d3871643-bb38-4db3-8068-6f8a3cc7cb42.jpg)
![20230410_204107](https://user-images.githubusercontent.com/81394097/236640850-d3b7ee61-281a-4350-939d-79d9b4196b63.jpg)

**Comment by deckerst** [comment]
> If I open the app and leave it alone it's fine no crashes
> 
> How long should cataloguing take? There are about 10k mainly images.

It's variable, but if you started the app for the first time, the 10k images would be catalogued in the background in a few minutes. After that, when there are just a few new images to catalog, it's done within the app when you open it and it usually takes a few seconds. Some people have in their collection some files that make the cataloguing crash (usually because of a memory error), and that will crash the app is cataloguing is done within the app. Anyway, it doesn't seem to be your case.

> A couple of files it seems to happen to more frequently but not always. See attached.both were taken with the camera. Interestingly if I scroll through images downloaded from the web which I've saved it doesn't crash.
> 
> It appears to be images I've taken which are triggering the crash. I've filtered by video including ones I've recorded and can scroll through with no issue.
> 
> Unfortunately it crashes on my galaxy fold 4 on both the main and cover screens.

Thanks for all the details. At this point I have no idea what the issue could be, but it's useful to know what works.

> I've attached a video of how when opening an image which shows 'oops' it does momentarily show thr image. It's of one of the two images I've attached

If you see the image for a split second like this, it's because the thumbnail is in the cache, but the full image can't be loaded. Sometimes, a file that no longer exists but wasn't properly removed from the system Media Store will behave like that in Aves, because it still has its thumbnail from a previous time.

**Comment by deckerst** [comment]
Do you use a custom rom?

I see you use the `Izzy` version. You could try and install `Aves Libre` (from F-Droid) or `Aves` from the Play Store. `Aves Libre` would install side by side with your current version but `Aves` from the Play Store would replace the one you currently have.

**Comment by Lorestan00** [comment]
I'm not using a custom rom. Samsung one Ui 5.1 based on android 13.

I downloaded it from Droidify which is a material design version of Fdroid, infact I think I downloaded it from fdroid.

So I've just uninstalled and installed the play store version....and it seems fine. I've swiped through 2 dozen photos quickly and no crash and it woudl be caching images in background still. I'll keep you posted if something goes wrong 

Out of interest Is the libre version newer?

**Comment by deckerst** [comment]
On F-Droid (or any client like Droidify) you can find both "Aves" (from IzzyOnDroid's repo) and "Aves Libre" (from the basic F-Droid repo). From your system environment, I know you were using the `izzy` version.

I'm glad to know the `play` version works better for you, but the different versions should not differ when it comes to browsing and decoding images, so there's still a mystery.

You can see the [differences between versions here](https://github.com/deckerst/aves/wiki/App-Versions). All versions are released more or less at the same time, but F-Droid takes a few days to update the `libre` version in their repo.

**Comment by deckerst** [comment]
> So I've just uninstalled and installed the play store version....and it seems fine. I've swiped through 2 dozen photos quickly and no crash and it woudl be caching images in background still. I'll keep you posted if something goes wrong

Still fine? If you want to go the extra mile, you could try the `libre` version and see whether it crashes.

**Comment by Lorestan00** [comment]
> > So I've just uninstalled and installed the play store version....and it seems fine. I've swiped through 2 dozen photos quickly and no crash and it woudl be caching images in background still. I'll keep you posted if something goes wrong
> 
> Still fine? If you want to go the extra mile, you could try the `libre` version and see whether it crashes.

Yep all good thanks.
