### ISSUE TITLE
Request player buttons 

### ISSUE THREAD

**Issue by joefast77** [deckerst/aves#659]
can you please make an option in settings to arrange player buttons in android tv version 🙏🏻
![IMG20230605140337](https://github.com/deckerst/aves/assets/80571759/2d74d30d-cb07-41a5-b583-5ad0d9ef9e97)

**Comment by deckerst** [comment]
I keep it simple for the TV interface, simplifying many menus and features, because of TV interaction constraints. Configuring the buttons on mobile is easy with drag and drop, but it would be tedious with a TV remote.

Could you explain exactly what you hope to achieve?

By the way, for key actions (like "play", "pause", "forward", "backward"), the media buttons on the remote should work.

**Comment by joefast77** [comment]
I really appreciate your work don't mean to make it any harder , while everything works just like you said , but when you press down to seek forward and backward it's in the middle , I just wanted to be able to move them where "info" button is .
but that's ok since it's going to take a lot of work .
