### ISSUE TITLE
GPS Location and Motion Photo icon overlay are too intrusive/big

### ISSUE THREAD

**Issue by petazonk** [deckerst/aves#68]
The overlay icons on the jpg photos are too big and thus intrusive. It would be good if they could be like a quarter of the size, transparent background, and either along the bottom or the top (not the side). Maybe use green coloured location ones and gray or another colour that doesn't stand out as much as white.

**Comment by deckerst** [comment]
I took your suggestion to reduce the size of the icons. This is released in Aves v1.5.2.

The icons are smaller overall, but they will now scale according to your OS preference for font size, so that folks with visual impairment can get sufficiently large icons.

Still from an accessibility perspective, I kept the background and color as they are to have sufficient contrast.

The reason for having icons in a column on the side is simple: some icons come with a text (such as videos with the duration, or bursts with the number of pictures), so horizontal space is saved for these.

Please note that you can hide some of these icons, if the information they provide is not useful to you. You could hide the location icon for example. It's configurable in `Settings` > `Thumbnails`.

**Comment by petazonk** [comment]
Thanks :)

You are constantly improving this which is great.
