### ISSUE TITLE
Rescan Issues

### ISSUE THREAD

**Issue by telrod11** [deckerst/aves#687]
**Describe the bug**
I have a large media library (20k) of videos and pics.   My usual working method is to take pics and videos, then rename in Aves (Thanks!), then I will move them to a nested folder on the SDCard of my Android 12 Samsung device.  This morning while doing this, Aves could not find the 12 photos that I had moved to my SDCard.   Rescan several times did not help.   I cleared the app cache, but still no joy.    Eventually, I uninstalled the app, and then immediately reinstalled and the pics were in the collection, immediately.

**To Reproduce**
1. Move Photos
2. Rescan Media
4. Pics are not in the collection

**Expected behavior**
I don't expect the "migratory" photos to imeediately be seen, but I do expect they can be seen after a rescan

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem. If they are too private for this public space, feel free to [send them by email](mailto:gallery.aves@gmail.com).

**System information and logs:**
Package: deckers.thibault.aves
Installer: com.android.vending
Aves version: 1.8.9-play, build 100
Flutter: stable 3.10.3
Android version: 13, API 33
Android build: TP1A.220624.014.G781WVLU9HWF1
Device: samsung SM-G781W
Geocoder: ready
Mobile services: ready
System locales: en_US
Storage volumes: /storage/emulated/0/, /storage/8834-A006/
Storage grants: 
Error reporting: false
**Additional context**
[aves-logs-20230717_063644.txt](https://github.com/deckerst/aves/files/12068375/aves-logs-20230717_063644.txt)

(System logs are after the reinstall, and the app performing as it should, sorry)

**Comment by deckerst** [comment]
Thanks for reporting.

A few things to clear out first. "Rescan" does not do what you think it does. "Rescan" is only useful when I add some analysis feature to a new Aves release. For example, detecting a new kind of motion photos. In that case rescanning may be necessary for users upgrading to the latest version of Aves, but otherwise users should never need to use it. "Rescan" does not discover new items, it only goes through known items and check their metadata.

Here the problem is that new items are not discovered by Aves. Its item list comes from the Android system Media Store. When the Media Store finds a new item, it tells Aves and Aves can show it to the user. So far, every time users got an issue similar to yours, it was because they created/moved/deleted files with an app/process badly written that sidesteps the Android system Media Store. So the Media Store gets updated late, so Aves gets updated late.

How do you move your files?

**Comment by telrod11** [comment]
Thanks for the reply. I moved the files with a file manager app usually it's one called mixplorer.

I do see what you're saying, but am curious why aves was able to find them on a reinstall?   If its into came from a poorly written system directory command, wouldn't that stay the same after a reinstall?

**Comment by deckerst** [comment]
I think there are other users of the `mixplorer` and `aves` combination and they haven't complained, so maybe there's a real bug on Aves side.

> curious why aves was able to find them on a reinstall? If its into came from a poorly written system directory command, wouldn't that stay the same after a reinstall?

True, but the Media Store eventually catches up. In the past, it was often sluggish and rescanned only on device reboot, but I believe it's more proactive these days. As for Aves reinstall, it *may* be a coincidence, I don't know.

If you can reproduce this issue with a specific move operation with a specific app, I'll try and reproduce it on my device. But otherwise it will be difficult to debug. And if it happens again to you, getting Aves logs *before* reinstalling could help too.

**Comment by telrod11** [comment]
@deckerst

I'd like to revisit this refresh issue again.

Photos moved from internal storage to SDCard refresh immediately with a competitor F-Stop.    I do believe there might be something intrinsically *slow* in the refresh code of Aves, (or is it F-Stop has a more sophisticated refresh ?)

Pics attached
![Screenshot_20230814_082231_F-Stop-2](https://github.com/deckerst/aves/assets/105058921/14cc52fc-8b39-4dac-bd96-c0f03fcbd2ab)
![Screenshot_20230814_082240_Aves](https://github.com/deckerst/aves/assets/105058921/86fe0b8b-e106-4a72-8668-9955848bc835)

**Comment by deckerst** [comment]
As far as I remember, F-Stop requires access to all files (not only photo/video), because they create sidecar metadata files, and they also handle hidden media. In other words, they do not rely on the system Media Store like Aves does, and they would need to scan and monitor all the storage themselves. So they would not suffer from the Media Store update delay.

Aves and F-Stop have different approach. For Aves, I favour collaboration with the system in place by using the Media Store and I respect users privacy by asking for the only required permissions to media. I am well aware of the downsides but I think it's a more ethical approach.

Maybe there is something intrinsically slow with Aves, but F-Stop custom monitoring with all file access is not evidence of that.
