### ISSUE TITLE
Filtering by rating

### ISSUE THREAD

**Issue by noearchimede** [deckerst/aves#689]
I use star ratings extensively to organize my pictures. 
When I look at my photo collection I'd often like to filter out all pictures below a given rating. 
Aves allows doing that, but the only way I found is to click on the search bar, scroll down to the ratings section, long press on a rating, select "filter out", and repeat for every rating I want to exclude (e.g. 1-star, 2-star and 3-star) and then one more time for "Unrated" (in the Metadata section of the search page).

I would love to have an option to filter pictures based on ratings in a quicker and more straightforward way. I can imagine three solutions, but of course there probably are better ones:
 - a direct solution might be something similar to "title filter": a button that shows a small menu where the user can set up a ratings-based filter. Maybe there could be 7 buttons (unrated, rejected, 1, 2, 3, 4, 5) and the user would need to click everything that they want included (e.g. for "any picture with at least 3 stars" they would click "4" and "5"), allowing arbitrary filters such as "exactly 3 stars or unrated".
 - being able to select/deselect (i.e. hide) multiple items in the Search window at once would indirectly solve my issue, by removing the hassle of having to click "search" and scroll down up to 5 times (if one only wants 5 star pictures)
 - having a way of somehow saving combinations of search options under a custom name would also solve it indirectly, by allowing any user to set up 5 ratings-related filters that can be activated with one or two clicks.

Anyways thank you for this awesome app!

**Comment by deckerst** [comment]
Interesting ideas. I'll think about it when i have more time. Your third point is something i want to do eventually (for now you can make a custom shortcut, but that's not as integrated as a custom filter).

In the meantime, it's not a filter but you can sort by rating, which would surface the best/worst.

**Comment by noearchimede** [comment]
I'm looking forward to hearing about your thoughts on this issue eventually!

What are custom shortcuts? How can I set those up?

**Comment by deckerst** [comment]
> a direct solution might be something similar to "title filter": a button that shows a small menu where the user can set up a ratings-based filter. Maybe there could be 7 buttons (unrated, rejected, 1, 2, 3, 4, 5) and the user would need to click everything that they want included (e.g. for "any picture with at least 3 stars" they would click "4" and "5"), allowing arbitrary filters such as "exactly 3 stars or unrated".

I probably won't do this one, because enabling it would require a custom UI, as well as extra actions at the top level of the page menu, which is too visible for a niche need.

> being able to select/deselect (i.e. hide) multiple items in the Search window at once would indirectly solve my issue, by removing the hassle of having to click "search" and scroll down up to 5 times (if one only wants 5 star pictures)

I get what you mean, and it's an interesting proposal for broader use cases, but for you I think we can find a more straightforward solution.

> having a way of somehow saving combinations of search options under a custom name would also solve it indirectly, by allowing any user to set up 5 ratings-related filters that can be activated with one or two clicks.

I like this idea of saving a custom set of filters as a reusable filter (in the drawer, in the search page, etc.) and I'd like to give it a try someday.

For you I have another idea, low-hanging fruit: adding to the long press menu of rating filters a `... or more` and `... or less` filter actions. For example, you go to the search page, you long press on the `4 star` filter, in the pop-up menu you select "4 or more" and that's it! The nice thing with working with the contextual long press menu is that it would work wherever the filter is: the Stats page, the Info page, etc.
