### ISSUE TITLE
Hidden files visibility controls

### ISSUE THREAD

**Issue by texturesplunky** [deckerst/aves#702]
Great app, unbelievably impressive, ty!

Please implement some sorts of different ways to set visible or not of hidden files / folders.

There are some folders that aces just won't let me add manually and won't catalog or display said folders  contents.

Thanks or your amazing work!

**Comment by deckerst** [comment]
> Please implement some sorts of different ways to set visible or not of hidden files / folders.

The concept of "hiding" means different things to different people. In Aves, hiding an album means that items in that album won't be displayed in the app, but it does not hide them for other apps. If you want to hide some items so that they are not visible to any other apps and you can only access them in Aves, you should use vaults (you can create and use them just like you do with albums).

Also, Aves does not display media files that are hidden at the OS level with `.nomedia`. This is intended.

> There are some folders that aces just won't let me add manually and won't catalog or display said folders contents.

I don't understand what you mean. Please rephrase and/or provide examples.

**Comment by texturesplunky** [comment]
__ thanks for your response! its the system level hidden visibility I was wondering about. Why is it intended not to see those hidden files by system?  thank you!

**Comment by deckerst** [comment]
It's down to the permission system. Aves is a gallery app that can access __media files__, and only media files. It's not a generic file manager. And media files that are hidden at the system level are simply not categorized as media by Android. They are not indexed by the Android Media Store and they are not accessible to apps that access only media files (like Aves).

The way around this would be for Aves to request permission to access all files on Android, and I don't want to do that.

**Comment by texturesplunky** [comment]
Wow, that explains everything perfectly. Appreciate the valuable information. Great work!

**Comment by deckerst** [comment]
Duplicate:
- #574
