### ISSUE TITLE
Image histogram

### ISSUE THREAD

**Issue by mherrmann3** [deckerst/aves#706]
For objectively judging the exposure and dynamic range of a photo, an [image histogram](https://en.m.wikipedia.org/wiki/Image_histogram) (of the luminance) would be helpful. 

It could be displayed (configurable in settings):
* in a floating transparent box in some corner, and/or
* in the info view (when swiping up)

**Comment by deckerst** [comment]
Yes, I thought about this in the past and never got to it! For the floating box, do you think it would be too small for an histogram if it was similar in size to the overlaid minimap in the top left corner?

**Comment by mherrmann3** [comment]
Great that you welcome and planned it!

Unfortunately, the minimap overlay doesn't show (although enabled in settings - every other overlay works).

I think a small histogram overlay (e.g., the size of two quick action buttons) is sufficient, because the main purpose of the histogram in a viewer app is to have a rough idea of the location and shape of the luminance distribution (some Camera apps have it too, like [Open Camera](https://sourceforge.net/projects/opencamera)).

**Comment by deckerst** [comment]
> Unfortunately, the minimap overlay doesn't show (although enabled in settings - every other overlay works).

It only appears when zoomed in and the image goes beyond the viewport, like so. 
![Screenshot_20230805_104624_Aves](https://github.com/deckerst/aves/assets/13898333/b9d4f56e-a60b-4466-b841-be5156a8dd94)

If you still don't see it, there's a bug.

**Comment by mherrmann3** [comment]
Ah, sorry, _that_ kind of minimap... Yes, now I see it (I expected a small geographical map with the location pin 😬). Perhaps you could rename the entry in the setting to _"Show mini image map when zoomed"_ (or similar).
\</offtopic>

**Comment by deckerst** [comment]
https://github.com/deckerst/aves/assets/13898333/60ad87ae-7b32-40c3-ab13-cde057188f5d

**Comment by mherrmann3** [comment]
Looks great! Thanks for the fast implementation. I'm looking forward to using it. (I hope you too!)

Will you also allow displaying luminance only (i.e., the brightness of the three colors combined)?

**Comment by mherrmann3** [comment]
Glad that you ask. I love log-scale where it makes sense, but histograms of ordinary photos or videos do not benefit from it. For those, we most likely do not care about highlighting small values (for which log-scale is great at), but the opposite: showing where the mode of the distribution is (i.e., the location of the "mountain peak(s)"). In addition, properly interpreting log-scaled information requires axis ticks & labels. For a linear scale, we can omit them.

**Comment by mherrmann3** [comment]
I finally had a chance to try out this new feature (delayed F-droid compilation). However, I noticed that the histograms (both Luminance and RGB) seem a bit ... weird. I compared them for [the above screenshot](https://github.com/deckerst/aves/issues/706#issuecomment-1666444110) in various other image tools:
![histogram_comparison](https://github.com/deckerst/aves/assets/3447479/f136da55-52e3-4a7b-be0e-d84e6a552344)

The histograms of the other tools are more-or-less consistent (apart some vertical clipping by PS), but Aves does it completely different (although I see some similarity) - but I cannot understand how/what exactly. Perhaps you can?

**Comment by deckerst** [comment]
Haha, i expected that, but i was hoping you would know why ;p

For starters i count the pixels from the fullscreen preview (in other words the image downscaled to fit your screen) which is what is loaded when you open the viewer. I do not count pixels on the original full resolution image, which could yield differences, but it's probably not the key reason.

Next, there may be differences due to gamma correction, color profiles, etc. and I have no expertise in this.

Last, maybe i just didn't understand what an histogram counts and how it bins the counts. Is there an open source tool you use that yield good  histograms?

**Comment by mherrmann3** [comment]
Likewise, I'm also not experienced with histograms of RGB images. Perhaps this could be a helpful starting point:
https://docs.opencv.org/3.4/d8/dbc/tutorial_histogram_calculation.html

Or could it be that the data passed to your histogram function is not what you expect, e.g., only part of the image?

**Comment by moonraver** [comment]
This is the only gallery app with histogram that can be found in any app store. It is a great function for photographers. But I have to confirm that histogram is super-inaccurate. What's more, during viewing my 50 MPix DNG files with histogram the app always crashes. I use Samsung Galaxy S23+. It is a great pity.

**Comment by deckerst** [comment]
Thanks for the feedback. Would you be willing to share this DNG that makes the app crash?

**Comment by moonraver** [comment]
So the problem is viewing some of the images captured with Samsung Galaxy S23+:
- 50 MPix 14bit linear DNG files captured in ExpertRAW app
- 50 Mpix DNG captured in stock Camera app in PRO mode
Strange is that some of the images captured in these 2 apps CAN be read in Aves Libre. Maybe the problem is that some files are too large to view?
I use latest Aves Libre 1.10.2 from F-droid.

Problematic files can be downloaded here:
https://filetransfer.io/data-package/Pr454hIR#link

**Comment by deckerst** [comment]
There was an issue with overlay metadata loading. Please try out [this test build](https://drive.google.com/file/d/1IaQ_yG1fPnF36LxELI2x5dDYoLdOizip/view?usp=sharing) and let me know whether you still experience crashes. The test build is the `play` flavor, but it doesn't matter for testing the DNG loading crash.

Generally, viewing a large DNG could be problematic on Android. Usually for large files, I do not load the whole image in memory, but rather load downsampled versions (when it's zoomed out), or necessary regions only (when it's zoomed in).

But downsampling and region decoding is not supported by the DNG codec on Android. At least that's the case on my device (an S11e running Android 12), so I disabled that feature for DNG.

Additionally, when Aves tries to load an image that wouldn't fit in memory, it gives up (otherwise it would crash the app), so trying to load the whole image for a large DNG is likely to be beyond available memory and Aves wouldn't do it. You would only see the upscaled thumbnail.

**Comment by moonraver** [comment]
Thank you for your build. Now the app doesn't crash but says OOPS on some images that can not be viewed.After restart of the app now it shows very very downsampled picture of "OOPS pictures" in Collection and in the Viewer. 
As an amateur photographer shooting in RAW, when I take a photo I want to check my histogram. But when I edit RAW files in my computer, it is even hard to set the RAW reading profile =1st step in editing RAW. So I was thinking about that inaccurate histogram of DNG files in Aves and I think it is hard for you to show it correctly because in addition there is an embedded JPEG inside RAW with a bit different histogram....so which one to show now? But big thank you at least for any histogram. For photographers it is important to see over and underexposure (left and right side of histogram)

One last thing.... as you mentioned downsampling during low and high zoom, etc.........keep in mind that everytime I capture a photo, I check my histogram and then I check if photo was correctly focused = its sharpness. DNGs are all rendered UNfocused in Android (downsampled because of file size???) and in Samsung gallery too. The only way to check the correct focusing is to shoot RAW +JPEG and then zoom that JPEG in AT LEAST at 100% (1:1) to check sharpness of image. In my case I zoom pictures to their max because I am a landscape photographer and every detail counts. So I my case there is no place for downsampling during zoom in.

Anyway, our mobile phones have 8GB+ of RAM, have the best processors and have problems to read 130 MB file? Isn't this problem of Androd OS? Hardware seems to be fine. And what about Samsung gallery...........Samsung produces photo mobiles with Expert RAW and Camera PRO mode and their Gallery still doesn't have basic thing like HISTOGRAM to check the photos.

**Comment by deckerst** [comment]
> says OOPS on some images that can not be viewed.After restart of the app now it shows very very downsampled picture of "OOPS pictures" in Collection and in the Viewer.

Yes, it can happen when the decoded image cannot fit in allocated memory, as I mentioned.

> inaccurate histogram of DNG files in Aves

It's not only DNG, and I think I know why it is wrong. Currently the histogram is based on a downsampled version and not the original fully decoded pixels. That said, you may be right about the fact that the histogram for DNG would be for the JPEG rendering anyway.

> there is no place for downsampling during zoom in.

When you're at 1:1, Aves does not downsample. It only downsamples when you're zoomed out (for example when opening the viewer and displaying a large image zoomed out to fit the screen).

> have problems to read 130 MB file

A compressed image of 130 MB takes way more than that when fully decoded. Also, Not all the RAM on a device is allocated and available to an app. Anyway, we're not supposed to fully decode such large images, only small regions of the image should be decoded as needed, but codecs don't always support this.

**Comment by deckerst** [comment]
If you feel like like it, you can try this build and confirm histograms are as expected:
https://drive.google.com/file/d/10zxUBQQ8-VwlXriDTa6NpnVmrzv72PEJ/view?usp=sharing

Also, large DNG files should open fine now.

So... you can have accurate histograms of large DNGs, yeah!

**Comment by moonraver** [comment]
I have tested it today and everything seems to be OK until I enable "Show shooting details" and "Show description" at the same time in "Overlay" menu.  Then these 50 MP photos have problems and the app crashes.

**Comment by deckerst** [comment]
@moonraver could you please try [this build](https://drive.google.com/file/d/1sB5Co-3om8LxvUJa-kX7IQfl585orXkn/view?usp=sharing) with your 50 MP raws with all the overlays enabled? It should not crash now.

**Comment by moonraver** [comment]
thanx, I have tested it and everything seems to be all right now........great job. As I take photos almost every 2 days, I can keep testing it and I can give you a feedback if you want in a few days.
