### ISSUE TITLE
Hiding files/albums

### ISSUE THREAD

**Issue by Donkey-Doug** [deckerst/aves#72]
Hiding files or albums does not work as expected. It now works as follows:

- Long pressing on an album and selecting hide from the 3 dots menu hides the images inside the folder, but not the folder itself.
- I tried to hide a path in order to hide an entire album, but the album was simply at the bottom, below all my other albums. My albums were sorted alphabetically.
- I cannot hide individual images.

**Comment by deckerst** [comment]
Before I get to your points, I'd like to make sure we're on the same page: "hide" in Aves means "hiding from the collection shown in Aves", not "hiding from the Android Media Store and the other apps".

> Long pressing on an album and selecting hide from the 3 dots menu hides the images inside the folder, but not the folder itself.

The folder should no longer be displayed in the list of albums or on the search page. If it is, it's a bug. Could you please take a screen recording of what you're describing? If it's too private for public sharing on GitHub, you can always [mail it to me](mailto:gallery.aves@gmail.com).

> I tried to hide a path in order to hide an entire album, but the album was simply at the bottom, below all my other albums. My albums were sorted alphabetically.

Nice find, thanks! It's a bug, I can reproduce it.

> I cannot hide individual images.

Indeed, but I'm conflicted about this:
- hiding individual files by path sounds tedious (going to a file selector for each file) and brittle (renaming or moving it in a file explorer would make it reappear). For folders and their subtrees, hiding by path is fine because you would likely have very few such subtrees (for example hiding the root of your music collection to hide album covers scattered in various folders). But I can't predict how many individual files users want to hide.
- the hiding feature is an Aves setting, not something intrinsic to the files, so I don't want to encourage users to spend time and energy doing "hiding management". They wouldn't benefit from this in other apps, or when moving their collection somewhere else.

Rather, I'd leverage tagging for this purpose. Users could tag the files they want to hide with some XMP tag, and then hide that tag. It is a more flexible and scalable way to go about it. These XMP tags stay within the files, so you would benefit from them in other software that understands XMP.

XMP tagging is high priority for me, it's literally my #1 issue. So I hope to get it done in the near future.

**Comment by deckerst** [comment]
@Donkey-Doug I fixed the bug raised in your 2nd point. For your 1st point, I can't reproduce what you describe, so I need more info or a repro video, as I suggested. Shall I close this issue?

**Comment by Donkey-Doug** [comment]
I will make a video soon. If you close this issue, I can open a new one with only the 1st point. Do whatever you prefer.

**Comment by Donkey-Doug** [comment]
Actually I cannot produce this error anymore. Maybe I got confused or it could have been the result of the 2nd point.
