### ISSUE TITLE
Slow image loading

### ISSUE THREAD

**Issue by Donkey-Doug** [deckerst/aves#79]
I transfered a folder with many images from my pc to the internal storage of my device.

Simple gallery pro detected all images almost instantly.
Aves spend a few minutes loading the images.

**Comment by deckerst** [comment]
They do not appear at all for several minutes, or they appear but cataloguing/locating takes several minutes?

They should appear soon after the Media Store detects them. Otherwise it's a bug.

**Comment by Donkey-Doug** [comment]
Cataloguing/locating takes several minutes.

**Comment by deckerst** [comment]
Ah then, it's normal. Well, "locating" especially because it's reverse-geolocating all the pictures that have coordinates. Usually that involves a Google Play service and online communication. The app is usable even without this step, but you don't get to search by "country" and "place".

Given that Simple gallery pro basically just lists the Media Store content without extra effort to detect file properties and mitigate the Media Store limitations, the comparison does not make sense.

That said, some people are confused by the fact that this background analysis done by Aves is shown in the app bar. They think leaving the app will break or discard the analysis, etc. I will change the way it's presented to look like a service decoupled from the app itself. I'll also make the "locating" pass optional.

**Comment by Donkey-Doug** [comment]
Forgot to add: I think the "locating" stopped every time I closed the app, which means it has to start over again several times. This resulted in making it feel even longer.
