### ISSUE TITLE
Design Updates: Logo, Borders, BottomBar

### ISSUE THREAD

**Issue by eusi** [deckerst/aves#798]
Since the original Google Photos app is going a strange way (more or less force people to go with Google Cloud services to backup their photos by adding annoying things that you "inform" you to go to eventually), I was looking for an alternative. Your feature set looks pretty awesome! I really like it!

Since I am a GUI software engineer and UX expert I would love to see three updates to love your gallery forever ;-) 

1. Bottom Bar, it is really helpful, however nowadays the Material Design switched from a "floating bar" to a bottom sticky one (that could also move out once the user slides up/down of course) for some good reasons (e.g. looks better/more clean, not cluttered, easier to focus). See image below (point 2).

2. I like the borders, but they are not that modern anymore in the UI. Someone else mentioned already in #754 that it would be nice to do some GUI tweaks here for everyone. But you are right, if you give the user such settings, this would break a lot of things. What do you think about reducing the thickness of the borders for all items in e.g. the album to the same thickness as the top- or bottom-bar (those gray borders have a good thickness). In addition you could provide an alternative layout (user could change from border-layout to no-border-layout). No border layout could look like the one in the image below.

![3](https://github.com/deckerst/aves/assets/5718902/d5804b80-5f42-4dc6-ba99-76999840d521)

3. Logo, actually I have not checked what's the purpose and background of the logo, but I guess I would remove the black borders (and maybe add a small 3d effect). Just to be more Material and 202X like ;-) A quick 5min draft:
![1](https://github.com/deckerst/aves/assets/5718902/56e3b9a8-c687-405c-b104-eab113f4b288)
![2](https://github.com/deckerst/aves/assets/5718902/49d1e6ab-9bbb-430a-8f7d-051fcc00fdd6)
To be honest, now I also recognize the shape even better! What do you think?

Thanks for your efforts!

**Comment by deckerst** [comment]
Thanks for your interest in this topic!

However, I'm unlikely to address most design suggestions (including yours) because they generally boil down to 2 criteria: fashion and personal taste. I've seen enough design cycles across the years, so the fact that Google released yet another version of Material is not impressing me. I may include parts of it (fonts, toggle controls, etc.) but I'm not trying to follow their look.

As for your specific points:
1) I personally don't like the opaque top/bottom bar they use in Google Photos, and I prefer the full screen continuous look currently in use in Aves.
2) I don't think the borderless image-text-image sandwich they use is great either, but more importantly the (potentially colourful) thick borders in Aves have meaning: they indicate filters. You can for example see the transition when tapping an album as the filter goes to the top of the Collection page. Filters are found on many pages (search, info, map, countries, tags, etc.) and this distinctive border unites them.
3) The logo could be improved, sure, but for now I still prefer the current one, which brings together the idiosyncratic name (aves -> birds) and design choices (colourful and thick borders). Also, making it flat with 4 basic colours would make it look like a Google product wannabe.

**Comment by deckerst** [comment]
By the way, if you want to have a laugh [here's the logo in the first commit](https://github.com/deckerst/aves/commit/d9695b0c680ba5cc88f0a200837d215a832c55f1#diff-21a9d156e52f237727f2fb32c82c5db4aacc6b045d7f1ecb37cb5cad91786741), back in summer 2019.

**Comment by eusi** [comment]
Thanks for your reply, even you wont implement my stuff haha ;-)
It is as it is. People are used to things they are used to :-) If all ios apps look identical (or at least follow the same look and feel), and so android do, people tend to think "other/different things" are bad. They are not bad of course, just different. If you would aim for making most money out of the product, I would recommend to go this mainstream way, but since you are doing this for another motivation, I am totally agree with you. Keep going, you are doing a great job :-) 

P.S. I really like your logo, 4 years ago xD
