### ISSUE TITLE
Live search results

### ISSUE THREAD

**Issue by Donkey-Doug** [deckerst/aves#80]
When typing to search, the user needs to press enter before the actual search results are shown. I suggest "live" search results: no need to press enter for the results.

**Comment by deckerst** [comment]
I like your idea about the photo section, but i think it will quickly become a headache for me, as i will have to decide what features from the Collection page get to be here too (sort, group, scale, fast scroll, etc.)

In the end, I'll try and follow F-Stop wisdom to separate the file name filtering from the full search. Adding the live name filtering to the Collection page itself also has the benefit to make it available in some situations where search wasn't available, like picking an image for an album cover.

The thing i don't like with F-Stop is that this filtering button is always there, but I'll make that customizable (like other "quick actions") so people can choose what's important for themselves.

**Comment by Donkey-Doug** [comment]
> I like your idea about the photo section, but i think it will quickly become a headache for me, as i will have to decide what features from the Collection page get to be here too (sort, group, scale, fast scroll, etc.)

I would not add options to sort, group or scale. Just use the same scale used in the rest of the app before the user started searching. Sorting should be done by best match. Grouping seems over exaggerated and not needed.

**Comment by deckerst** [comment]
In the next release there will be a live title filter action, separate from the main collection search. The filtering can be combined with other typical filters, and used when picking a cover. It is locked when selecting items, to prevent ambiguity.

As the quick actions on that page are now customizable, you can show it instead of the search button if you feel like it:
<img src="https://user-images.githubusercontent.com/13898333/140244517-d13fe19f-4a70-4326-b8d3-3f78733fe14b.png" height="200" />
