### ISSUE TITLE
Touch-friendly seekbars

### ISSUE THREAD

**Issue by Donkey-Doug** [deckerst/aves#81]
I have two problems with the current seekbar:
- The line is too thin. I often miss it.
- Trying to use the seekbar results in me activating my gesture to switch apps. This is because of how low the seekbar is.

Suggestion:
Make the seekbar thicker. This will automatically raise it slightly and hopefully I do no longer accidentally trigger my gestures. It would also be more touch friendly. Finally, it fits m with the UI - it would look very nice and consistent with the buttons, which have a nice blur effect. 

Current:
![Screenshot_20211001-045055_Aves](https://user-images.githubusercontent.com/50382414/135558055-be5f8da8-3df9-48ac-b725-00f761578e38.png)

Suggestion:
![khnOb](https://user-images.githubusercontent.com/50382414/135557475-b7eb02f5-a19b-4eff-91af-b71b77f68d42.png)

Reference:
https://android-arsenal.com/details/1/6291#!description

**Comment by deckerst** [comment]
The seekbar is responsive to touch not only on the thin blue line, but on the whole blurry area within the outline. The height of that area should be at least 48dp, just like the buttons. I'll double-check.

But with your screenshot (thanks for that), I realize that your seekbar is so low because you hide the optional information below. I will make sure there's a minimum padding between the bar and the screen bottom edge, raising it above your app switch gesture area.

**Comment by Donkey-Doug** [comment]
I just checked and the height with information seems perfect. I suggest just removing the info without lowering the seekbar.
