### ISSUE TITLE
Rescan doesn't find new media

### ISSUE THREAD

**Issue by telrod11** [deckerst/aves#839]
**Describe the bug**
Rescan fails to include new media in viewer. 

**To Reproduce**
1. Open Aves
2. Look for media that was added today and find it isn't there
3. Hit rescan
4. Media still not found

Tested my library with a couple other gallery apps (f-stop, memoria, simple gallery) and all show the missing media when set to "Newest", just as I have aves set. 

**Expected behavior**

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem. If they are too private for this public space, feel free to [send them by email](mailto:gallery.aves@gmail.com).

**System information and logs:**
In the app, there are instructions in the `About` page > `Bug Report` section. After following them, paste here your system information and attach your logs.

**Additional context**

**Comment by deckerst** [comment]
`Rescan` in Aves does not do what you think it does. It's only useful to use that function when a new release of Aves introduces new cataloguing features (like detecting motion photos).

Apps cannot force the system Media Store to rescan media. This is not a thing.

If media is missing in Aves, it can be either:
- media is not where you expect (for example you expect a newly downloaded file at the top, but it contains an old date so it's down below),
- media files were not moved properly, and the Media Store is not aware about it, so Aves is not either,
- the Media Store is aware about these media files, but Aves didn't get the memo. That's possibly a bug like #829.

**Comment by telrod11** [comment]
I'm unsure how other gallery apps I mentioned are able to see these changes, but aves is not.

If aves is WAD, great, but I thought you'd like to know others can do it, and do it very well.

Apologies for bringing it up.

**Comment by deckerst** [comment]
"WAD"?

As i said, there's possibly a bug in Aves. But other galleries may scan themselves the file system (if they have permission to do so), and bypass the OS media segregation altogether. So the fact that other galleries show something is interesting but can be misleading for diagnostic.

> Apologies for bringing it up.

No need. It's good to know that the current way doesn't seem to work in all situations, but i need way more details to act on that kind of reports.

**Comment by telrod11** [comment]
WAD
Works As Designed

I will report back that aves eventually found the missing media but it took almost 12 hours for that to happen.

Thanks for listening.

**Comment by brumwald** [comment]
I recognize Aves isn't to blame here, but I'm making this comment because this is one of the top hits on google when searching for this issue.

For someone not into android development I wasn't even aware of Media Store being a thing. Which I guess makes it even more frustrating because you are looking in the wrong direction. 

I have this problem pretty much every time I change phone, I usually sync up old albums using termux (with rsync or scp) and seems like the Media Store refuses to pick it up. New items / photos get's recognized immediately but it never finds the old ones (the behavior doesn't quite make sense to me, but anyway). Sometimes it can solve itself after a day or two but this time I got fed up after a week.

According to someone on the internet you can use adb to tell Media Store to rescan:
`adb shell content call --method scan_volume --uri content://media --arg external_primary`

This can take quite some time so to get some feedback you can look at the logs:
`adb logcat -s MediaProvider`

This instantly resolved my issues.
