### ISSUE TITLE
Unexpected back behavior in search

### ISSUE THREAD

**Issue by Donkey-Doug** [deckerst/aves#85]
Pressing back on the search results closes the app, instead of bringer the user back to the previous view.

**Comment by kha84** [comment]
Probably a small variation of the described issue:
- open some photo and swipe it up to see details (info + tags)
- tap on some tag - a new search is created with this tag applied. So far so good
- press android "back" button

Expected behavior: it should return me back to seeing that view with photo details 

Current behavior: a tooltip appears "tap back again to exit"
