### ISSUE TITLE
weird tag reading issue

### ISSUE THREAD

**Issue by Ingegneus** [deckerst/aves#886]
idk what is causing this, but I have a few images where the tags aren't read properly. unfortunately I can't reproduce the behaviour on other files. 
here is the file:
https://drive.google.com/file/d/1SiAlv4WatYo5KWhBC0NoH7PTqhO0NNUJ/view?usp=sharing
I will remove the access after you have downloaded it.

this is what I see in the metadata section in aves.
![Screenshot_20240126_182453_Aves](https://github.com/deckerst/aves/assets/78076361/c09b35c6-b7a2-479f-863b-aeb6329438e3)

the metadata should be readable because digikam can still view it (even after rereading the metadata from the file)
I tried rewriting the metadata to the file via digikam, but that didn't work, so then I thought that syncthing corrupted the file somehow, so I redownloaded all files with syncthing, but it is still the same. I hashed the file and the pc version has the same sha512 hash as the phone version. so I am pretty sure, that the file is ok.

so what is happening here?

**Comment by deckerst** [comment]
Thanks for the report. I have downloaded the file. I'll take a look.

**Comment by deckerst** [comment]
That image is malformed, and that makes it trip some metadata reading libraries I'm using (specifically [metadata-extractor](https://github.com/drewnoakes/metadata-extractor/) and [pixymeta](https://github.com/deckerst/pixymeta-android/)). The fallback metadata you see in the `Info` page comes from another library ([exifinterface](https://developer.android.com/jetpack/androidx/releases/exifinterface)), which is apparently less sensitive to malformed files.

**Comment by deckerst** [comment]
So, looking into it further, one JPEG segment is declared with length 0, so the readers can't go further because it would mess all indices. `metadata-extractor` and `pixymeta` just throw an error and yield nothing, while `exifinterface` stops reading further and yields what it decoded until the malformed segment.

In any case, even I showed its metadata it's unsafe to deal with such a file. You couldn't safely edit it.

I'll close this issue, as the problem lies with the software that edited this file.

**Comment by Ingegneus** [comment]
Thanks for the quick response!
