### ISSUE TITLE
Show externally edited image when returning to Aves

### ISSUE THREAD

**Issue by TechD123** [deckerst/aves#888]
**Is your feature request related to a problem? Please describe.**
Aves doesn't ship with an editor, so users rely on external apps for this. The flow is like this:

- user taps edit while viewing image with Aves
- default image editor opens (say Fossify Gallery)
- Image is edited (either replaced or saved as a new file)
- User returns to Aves, but is still looking at the old image
- The user has to exit image viewing and waits about ten seconds for the new/modified image to show up in the timeline

**Describe the solution you'd like**
Of course this isn't ideal and doesn't fit with the otherwise polished UX of Aves. The perfect solution would be to open the image directly afterwards. Perhaps this could be accomplished in this way (sorry if not feasible, just an idea):

- user leaves Aves to edit (trigger ready)
- as soon as Aves registers foreground activity again in a time frame of say one minute (trigger set off), Aves scans for new images (maybe more than once, to account for slow hardware or large image sizes) to catch the change ASAP
- if any new (look at timestamp) image is detected, it is displayed in viewing mode
- Optionally, Aves could only open new pictures if they are close to the original filename... but are there any realistic scenarios where users would have other apps generating other images at the same time?

**Describe alternatives you've considered**
Perhaps Aves could explicitly support certain apps with image editing capabilities, but I feel like an independent solution would be preferable.

Thank you for this amazing gallery app!

**Comment by deckerst** [comment]
Your request actually deals with 2 different things:
1) slow discovery of new items
2) showing the newly edited item

For 1), it's been reported in other issues: #900, #829, #760, etc. It's not something I experience myself, and I don't know yet why it does so on some devices and not others.

For 2), it's not as simple as you make it sound because the edited item does not necessarily fit in the current collection. For example, you open the Camera album, you edit an item with Snapseed which saves the edited version in its own album, so when you come back to Aves, the new item is not in your current collection.

I opted for a more explicit but versatile solution, showing to a user who just returned to Aves from the editor app a prompt to show the newly edited item. If the user chooses to do so, it will go to the Collection page at the right place. The current collection filters are preferably kept as is, but if the newly edited item would be excluded by these filters, all the filters will be removed so that the new item is in view.
