### ISSUE TITLE
Image resolution read incorrectly

### ISSUE THREAD

**Issue by Supetorus** [deckerst/aves#896]
**Describe the bug**
One image has resolution read incorrectly. It has a resolution of 4032 x 3024, but the app reads that it has resolution of 49167 x 53259. Image also renders poorly (pixelated and incorrect width / height ratio.

**To Reproduce**
Error only happens with a specific photo. I will email the photo once I submit this issue.

**System information and logs:**
Package: deckers.thibault.aves
Installer: com.android.vending
Aves version: 1.10.3-play, build 112
Flutter: stable 3.16.9
Android version: 14, API 34
Android build: UQ1A.240105.004.A1
Device: Google Pixel 7a
Support: dynamic colors=true, geocoder=true, HDR=true
Mobile services: ready
System locales: en_US
Storage volumes: /storage/emulated/0/
Storage grants: /storage/emulated/0/Pictures/, /storage/emulated/0/Documents/, /storage/emulated/0/DCIM/, /storage/emulated/0/Android/media/
Error reporting: true

**Additional context**
Logs and photos included in email.

**Comment by deckerst** [comment]
Thanks for the report, I'll take a look.

**Comment by deckerst** [comment]
Same behaviour on my device. Apparently, the Android media store reports the wrong size, but using the standard Android classes [BitmapFactory](https://developer.android.com/reference/android/graphics/BitmapFactory) or [MediaMetadataRetriever](https://developer.android.com/reference/android/media/MediaMetadataRetriever) yields the correct size. Android is so baffling in its inconsistencies...

Anyway, I'll see what I can do to fetch the proper size of images without decreasing performances to check them.

**Comment by deckerst** [comment]
Fixed.

In order to correct the size for an existing image, it won't be enough to select the image and do a rescan. You'll have to trigger the discovery of that image as if it was new. You could for example rename or move it via another file manager app (*not* in Aves).

By the way, I've also noticed that the problematic file contains some broken XMP metadata. Maybe that's why this image is causing trouble (the other image you sent me, with the right size, does not include XMP). Maybe the tool you used to tag people in the picture messed the image structure a little bit.

**Comment by Supetorus** [comment]
Thanks for getting this fixed so quick! And thanks for the heads up on the
corrupted xmp. I use digikam to tag my photos and I sync them between
devices with syncthing. Maybe there there was a conflict between syncing
and editing somehow.
