### ISSUE TITLE
App keeps crashing

### ISSUE THREAD

**Issue by LoookMaan** [deckerst/aves#914]
**Describe the bug**
The app keeps crashing when I opened it every time. Even when I opened it and left it idle, but I also noticed it crashed when cataloguing. The large cataloguing goes on fine, but it keeps crashing on the smaller amount cataloguing. I've cleared the data of the app multiple times, reinstalled it from play store and fdroid, same problem.

**To Reproduce**
1. Open the app
2. Left it loading and idle
3. See error / crashes

**Expected behavior**
Cataloguing finishes and app works fine

**Screenshots**
I'm not sure what kind of screenshot to put here...sorry

**System information and logs:**
Package: deckers.thibault.aves.libre
Installer: com.google.android.packageinstaller
Aves version: 1.10.4-libre, build 11302
Flutter: stable 3.16.9
Android version: 12, API 31
Android build: SKQ1.211019.001 test-keys
Device: Xiaomi M2007J20CG / Xiaomi Poco X3 NFC
Support: dynamic colors=true, geocoder=true, HDR=true
Mobile services: not available
System locales: en_GB
Storage volumes: /storage/emulated/0/, /storage/2343-0CD9/
Storage grants: 
Error reporting: false
[aves-logs-20240219_124639.txt](https://github.com/deckerst/aves/files/14329525/aves-logs-20240219_124639.txt)

**Additional context**
I've actually encountered this problem about half a year ago, I thought it's just a common bug so I uninstalled it hoping it'll be fixed in a few months time. I didn't read the forum as I'm quite busy as a student. Got some free time recently and digged through GitHub a bit and saw a post with similar problem as mine but it's already been resolved.

**Comment by deckerst** [comment]
Thanks for the report.

> The large cataloguing goes on fine, but it keeps crashing on the smaller amount cataloguing

I don't understand. What is the large and small cataloguing?

The cataloguing happens when new items are discovered. When there are a few items, cataloguing happens in the main process, and you can see feedback as a subtitle in the app title bar. If there are a lot of newly discovered items, cataloguing happens in a different process, and you can see feedback in a system notification.

> I've actually encountered this problem about half a year ago, I thought it's just a common bug so I uninstalled it hoping it'll be fixed in a few months time. I didn't read the forum as I'm quite busy as a student. Got some free time recently and digged through GitHub a bit and saw a post with similar problem as mine but it's already been resolved.

I can crash for various reasons during cataloguing. Sometimes because of specific media files that trip libraries I'm using, or large files are badly handled and it uses all the memory, etc. Some of these issues are fixed, but for some I need more reports/details.

In your case, I don't see the crash in the logs. What you could do for now is to launch the app via the "safe mode" shortcut (which disables cataloguing) and see whether you can open and browse your media. I'll try and think of a way to pinpoint the cause of your crash.

**Comment by deckerst** [comment]
Another thing you can do is to install the `play` version of Aves, allow the automatic error reporting, and let it crash a couple of times. These reports are anonymous, but I can try and search crashes from devices matching your specs.

**Comment by deckerst** [comment]
Could you please try the new release v1.10.5 and let me know if the crash still happens? The release is already on the Play Store as beta, and will soon be available everywhere.

Again, installing the Play Store version and enabling automatic error reporting is the most helpful to debug these crashes.

**Comment by deckerst** [comment]
@LoookMaan Does it still crash with the latest version of Aves?

If so, could you try [this](https://github.com/deckerst/aves/issues/977#issuecomment-2061905514)?
