### ISSUE TITLE
Tags disappeared

### ISSUE THREAD

**Issue by JoeHardi** [deckerst/aves#943]
**Describe the bug**
I had almost all pictures tagged. Those tags disappeared today. If I click on a picture the tag becomes visual again, but only for this picture.

**To Reproduce**
1. Open Aves Libre
2. Click on a album
3. See no tags
4. By clicking on a picture, tag becomes visual again but only for this picture.

**Expected behavior**
See all tags.

**System information and logs:**
Package: deckers.thibault.aves.libre
Installer: com.looker.droidify
Aves version: 1.10.5-libre, build 11402
Flutter: stable 3.19.1
Android version: 13, API 33
Android build: lineage_pdx214-userdebug 13 TQ3A.230901.001 eng.root.20240213.054336 dev-keys
Device: Sony Xperia 5 III
Support: dynamic colors=true, geocoder=false, HDR=true
Mobile services: not available
System locales: en_US
Storage volumes: /storage/emulated/0/
Storage grants: /storage/emulated/0/Movies/, /storage/emulated/0/Pictures/, /storage/emulated/0/DCIM/, /storage/emulated/0/02 Bilder/, /storage/emulated/0/Android/media/
Error reporting: false

**Comment by deckerst** [comment]
> 2. Click on a album
> 3. See no tags

This does not make sense, as clicking on an album is not supposed to show tags. Or maybe you call "tag" something else?

In any case, if your images do indeed contain tags, you could rescan them by selecting all your collection and going to the `...` menu > `Rescan`. The process may take a while, but do you see your tags at the end of the rescan?

**Comment by JoeHardi** [comment]
Hey sorry,

I wrote it a little unclear.

I tagged a lot of pictures with tags like "Mother", " Father" and so on.
When I click on an album, where I see all the picture afterwards, I do not have anymore tags. Also when clicking in "Tags" it simply shows nothing.

Reloading, as you said, does not solve the problem.


11. März 2024, 22:00 von ***@***.***:

**Comment by deckerst** [comment]
Would you mind sharing an image that contains tags that should be listed in the `Tags` page of Aves but do not on your device?

If you could also screenshot the `Info` page of that item, that would be helpful.

**Comment by JoeHardi** [comment]
Of course! Thank you very much for taking care of that!

**Before** clicking on picture "1" no tag was shown. Even in the tags partition the tag "Aviation" won't show up. Picture "2" is the info page of picture "1".

![1](https://github.com/deckerst/aves/assets/75334779/e3492a44-dffa-4686-87c3-a3202002e902)
![2](https://github.com/deckerst/aves/assets/75334779/323cbcb8-fb2b-4dba-8a5c-464b3bbf935d)

Here an example: Before clicking on the picture in the top left corner in "A" no tags is shown. After clicking on the picture once, the tag shows up, like in "B".

![A](https://github.com/deckerst/aves/assets/75334779/1e49f0d1-0675-48f5-9bcb-8d432216824b)
![B](https://github.com/deckerst/aves/assets/75334779/4265cf2b-3bab-4344-80a3-0ee5d088c190)

**Comment by deckerst** [comment]
Thanks. "Aves" and "Aves Libre" should work the same. I can't reproduce the issue, but maybe there's something special with your environment, being Lineage and all.

Could you please attach here the logs you get from `About` > `Bug Report` (it seems missing from the report above)? Preferably, please save the logs after selecting some tagged items and doing a `Rescan` on them (from the `Collection` page menu).

**Comment by JoeHardi** [comment]
Done
[aves-logs-20240316_210635.txt](https://github.com/deckerst/aves/files/14625145/aves-logs-20240316_210635.txt)

**Comment by deckerst** [comment]
Seems like the analysis service is trying to start every second. That's weird, and it may be draining your battery too.

Normally, the analysis service starts when there are lots of newly discovered items, in order to read their metadata, register the discovered tags, etc. So typically you start the app for the first time and it finds, say, 10k new items so the service starts in the background and a notification is displayed to show progress. When the service is done, or if you reopen the app in between, you should see the discovered tags so far. But it seems that on your device the service fails to start, so maybe that's why tags do not appear and you only see the tags that are discovered on the fly when opening items in the viewer.

If you have nothing in the recycle bin or vaults, you could try to 1) uninstall, 2) reinstall, 3) clear app data (in case it got initialized from an automatic backup/restore), 4) make sure you enable notification permission (for analysis service feedback), 4) launch the app.

If you still have the issue with a clean reinstall, I'll try and investigate if lineage can mess up services.
