### ISSUE TITLE
Collection reinitializes when app reopens from launcher

### ISSUE THREAD

**Issue by Aballoffox** [deckerst/aves#970]
**Describe the bug**
When I leave Aves in the background (not killed), and restart it by clicking the icon of Aves on the Desktop, it will get a bug just as the screenshot (it seems to re-scan the mediastore). This may last for about three seconds, and then become normal. This bug can be reproduced 100% successfully.
**To Reproduce**
1. Start Aves
2. Back to Desktop
3. Click the icon of Aves on the Desktop

**Screenshots**
![Screenshot_20240408_185311_deckers thibault aves_](https://github.com/deckerst/aves/assets/126940138/fa220e11-b0bc-4b1f-8b15-93807a2b32b9)

**Additional context**
The version of Aves is 1.10.8, and this bug appeared just after I updated to this version.
My phone is Huawei M40P, HarmonyOS 4.0.0.132. I've turned off battery optimization to prevent the OS from killing this app, but it did not work.

**Comment by deckerst** [comment]
Since v1.10.8, reopening Aves via the launcher icon is different from reopening it via the recent apps.
It's on purpose that opening it via the launcher icon shows the home page (even if the app hasn't been killed), but it's true that the store initialization is likely superfluous and should be skipped in this case.
