### ISSUE TITLE
Regression: slow startup speed

### ISSUE THREAD

**Issue by DaleBCooper** [deckerst/aves#973]
When opening version 1.10.8 all albums are shown as a white background and it takes up to 2 or 3 seconds until the album thumbnails are shown.

With version 1.10.7 all albums are shown instantly when opening the app, even when it was killed.

Installed from fdroid on a Pixel 7a.

**Comment by deckerst** [comment]
You mention that it happens even when the app is killed, but in any case, your issue is similar to that one: 
- #970 

So, could you please try [this build](https://drive.google.com/file/d/1KfsSUqS21BnfkCnk4KtI3CbQv6ZtmPcx/view?usp=drivesdk), which contains the fix for #970? It will install as "Aves [Profile]" and is a separate app (with its own settings, etc.) It will scan your whole collection on first launch, so please do not assess the launch performance until all this is done and the app is stable.

**Comment by DaleBCooper** [comment]
I can confirm the fix from #970 resolves the issue. It's as fast as 1.10.7.
Thank you very much for the fast response!
Not only is Aves Libre the best gallery app for android, it also has the fastest support. :⁠-⁠)
