### ISSUE TITLE
Text wrapping in info section

### ISSUE THREAD

**Issue by Donkey-Doug** [deckerst/aves#98]
There are two minor imperfections visible in the screenshot below:

![Screenshot_20211004-182149_Aves_1](https://user-images.githubusercontent.com/50382414/135888137-3127f5d5-a4e7-4a9d-b1f9-0bd4daabbec6.png)

- The text next to title and path go all the way to the left when the text exceeds 1 line
- "Owned by" shows an icon. This icon is also slightly offset to the left

**Comment by deckerst** [comment]
> The text next to title and path go all the way to the left when the text exceeds 1 line

This is on purpose. Horizontal space is precious, especially for people with smaller devices or larger fonts.

> "Owned by" shows an icon. This icon is also slightly offset to the left

Agreed, the misalignment bugs me too!

But funnily, when I saw the title of your issue, I thought you saw the more serious layout issue on this page:
<img src="https://user-images.githubusercontent.com/13898333/135956525-69e2ecd4-a146-46e4-9151-c93319e0aed5.png" height="400" />

URI & paths are often wrapped in weird places, because of this [Flutter issue](https://github.com/flutter/flutter/issues/61081) and the workarounds break other aspects :/
